const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name)=>{const paths={overview:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',lineup:'<rect x="3" y="3" width="18" height="7" rx="2"/><rect x="3" y="14" width="18" height="7" rx="2"/><path d="M6 6h1m-1 11h1m5-11h6m-6 11h6"/>',platforms:'<rect x="6" y="6" width="12" height="12" rx="2"/><path d="M9 1v5m6-5v5M9 18v5m6-5v5M1 9h5m-5 6h5m12-6h5m-5 6h5"/>',components:'<path d="M3 7l9-5 9 5-9 5zM3 12l9 5 9-5M3 17l9 5 9-5"/>',quiz:'<path d="M9 3h6l1 3h4v16H4V6h4zM8 13l2 2 6-6M8 19h8"/>',sources:'<path d="M12 5C9 2 4 3 2 4v16c4-2 7-1 10 1 3-2 6-3 10-1V4c-2-1-7-2-10 1v16"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.overview}</svg>`};
const sections=[['overview','The big picture'],['lineup','Explore the lineup'],['platforms','AMD & Intel'],['components','Storage & GPUs'],['quiz','Test your knowledge'],['sources','Sources & glossary']];
const state={page:'overview',mode:'standard',concept:'chassis',selected:new Set(),filters:{q:'',family:'All',vendor:'All',use:'All'},quizIndex:0,answers:Array(quiz.length).fill(null),drive:'sff'};
const sourceLink=(id,label)=>`<a href="${sources[id].url}" target="_blank" rel="noopener noreferrer">${label||sources[id].title} ↗</a>`;
const cite=(id)=>`<div class="detail-source">${sourceLink(id)} <span> · ${sources[id].loc}</span></div>`;
const intro=(label,title,desc)=>`<div class="page-intro"><div class="eyebrow">${label}</div><h1>${title}</h1><p>${desc}</p></div>`;
function physicalCaption(m){const p=physicalData[m.id];return p?`<p class="physical-caption">${p.reviewStatus==='schematic'?'Layout schematic · ':''}${esc(p.view)}</p>`:'';}
function physicalDetail(m){const p=physicalData[m.id];return p?`<details class="physical-reference"><summary>About this illustration</summary><p><b>${esc(p.view)}</b></p><p>${esc(p.caveat)}</p><p><a href="${esc(p.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(p.sourceTitle)} ↗</a><br><span class="muted">${esc(p.locator)}</span></p></details>`:'';}
let artSerial=0;
function hardware(shape='rack2',hero=false){
 const key=({rack1:'c220',rack2:'c240',rack4:'c845',rack8:'c885',rack10:'c880',node:'x215',wideNode:'x410',edge:'xe130',edge2:'xe150'})[shape]||shape.replace('ucs-','');
 const uid='ucs-physical-'+(++artSerial), metal=`url(#${uid}-metal)`, mesh=`url(#${uid}-mesh)`;
 const rect=(x,y,w,h,fill='#222d34',stroke='#85959b',r=1)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="${fill}" stroke="${stroke}" stroke-width=".7"/>`;
 const vent=(x,y,w,h)=>rect(x,y,w,h,mesh,'#627680');
 const drive=(x,y,w,h,green=false)=>rect(x,y,w,h,'#18252c')+rect(x+2,y+2,w-4,h-4,'#34454c','#6d8189')+`<path d="M${x+4} ${y+h-5}h${Math.max(2,w-9)}" stroke="#b3c6cc"/><rect x="${x+2}" y="${y+2}" width="${Math.min(4,w-4)}" height="${h-4}" fill="${green?'#96bf54':'#263740'}"/><circle cx="${x+w-3}" cy="${y+h-3}" r="1" fill="#91d4d2"/>`;
 const face=(x,y,w,h,depth=28)=>`<path d="M${x} ${y}l${depth} -${depth*.8}h${w}l-${depth} ${depth*.8}Z" fill="#798b91" stroke="#a1afb3" stroke-width=".7"/><path d="M${x+w} ${y}l${depth} -${depth*.8}v${h}l-${depth} ${depth*.8}Z" fill="#3c4e57" stroke="#73868d" stroke-width=".7"/>${rect(x,y,w,h,metal)}`;
 const ears=(x,y,w,h)=>rect(x,y,9,h,'#b2bfc1')+rect(x+w-9,y,9,h,'#a0b1b8')+`<circle cx="${x+4.5}" cy="${y+5}" r="1.5" fill="#44525a"/><circle cx="${x+w-4.5}" cy="${y+h-5}" r="1.5" fill="#44525a"/>`;
 const label=(x,y,t,size=6)=>`<text x="${x}" y="${y}" fill="#d5e3e8" font-size="${size}" font-family="Consolas,monospace">${t}</text>`;
 const frontNode=(x,y,w,h,wide=false)=>{
  if(w<12)return rect(x,y,w,h,metal)+Array.from({length:6},(_,i)=>rect(x+1+(i%2)*(w-2)/2,y+4+Math.floor(i/2)*(h-10)/3,Math.max(.7,(w-4)/2),(h-15)/3,'#253943','#879ca4')).join('');
  let s=rect(x,y,w,h,metal)+vent(x+3,y+3,w-6,9);const half=wide?w/2:w;
  for(let row=0;row<3;row++)for(let col=0;col<2;col++)s+=drive(x+3+col*(half-6)/2,y+15+row*(h-32)/3,(half-8)/2,(h-38)/3);
  if(wide)s+=vent(x+half+2,y+15,half-5,h-28);
  return s+`<path d="M${x+2} ${y+15}v${h-29}m${w-4} 0v-${h-29}" fill="none" stroke="#bfd0d4" stroke-width="1.3"/><circle cx="${x+5}" cy="${y+h-7}" r="1.5" fill="#94e1b6"/>`;
 };
 const enclosure=(x,y,w,h,active=-1,span=1)=>{
  let s=rect(x,y,w,h,metal);let slot=(w-30)/8;
  for(let i=0;i<8;i++)s+=frontNode(x+10+i*slot,y+5,slot-1,h-10)+ (i===active?`<rect x="${x+9+i*slot}" y="${y+4}" width="${slot*span+1}" height="${h-8}" fill="none" stroke="#66d5e4" stroke-width="1.4"/>`:'');
  for(let i=0;i<6;i++)s+=vent(x+w-17,y+6+i*(h-12)/6,12,(h-18)/6);
  return s;
 };
 let body='',description='';
 if(key==='chassis'){
  body=face(63,18,218,152,16)+enclosure(63,18,218,152);description='X9508 front: eight vertical compute slots and six right-side power bays';
 }else if(['x210','x215','x410'].includes(key)){
  const wide=key==='x410',w=wide?48:24,x=67,y=25,h=145;
  body=`<path d="M${x+w} ${y}l120 -15v${h}l-120 15Z" fill="#52666f" stroke="#9db0b8"/><path d="M${x} ${y}l120 -15h${w}l-120 15Z" fill="#8fa0a6" stroke="#b0c0c5"/><path d="M${x+w+8} ${y+15}l103 -13v${h-36}l-103 13Z" fill="#667d86" stroke="#80959c"/>${frontNode(x,y,w,h,wide)}`;
  body+=enclosure(258,104,87,62,wide?0:2,wide?2:1)+label(255,94,wide?'2 CHASSIS SLOTS':'1 CHASSIS SLOT',6);
  description=`${key.toUpperCase()} M8 extracted vertical compute sled with six SFF drive carriers; X9508 context inset`;
 }else if(['xe130','xe150'].includes(key)){
  const large=key==='xe150',x=55,y=large?67:94,w=238,h=large?84:42;
  body=face(x,y,w,h,28);const by=large?y+42:y;
  body+=vent(x+7,by+4,85,8)+vent(x+107,by+4,121,15);
  if(!large)body+=drive(x+7,by+13,85,10,true);
  body+=drive(x+7,by+24,85,10,true)+drive(x+150,by+23,81,9,true)+drive(x+150,by+33,81,8,true);
  body+=rect(x+108,by+25,15,12,'#0d151c')+rect(x+125,by+25,15,12,'#0d151c')+label(x+9,by+40,'USB   ●  ◌',5);
  if(large)body+=rect(x+5,y+4,72,34,'#7b8e95')+vent(x+86,y+5,140,17)+[0,1,2,3].map(i=>rect(x+92+i*31,y+28,24,7,'#111e26')).join('');
  description=large?'XE150c half-width 2U module: upper accelerator bracket above three-drive I/O front':'XE130c half-width 1U module: four-drive storage front, two RJ45 ports';
 }else if(['c880','c885'].includes(key)){
  const tall=key==='c880',x=tall?104:91,y=20,w=tall?152:179,h=150;
  body=face(x,y,w,h,20)+ears(x,y,w,h);
  const rows=tall?7:8,ry=y+5,rh=tall?15:17;
  for(let i=0;i<rows;i++)body+=rect(x+10,ry+i*(rh+1),w-20,rh,'#8c9fa7')+vent(x+27,ry+i*(rh+1)+1,w-40,rh-2);
  if(tall){body+=vent(x+12,y+121,34,21)+vent(x+w-47,y+121,34,21);for(let i=0;i<8;i++)body+=drive(x+49+i*6.5,y+123,5.5,16,true);}
  description=tall?'C880A M8 10U front with grille stack above lower I/O and E1.S bay section':'C885A M8 8U front with eight horizontal grille bands';
 }else if(key==='c845'){
  const x=24,y=54,w=289,h=112;body=face(x,y,w,h,26)+ears(x,y,w,h);
  for(let i=0;i<3;i++)body+=vent(x+19+i*87,y+5,81,20);
  body+=vent(x+20,y+30,38,18);for(let i=0;i<20;i++)body+=drive(x+61+i*10.4,y+30,9,20,true);
  for(let i=0;i<5;i++)body+=vent(x+17+i*51.5,y+57,47,49)+`<circle cx="${x+40.5+i*51.5}" cy="${y+81.5}" r="19" fill="none" stroke="#40545e" stroke-width="2"/>`+rect(x+58+i*51.5,y+72,4,19,'#94b95a');
  description='C845A M8 4U front: upper I/O, twenty E1.S bays, five lower fan modules';
 }else{
  const one=['c220','c225'].includes(key),x=15,y=one?99:80,w=307,h=one?29:58;body=face(x,y,w,h,24)+ears(x,y,w,h);
  if(key==='c225')body+=vent(x+48,y+4,112,h-8)+vent(x+188,y+4,104,h-8)+label(x+163,y+17,'cisco',6)+`<circle cx="${x+32}" cy="${y+15}" r="3" fill="#9eafb5" stroke="#485c65"/>`;
  else if(one){for(let row=0;row<2;row++)for(let col=0;col<5;col++)body+=drive(x+18+col*54,y+3+row*12,52,11);}
  else {for(let i=0;i<24;i++)body+=drive(x+17+i*11.35,y+5,10.1,h-10);}
  description=key==='c225'?'C225 M8 1U rack, security bezel fitted':`${key.toUpperCase()} M8 ${one?'1U, ten SFF carriers in two rows':'2U, twenty-four vertical SFF carriers'}; bezel removed`;
 }
 return `<svg viewBox="0 0 360 180" role="img" aria-label="${description}"><title>${description}</title><defs><linearGradient id="${uid}-metal" x2="0" y2="1"><stop stop-color="#a5b3b7"/><stop offset=".2" stop-color="#71858d"/><stop offset="1" stop-color="#3e535d"/></linearGradient><pattern id="${uid}-mesh" width="4" height="4" patternUnits="userSpaceOnUse"><rect width="4" height="4" fill="#15232b"/><circle cx="2" cy="2" r="1.1" fill="#53656e"/></pattern></defs>${body}</svg>`;
}
function node(id,x,y,w,h,label,sub='',opts={}){return `<g class="node ${state.concept===id?'selected':''}" data-concept="${id}" role="button" tabindex="0" aria-label="${esc(opts.aria||label||concepts[id].name)}" aria-pressed="${state.concept===id}"><rect class="surface" x="${x}" y="${y}" width="${w}" height="${h}" rx="${opts.r||7}"/>${opts.content||`<text x="${x+w/2}" y="${y+h/2-(sub?4:-5)}" text-anchor="middle" class="label">${label}</text>${sub?`<text x="${x+w/2}" y="${y+h/2+15}" text-anchor="middle" class="sublabel">${sub}</text>`:''}`}</g>`;}
function architecture(){
 const direct=state.mode==='direct',rack=state.mode==='rack';
 let svg=`<defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".6" fill="#3e535c" opacity=".45"/></pattern></defs><rect width="1000" height="500" fill="#0d171f"/><rect width="1000" height="500" fill="url(#grid)"/>`;
 if(!rack){
 svg+=`<path class="trace management" d="${direct?'M295 91H332V303H355':'M192 125V182H365'}"/><path class="trace" d="M615 88v34H465v31M615 122h150v31"/>`;
 svg+=node('intersight',47,58,248,67,'Cisco Intersight','Operations & policies');
 svg+=node('upstream',420,31,390,57,'Upstream network','Ethernet / optional storage network');
 if(!direct){svg+=node('fi',365,153,200,59,'Fabric interconnect A','External');svg+=node('fi',665,153,200,59,'Fabric interconnect B','External');}
 svg+=`<rect x="80" y="235" width="840" height="235" rx="13" fill="#101f28" stroke="#537783" stroke-width="1.5"/><text x="103" y="258" class="tiny">X9508 CHASSIS</text><text x="604" y="258" class="tiny" text-anchor="middle">7U · 8 FRONT NODE SLOTS</text>`;
 svg+=node('chassis',846,242,56,27,'', '', {content:'<text x="874" y="260" text-anchor="middle" class="sublabel">Inspect</text>'});
 svg+=node(direct?'fi':'ifm',355,280,220,47,direct?'Embedded FI A':'IFM A',direct?'9108 100G':'Rear networking module');
 svg+=node(direct?'fi':'ifm',655,280,220,47,direct?'Embedded FI B':'IFM B',direct?'9108 100G':'Rear networking module');
 svg+=`<path class="trace" d="M465 ${direct?153:212}V280M765 ${direct?153:212}V280M465 327v23M765 327v23"/>`;
 if(direct)svg+=`<path class="trace management" d="M332 235v68h23"/>`;
 svg+=node('compute',360,350,515,53,'Compute nodes','X210c M8 (Intel) or X215c M8 (AMD)');
 svg+=node('power',103,422,772,28,'', '',{content:'<text x="489" y="440" text-anchor="middle" class="sublabel">SHARED POWER & COOLING</text>'});
 svg+=`<path class="trace optional" d="M210 336v19M318 379h42"/>`;
 svg+=node('xfabric',103,355,215,48,'X-Fabric','Optional PCIe path');
 svg+=node('gpuNode',103,280,215,56,'PCIe expansion node','X580p + qualified GPUs');
 svg+=`<text x="80" y="494" class="tiny">SELECT A PART TO EXPLORE ↓ · MODULE POSITIONS SIMPLIFIED</text>`;
 if(direct){svg+=`<text x="475" y="186" class="sublabel">FIs live inside the chassis</text>`;}
 }else{
 svg+=node('intersight',47,45,242,61,'Cisco Intersight','Optional operations integration');
 svg+=node('upstream',585,45,287,61,'Network switches','Standalone Ethernet connection');
 svg+=`<rect x="86" y="154" width="817" height="307" rx="13" fill="#101f28" stroke="#537783" stroke-width="1.5"/><text x="110" y="183" class="tiny">C-SERIES RACK SERVER · C240 M8-STYLE LOGICAL EXAMPLE</text><path class="trace management" d="M169 106v36H99v97h12"/><path class="trace" d="M729 106v103"/>`;
 svg+=node('imc',111,209,212,59,'Management controller','Cisco IMC');
 svg+=node('vic',648,209,228,59,'Network adapter / VIC','Physical network ports');
 svg+=`<path class="trace" d="M360 250H342V373H271V391M607 255H628V373H672V391"/>`;
 svg+=node('cpu',360,209,247,65,'CPU sockets','1 or 2 × Intel Xeon 6');
 svg+=node('memory',361,297,245,66,'DDR5 memory','DIMMs next to the CPUs');
 svg+=`<path class="trace" d="M484 274v23M648 239h-41"/>`;
 svg+=node('drives',111,391,320,47,'Local storage','Backplane + drives');
 svg+=node('pcie',469,391,407,47,'PCIe expansion','Qualified GPUs / adapters / controllers');
 }
 $('#diagramMount').innerHTML=`<svg class="diagram" viewBox="0 0 1000 500" role="group" aria-label="Interactive ${state.mode} UCS deployment schematic">${svg}</svg>`;
 $('#diagramBlurb').innerHTML=rack?'<b>Standalone rack:</b> the server connects to ordinary network switches and has its own management controller. Fabric integration is a separate, supported deployment option.':direct?'<b>X-Series Direct:</b> the fabric interconnects move inside the X9508. Optional expansion and a second chassis require a supported design.':'<b>Standard X-Series:</b> compute nodes connect through chassis IFMs to an external pair of fabric interconnects. Intersight provides management above the hardware.';
 $$('#modeSwitch button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===state.mode));
 const ids=$$('[data-concept]',$('#diagramMount')).map(n=>n.dataset.concept);
 if(!ids.includes(state.concept))state.concept=rack?'cpu':'chassis';
 setConcept(state.concept,false);
}
function setConcept(id,focus=false){$('#diagramTip').hidden=true;state.concept=id;const c=concepts[id];if(!c)throw new Error('Unmapped concept '+id);$$('[data-concept]').forEach(n=>n.setAttribute('aria-pressed',String(n.classList.toggle('selected',n.dataset.concept===id))));$('#partDetail').innerHTML=`<h3>${c.name}</h3><div class="detail-grid"><div><h4>WHAT IT IS</h4><p>${c.what}</p></div><div><h4>IN THIS DESIGN</h4><p>${c.design}</p></div></div>${cite(c.src)}`;}
function overview(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">AN INTERACTIVE GUIDE TO CISCO UCS</div><h1>Meet the system.<br><em>Understand the lineup.</em></h1><p>Servers are just the start. Explore how Cisco’s compute, networking and management fit together—and where AMD, Intel and GPUs come in.</p><div class="button-row"><a class="btn primary" href="#lineup">Explore the servers <span>↗</span></a><button class="btn ghost" data-scroll="systemMap">Take the system tour <span>↓</span></button></div><div class="source-note">Based on ${sourceLink('catalog','Cisco UCS C-Series Rack Servers')} and ${sourceLink('chassis','Cisco UCS X9508 Chassis Data Sheet')}.</div></div><div class="hero-art">${hardware('chassis',true)}<div class="art-label">X9508 · ILLUSTRATIVE FRONT VIEW</div></div></section>
 <div class="chapter-heading"><h2>Three ways to think about the hardware</h2><span class="small">Start with where it lives.</span></div><section class="family-grid" aria-label="Hardware families">
 <button class="family-card" data-family="Rack"><span class="over">01 / RACK SERVERS</span><span class="arrow">↗</span><div class="hardware">${hardware('rack2')}</div><h3>C-Series</h3><p>Self-contained servers. From compact 1U compute to large, dedicated AI systems.</p><div class="chip-row"><span class="badge intel">Intel Xeon</span><span class="badge amd">AMD EPYC</span></div></button>
 <button class="family-card" data-family="Modular"><span class="over">02 / MODULAR SYSTEMS</span><span class="arrow">↗</span><div class="hardware">${hardware('chassis')}</div><h3>X-Series</h3><p>Server nodes share an enclosure, power, cooling and networking connections.</p><div class="chip-row"><span class="badge intel">Intel Xeon</span><span class="badge amd">AMD EPYC</span></div></button>
 <button class="family-card" data-family="Edge"><span class="over">03 / EDGE SYSTEMS</span><span class="arrow">↗</span><div class="hardware">${hardware('edge')}</div><h3>Unified Edge</h3><p>Compact XE nodes bring compute and acceleration closer to where data is created.</p><div class="chip-row"><span class="badge intel">Intel Xeon 6 SoC</span></div></button></section>
 <section class="panel" id="systemMap"><div class="panel-head"><div><div class="eyebrow">THE SYSTEM, CONNECTED</div><h2 style="margin-top:8px">What makes it “unified”?</h2><p>Choose a deployment. Select any labeled component.</p></div><div class="segmented" id="modeSwitch" aria-label="Deployment mode"><button data-mode="standard" aria-pressed="true">X-Series</button><button data-mode="direct" aria-pressed="false">X-Series Direct</button><button data-mode="rack" aria-pressed="false">Standalone rack</button></div></div><div id="diagramBlurb" class="diagram-notes"></div><div class="diagram-scroll" id="diagramMount"></div><div class="diagram-legend"><div class="legend-items"><span><i class="legend-dot"></i>Network / system connection</span><span><i class="legend-dot" style="background:var(--purple)"></i>Management</span><span><i class="legend-dot" style="background:var(--amber)"></i>Optional PCIe</span></div><span>Logical schematic · placement simplified · pan on mobile</span></div><div class="detail-panel" id="partDetail" aria-live="polite"></div></section>
 <div class="takeaway"><span class="symbol">↳</span><div><h3>UCS is a system. A server is one part of it.</h3><p>A chassis holds nodes. A CPU runs instructions. A fabric interconnect links supported servers to the network. Intersight helps manage the infrastructure. These are different layers.</p></div></div>
 <section class="two-col"><article class="lesson"><div class="eyebrow">READ THE NAME</div><h3 style="margin-top:12px">Cisco UCS X215c M8</h3><div class="name-decoder"><div class="name-piece">X<small>Modular family</small></div><div class="name-piece">215c<small>Compute model</small></div><div class="name-piece">M8<small>Server generation</small></div></div><p>“M8” is a Cisco server generation. It does not mean eighth-generation AMD or Intel silicon. A chassis name, such as X9508, is another product altogether.</p>${sourceLink('x215','See this model')}</article><article class="lesson"><div class="eyebrow">A FEW NAMES YOU’LL ALSO HEAR</div><h3 style="margin-top:12px">B-Series, S-Series & HCI</h3><p><b>B-Series</b> is the classic blade-server line. <b>S-Series</b> includes storage-centric systems such as S3260. Their lifecycle matters when reading older UCS designs.</p><p><b>Cisco Compute Hyperconverged with Nutanix</b> is a validated infrastructure solution using selected hardware and software combinations.</p><a class="text-link" href="#lineup/history">See the older lineup & lifecycle →</a><br>${sourceLink('nutanix','Nutanix solution data sheets')}</article></section>
 <section class="section panel panel-pad"><div class="eyebrow">MANAGEMENT, DECODED</div><h2 style="margin-top:10px">The configuration can live in a profile.</h2><p class="muted">UCS turns repeatable hardware settings into policies. A server profile collects the appropriate policies; a template helps reuse a consistent design across multiple servers.</p><div class="three-col"><article><h3>Cisco IMC</h3><p class="small muted">The individual server’s out-of-band controls: hardware health, remote console and low-level administration on supported rack models.</p></article><article><h3>UCS Manager</h3><p class="small muted">A UCS-domain manager associated with fabric interconnects. You will see service profiles and this management mode in many established deployments.</p></article><article><h3>Cisco Intersight</h3><p class="small muted">An infrastructure operations platform. Intersight Managed Mode handles supported UCS domains; standalone integration has a different scope.</p></article></div><p class="small muted">Think “approved BIOS, boot, firmware and connectivity settings,” not “a copy of the application.” A profile does not make incompatible hardware interchangeable. Available policies depend on management mode and release.</p>${sourceLink('policies','Cisco Intersight Policies Solution Overview')}</section><div class="next-lesson"><p>Next: learn the actual models and compare the choices.</p><a class="btn primary" href="#lineup">Explore the lineup →</a></div>`;}
function render(){const hash=location.hash.slice(1).split('/'),page=sections.some(s=>s[0]===hash[0])?hash[0]:'overview';state.page=page;if(page==='overview')state.mode=['standard','direct','rack'].includes(hash[1])?hash[1]:'standard';$('#nav').innerHTML=sections.map(([id,label],i)=>`<a class="nav-item ${page===id?'active':''}" href="#${id}" ${page===id?'aria-current="page"':''}>${icon(id)}<span>${label}</span><span class="nav-index">0${i+1}</span></a>`).join('');$('#crumb').textContent=sections.find(s=>s[0]===page)[1].toUpperCase();$('#main').innerHTML=page==='overview'?overview():views[page]();if(page==='overview')architecture();afterRender(page,hash[1]);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-mode],[data-concept],[data-scroll],[data-family]');if(!b)return;if(b.dataset.mode){state.mode=b.dataset.mode;architecture();history.replaceState(null,'','#overview/'+state.mode);}if(b.dataset.concept)setConcept(b.dataset.concept);if(b.dataset.scroll)document.getElementById(b.dataset.scroll).scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});if(b.dataset.family){state.filters={q:'',family:b.dataset.family,vendor:'All',use:'All'};location.hash='lineup';}});
document.addEventListener('keydown',e=>{if(e.target.matches('[data-concept]')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setConcept(e.target.dataset.concept);}});
function tipFor(el){const tip=$('#diagramTip');const box=el.getBoundingClientRect();tip.textContent=el.getAttribute('aria-label');tip.hidden=false;const width=tip.offsetWidth,height=tip.offsetHeight;tip.style.left=Math.max(10,Math.min(innerWidth-width-10,box.x+box.width/2-width/2))+'px';tip.style.top=Math.max(10,Math.min(innerHeight-height-10,box.top-height-9))+'px';}
document.addEventListener('pointerover',e=>{const el=e.target.closest('[data-concept]');if(el&&e.pointerType!=='touch')tipFor(el);});
document.addEventListener('pointerout',e=>{if(e.target.closest('[data-concept]'))$('#diagramTip').hidden=true;});
document.addEventListener('focusin',e=>{if(e.target.matches('[data-concept]'))tipFor(e.target);});
document.addEventListener('focusout',e=>{if(e.target.matches('[data-concept]'))$('#diagramTip').hidden=true;});
window.addEventListener('scroll',()=>$('#diagramTip').hidden=true,true);
window.addEventListener('resize',()=>$('#diagramTip').hidden=true);
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});
function selectOptions(values,current){return values.map(v=>`<option ${v===current?'selected':''}>${esc(v)}</option>`).join('')}
function lineup(){return `${intro('02 / EXPLORE THE HARDWARE','Find your way around the lineup.','Start with the form factor, then compare processors, drives and expansion. These '+models.length+' representative models cover current and installed-base UCS choices.')}
 <div class="filterbar"><div class="filter search"><label for="modelSearch">Search the guide</label><input id="modelSearch" type="search" placeholder="Try C245, EPYC, E3.S…" value="${esc(state.filters.q)}"></div><div class="filter"><label for="familyFilter">Family</label><select id="familyFilter">${selectOptions(['All','Rack','Modular','AI','Edge'],state.filters.family)}</select></div><div class="filter"><label for="vendorFilter">CPU vendor</label><select id="vendorFilter">${selectOptions(['All','AMD','Intel'],state.filters.vendor)}</select></div><div class="filter"><label for="useFilter">Explore a use</label><select id="useFilter">${selectOptions(['All','General compute','Virtualization','Storage','AI inference','AI training','Scale-up databases','Edge'],state.filters.use)}</select></div></div>
 <p class="small muted">AI systems are also C-Series rack servers; the AI filter groups them for learning. Use-case tags are educational starting points, not sizing recommendations.</p>
 <div class="filter-count"><span id="modelCount" role="status"></span><button class="btn compact ghost" data-reset-filters>Clear filters</button></div><div class="model-grid" id="modelGrid"></div>
 <div class="compare-tray" id="compareTray" hidden><p id="compareStatus"></p><div style="display:flex;gap:10px"><button class="btn compact ghost" data-clear-compare>Clear</button><button class="btn compact primary" id="compareButton" data-compare>Compare selected →</button></div></div>
 <div class="warning"><strong>Read “up to” carefully.</strong> Drive, memory, slot and GPU ceilings describe qualified options. They may not all be achievable together. Exact processors, risers, backplanes, power, cooling, firmware and software determine a supported system.</div>
 <section class="section" id="history"><div class="eyebrow">THE LINEUP OVER TIME</div><h2 style="margin-top:10px">Names in older UCS designs</h2><p class="muted">Older equipment can remain in service. A last-order date and a last-support date are different milestones.</p><div class="history-list"><article><span class="badge warn">END OF SALE · 31 DEC 2025</span><h3 style="margin-top:16px">B200 M6 + 5108 chassis</h3><p>The classic B-Series blade model and chassis appear throughout older UCS environments. Cisco’s affected-product notice gives December 31, 2030 as the last support date, subject to coverage.</p>${sourceLink('bladeEol','B200 M6 / 5108 lifecycle notice')}</article><article><span class="badge warn">END OF SALE · 03 FEB 2025</span><h3 style="margin-top:16px">S3260 storage server</h3><p>A storage-focused UCS family with shared drives and server nodes. The notice distinguishes M5 equipment from earlier M4 nodes, whose support ended earlier.</p>${sourceLink('storageEol','S3260 lifecycle notice')}</article></div>
 <article class="lesson" style="margin-top:16px"><h3>M6, M7 and M8 are generations—not interchangeable specifications.</h3><p>M7 rack and modular models remain useful reference points for Intel Xeon Scalable designs. Always keep the complete model name: an M8 CPU, DIMM or drive option is not automatically valid in an M7 or M6 system.</p>${sourceLink('catalog','Browse Cisco’s broader model list')}</article></section><div class="next-lesson"><p>Next: separate the CPU decision from the rest of the server.</p><a class="btn primary" href="#platforms">AMD & Intel →</a></div>`;}
function filteredModels(){const f=state.filters,q=f.q.trim().toLowerCase();return models.filter(m=>(f.family==='All'||m.family===f.family||(f.family==='Rack'&&m.family==='AI'))&&(f.vendor==='All'||m.vendor===f.vendor)&&(f.use==='All'||m.use.includes(f.use))&&(!q||[m.name,m.cpu,m.cpuDetail,m.storage,m.gpu,m.tag,m.family,m.vendor,...m.drive].join(' ').toLowerCase().includes(q)))}
function modelCard(m){return `<article class="model-card"><div class="card-top"><span class="badge ${m.vendor.toLowerCase()}">${m.vendor} CPU</span><span class="small muted">${m.form}</span></div><div class="hardware">${hardware(m.shape)}</div>${physicalCaption(m)}<div class="card-body"><h3>${m.name}</h3>${memoryMetrics(m)}<span class="tag">${m.tag}</span>${m.lifecycle?'<span class="badge warn" style="align-self:start;margin-top:9px">AFFECTED VARIANTS: EOS NOTICE</span>':''}<dl class="spec-mini"><div><dt>CPU</dt><dd>${m.cpu}</dd></div><div><dt>Drives</dt><dd>${m.storage}</dd></div><div><dt>GPU</dt><dd>${m.gpu}</dd></div></dl><div class="card-actions"><button class="btn compact" data-model="${m.id}">Explore model ↗</button><label class="compare-check"><input type="checkbox" data-select-model="${m.id}" ${state.selected.has(m.id)?'checked':''} aria-label="Compare ${m.name}">Compare</label></div></div></article>`;}
function renderModels(){const list=filteredModels();$('#modelCount').textContent=`${list.length} of ${models.length} models · select up to 3 to compare`;$('#modelGrid').innerHTML=list.length?memoryLegend()+list.map(modelCard).join(''):'<div class="empty"><h3>No models match this combination.</h3><p class="muted">Try a broader family or CPU filter.</p><button class="btn" data-reset-filters>Clear filters</button></div>';updateTray();}
function updateTray(){const tray=$('#compareTray');if(!tray)return;tray.hidden=!state.selected.size;$('#compareStatus').textContent=`${state.selected.size}/3 selected · ${[...state.selected].map(id=>models.find(m=>m.id===id).name).join(' + ')}`;$('#compareButton').disabled=state.selected.size<2;}
function openDialog(html){$('#dialogContent').innerHTML=html;$('#modelDialog').showModal();$('#modelDialog [data-close]').focus();}
function showModel(id){const m=models.find(x=>x.id===id);if(!m)return;openDialog(`<div class="dialog-head"><div><span class="badge ${m.vendor.toLowerCase()}">${m.vendor} CPU</span><h2 id="dialogTitle">Cisco UCS ${m.name}</h2><span class="muted">${m.tag}</span></div><button class="icon-btn" data-close aria-label="Close model details">×</button></div><div class="dialog-body">${memoryMetrics(m)}<div class="hardware">${hardware(m.shape)}</div>${physicalDetail(m)}${memoryEvidence(m)}<p class="dialog-intro">${m.job}</p><dl class="dialog-specs"><div><dt>FORM FACTOR</dt><dd>${m.form}</dd></div><div><dt>PROCESSORS</dt><dd>${m.cpu}<br><small class="muted">${m.cpuDetail}</small></dd></div><div><dt>MEMORY</dt><dd>${m.memory}</dd></div><div><dt>LOCAL STORAGE</dt><dd>${m.storage}</dd></div><div><dt>ACCELERATION</dt><dd>${m.gpu}</dd></div><div><dt>MANAGEMENT</dt><dd>${m.management}</dd></div></dl><div class="${m.lifecycle?'warning':'takeaway'}">${m.lifecycle?'':'<span class="symbol">↳</span>'}<div><strong>${m.lifecycle?'Lifecycle snapshot · 7 Oct 2026':'What to notice'}</strong><p class="small" style="margin:7px 0 0">${m.note}</p></div></div><p class="small muted">This guide covers representative options; use the configuration and interoperability documents for a deployable bill of materials.</p><div class="dialog-source">${m.sources.map(s=>`${sourceLink(s)}<span class="muted">${sources[s].loc} · ${sources[s].date}</span>`).join('')}</div></div>`);}
function showCompare(){const list=[...state.selected].map(id=>models.find(m=>m.id===id));if(list.length<2)return;const rows=[['Physical format','form'],['CPU','cpu'],['Processor scope','cpuDetail'],['Memory','memory'],['Drives','storage'],['GPU options','gpu'],['Management','management'],['Important qualification','note']];openDialog(`<div class="dialog-head"><div><div class="eyebrow">SIDE BY SIDE</div><h2 id="dialogTitle">Compare your models</h2></div><button class="icon-btn" data-close aria-label="Close comparison">×</button></div><div class="dialog-body"><p class="small muted">Feature comparison, not a benchmark ranking. “Up to” values are configuration ceilings. Swipe the table sideways on narrow screens.</p><div class="table-scroll"><table><caption class="visually-hidden">Comparison of selected UCS server models</caption><thead><tr><th scope="col">Feature</th>${list.map(m=>`<th scope="col">${m.name}<br><span class="badge ${m.vendor.toLowerCase()}">${m.vendor}</span></th>`).join('')}</tr></thead><tbody>${rows.map(([l,k])=>`<tr><th scope="row">${l}</th>${list.map(m=>`<td>${m[k]}</td>`).join('')}</tr>`).join('')}<tr><th scope="row">Evidence</th>${list.map(m=>`<td>${m.sources.map(s=>sourceLink(s,sources[s].title.replace('Cisco UCS ','').replace(' Data Sheet',''))).join('<br>')}</td>`).join('')}</tr></tbody></table></div></div>`);}
function modelButtons(ids){return `<div class="mini-chips">${ids.map(id=>`<button data-model="${id}">${models.find(m=>m.id===id).name} ↗</button>`).join('')}</div>`;}
function platforms(){return `${intro('03 / TWO CPU ECOSYSTEMS','AMD or Intel? Start with the model.','The processor is one decision. Form factor, memory, accelerators, storage and management are separate decisions—and Cisco qualifies their combinations.')}
 <div class="two-col"><article class="vendor-panel amd"><span class="badge amd">AMD CPU PLATFORMS</span><h2>EPYC</h2><p>Recent UCS general-purpose AMD servers span both rack and modular designs.</p><ul><li><b>C225 M8:</b> one CPU socket in 1U.</li><li><b>C245 M8:</b> up to two sockets in 2U.</li><li><b>X215c M8:</b> up to two sockets in X9508.</li><li><b>C845A M8:</b> two EPYC processors host qualified AMD or NVIDIA GPUs.</li></ul>${modelButtons(['c225','c245','x215','c845'])}<p class="small">C225 / C245 / X215c M8 list qualified 4th- and 5th-generation EPYC processors. C845A M8 uses qualified 5th-generation parts.</p></article>
 <article class="vendor-panel intel"><span class="badge intel">INTEL CPU PLATFORMS</span><h2>Xeon</h2><p>Xeon 6 appears across rack, modular, edge and dedicated AI platforms.</p><ul><li><b>C220 / C240 M8:</b> up to two sockets.</li><li><b>X210c M8:</b> up to two; <b>X410c M8:</b> four.</li><li><b>XE130c / XE150c M8:</b> one Xeon 6 SoC.</li><li><b>C880A M8:</b> two Xeon 6 processors host eight NVIDIA B300 GPUs.</li></ul>${modelButtons(['c220','c240','x210','x410','xe150','c880'])}<p class="small">“Xeon 6” covers multiple processor designs. Use the server’s qualified CPU list; support for one family member does not imply support for every Xeon 6.</p></article></div>
 <div class="takeaway"><span class="symbol">≠</span><div><h3>AMD CPU ≠ AMD GPU. Intel CPU ≠ Intel GPU.</h3><p>For example, X215c M8 can host a qualified NVIDIA GPU expansion configuration, while C845A M8 has documented AMD Instinct options as well. A shared CPU vendor does not make GPU support transferable.</p></div></div>
 <section class="section"><div class="chapter-heading"><h2>A practical platform map</h2><span class="small">Open a model for its sources.</span></div><div class="table-scroll"><table><caption class="visually-hidden">UCS form factors by CPU ecosystem</caption><thead><tr><th scope="col">What you’re looking for</th><th scope="col">AMD CPU examples</th><th scope="col">Intel CPU examples</th></tr></thead><tbody>${[['Compact 1U rack',['c225'],['c220']],['Expandable 2U rack',['c245'],['c240']],['Two-socket modular',['x215'],['x210']],['Four-socket modular',[],['x410']],['Dedicated multi-GPU AI',['c845','c885'],['c880']],['Unified Edge',[],['xe130','xe150']]].map(([label,a,b])=>`<tr><th scope="row">${label}</th><td>${a.length?modelButtons(a):'<span class="support-none">No example in the documented set</span>'}</td><td>${modelButtons(b)}</td></tr>`).join('')}</tbody></table></div><p class="matrix-note">This map is limited to the models in this guide. A blank is not a platform-wide statement that support is impossible. C885A variants have lifecycle notices.</p></section>
 <section class="section two-col"><article class="lesson"><div class="eyebrow">A FAIR COMPARISON</div><h3>Compare a workload, not a logo.</h3><p>Core count alone does not predict application performance. Consider per-core licensing, memory capacity and bandwidth, storage I/O, power, software support and measured workload results.</p><p>For a VM host, memory or licensing may constrain the design before CPU cores do. For an AI server, GPU memory and interconnects can matter more than the host CPU brand.</p></article><article class="lesson"><div class="eyebrow">PLATFORM VS. SOFTWARE</div><h3>What runs on UCS?</h3><p>UCS provides the infrastructure. An operating system, hypervisor or container platform runs the workload. Intersight manages equipment; it is not the hypervisor.</p><p>Check the exact model and release for systems such as VMware ESXi, Windows Server or Linux. Nutanix solutions use their own validated node and software combinations.</p>${sourceLink('hcl','Hardware and software interoperability references')}<br>${sourceLink('nutanix','Nutanix solution documents')}</article></section><div class="next-lesson"><p>Next: decode the drive and accelerator options.</p><a class="btn primary" href="#components">Storage & GPUs →</a></div>`;}
const driveLessons={
 sff:{label:'2.5-inch SFF',art:'',title:'A shape, with several interface choices.',text:'Small-form-factor bays commonly hold 2.5-inch drives. Depending on the server and backplane, these may be SAS, SATA or NVMe. The bay shape alone does not tell you which protocols are supported.',notice:'In C240 M8, the SFF configuration supports up to 28 drives. That ceiling is separate from the E3.S and LFF chassis options.',ids:['c225','c245','c240'],source:'c240'},
 lff:{label:'3.5-inch LFF',art:'lff',title:'Larger bays for capacity-focused storage.',text:'Large-form-factor bays are commonly associated with 3.5-inch hard drives. A drive count is not the same as usable storage capacity: drive size, RAID layout, spares and software all matter.',notice:'C240 M8 has an LFF option with up to 16 large SAS drives and four optional rear SFF drives.',ids:['c240'],source:'c240'},
 e3:{label:'E3.S NVMe',art:'e3',title:'Enterprise flash in a different form factor.',text:'E3.S is an enterprise SSD shape in the EDSFF family. NVMe is the protocol. An E3.S option needs the appropriate chassis or front module; it is not an adapter-free replacement for a 2.5-inch drive.',notice:'Examples: C220 M8 up to 16; C240 M8 up to 36; X210c M8 up to nine. These are different model-specific configurations.',ids:['c220','c240','x210'],source:'x210'},
 e1:{label:'E1.S NVMe',art:'e1',title:'Another enterprise SSD format.',text:'E1.S and E3.S are different physical form factors. Both can carry NVMe SSDs, but one cannot simply be substituted for the other. Cooling, carriers and electrical connections are part of the platform design.',notice:'C845A M8 lists up to 20 E1.S drives; C880A M8 lists up to eight. Both use local flash alongside their GPU subsystem.',ids:['c845','c880'],source:'c845hw'},
 m2:{label:'M.2 boot',art:'m2',title:'Small drives with an important job.',text:'M.2 modules often store the boot operating system separately from the main data drives. M.2 describes a form factor; it does not always mean NVMe. The device and module may use SATA instead.',notice:'Cisco lists model-specific M.2 SATA or NVMe options. Check whether mirroring, hardware RAID or passthrough is supported for the exact boot module.',ids:['c225','x210','xe130'],source:'x210'}
};
function components(){return `${intro('04 / UNDER THE COVER','Decode storage. Understand acceleration.','Drive shape, storage protocol and accelerator type describe different things. Keep them separate and the specification sheets become much easier to read.')}
 <section class="panel"><div class="panel-head"><div><div class="eyebrow">STORAGE EXPLORER</div><h2 style="margin-top:8px">What does the drive label tell you?</h2><p>Select a format to learn where it appears.</p></div><span class="badge accent">FORM ≠ PROTOCOL</span></div><div class="storage-lab"><div class="lab-controls" aria-label="Drive formats">${Object.entries(driveLessons).map(([id,d])=>`<button data-drive="${id}" aria-pressed="${state.drive===id}">${d.label}</button>`).join('')}</div><div class="lab-content" id="driveLesson"></div></div></section>
 <div class="two-col section"><article class="lesson"><h3>The controller is part of the story.</h3><p>A RAID controller can organize drives into arrays. A host bus adapter or passthrough configuration gives software more direct access to individual drives. The backplane supplies the physical and electrical connections to the bays.</p><p>A server listing SAS, SATA and NVMe does not mean every bay supports all three simultaneously. Boot storage and data storage can follow different rules.</p>${sourceLink('c240','See C240 M8 backplane and controller options')}</article><article class="lesson"><h3>Memory is not storage.</h3><p><b>System RAM:</b> the CPU’s active working space.<br><b>GPU memory:</b> the accelerator’s working space.<br><b>Drives:</b> persistent storage for software, datasets and files.</p><p>Adding SSDs does not increase GPU memory. Adding CPU DIMMs does not turn an undersized GPU into a larger one.</p><a href="#sources/glossary">Open the terminology guide →</a></article></div>
 <section class="section"><div class="chapter-heading"><h2>Three ways GPUs show up in UCS</h2><span class="small">Each has its own platform rules.</span></div><div class="three-col"><article class="lesson"><div class="big-number">01</div><h3>Add-in PCIe cards</h3><p>GPU cards installed in a rack server. Small inference cards and large accelerators differ in height, width, power and cooling needs.</p><div class="chip-row"><span class="badge">C220 / C225</span><span class="badge">C240 / C245</span><span class="badge">C845A</span></div><p class="small" style="margin-top:16px">C845A M8 supports qualified AMD Instinct MI210 / MI350P or NVIDIA PCIe configurations.</p>${sourceLink('c845','C845A GPU options')}</article><article class="lesson"><div class="big-number">02</div><h3>Modular expansion</h3><p>An X-Series compute node connects to an additional PCIe node through X-Fabric. The expansion node holds the GPUs; the compute node still runs the host software.</p><div class="chip-row"><span class="badge">X440p</span><span class="badge">X580p</span></div><p class="small" style="margin-top:16px">X580p pairs with X210c M8 or X215c M8 and requires X9516 modules. Cisco’s data sheet has inconsistent chassis-wide GPU totals; this guide uses its per-node options only.</p>${sourceLink('x580','X580p requirements')}</article><article class="lesson"><div class="big-number">03</div><h3>Integrated GPU systems</h3><p>Dense systems use purpose-built GPU baseboards and high-speed accelerator connections. SXM and OAM modules are different from PCIe cards.</p><div class="chip-row"><span class="badge">C880A</span><span class="badge warn">C885A · lifecycle</span></div><p class="small" style="margin-top:16px">C880A M8 combines Intel host CPUs with eight NVIDIA HGX B300 GPUs.</p>${sourceLink('c880','C880A platform')}</article></div></section>
 <section class="panel section"><div class="panel-head"><div><div class="eyebrow">THE CPU / GPU CROSSOVER</div><h2 style="margin-top:8px">Documented examples, not universal pairings</h2></div></div><div class="table-scroll" style="border:0;border-radius:0"><table><caption class="visually-hidden">Example CPU and GPU vendor combinations</caption><thead><tr><th scope="col">Host CPU</th><th scope="col">GPU</th><th scope="col">Example</th><th scope="col">What to remember</th></tr></thead><tbody><tr><th scope="row">AMD EPYC</th><td>NVIDIA</td><td>${modelButtons(['c245','c845','x215'])}</td><td>A supported AMD server can use NVIDIA accelerators.</td></tr><tr><th scope="row">AMD EPYC</th><td>AMD Instinct</td><td>${modelButtons(['c845'])}</td><td>MI210 / MI350P are listed for C845A M8. That does not establish support on C245 or X215c.</td></tr><tr><th scope="row">Intel Xeon</th><td>NVIDIA</td><td>${modelButtons(['c240','c880','xe150'])}</td><td>PCIe RTX PRO, HGX B300 and edge GPU options are different designs.</td></tr><tr><th scope="row">Intel Xeon</th><td>Intel Data Center GPU Flex</td><td>X-Series + X440p<br>${sourceLink('x440','Qualified expansion platform')}</td><td>The X440p data sheet lists Flex 140 / 170 and host-node pairings including X210c M7. Do not transfer this to X580p.</td></tr><tr><th scope="row">Intel Xeon</th><td>AMD Instinct</td><td class="support-none">No example established here</td><td>Do not infer support or a blanket prohibition from CPU vendor alone.</td></tr></tbody></table></div></section>
 <div class="warning"><strong>Intel GPU references need care, too.</strong> The C220 M8 installation guide mentions Flex 140 in a firmware table, while its explicit GPU population rules list NVIDIA L4. The clearer Intel GPU example is X440p: its specification table lists Intel Data Center GPU Flex 140 and Flex 170. Use a qualified host-node pairing and current release documentation. ${sourceLink('x440','X440p GPU table')} · ${sourceLink('c220gpu','C220 source distinction')}</div>
 <section class="section"><h2>From an interesting option to a supported system</h2><p class="muted">Use this order when you move from learning to configuring.</p><div class="compat-steps"><article class="compat-step"><h3>Exact hardware</h3><p>Full model, chassis variant and CPU part number.</p></article><article class="compat-step"><h3>Population rules</h3><p>DIMMs, risers, drives, GPU kits, power and cooling.</p></article><article class="compat-step"><h3>Software stack</h3><p>Firmware, drivers, operating system and hypervisor releases.</p></article><article class="compat-step"><h3>Validated design</h3><p>Solution-level rules for AI, HCI, clustering and management.</p></article></div><p class="source-note">Start with ${sourceLink('hcl','Cisco’s interoperability references')} and the model’s specification sheet.</p></section><div class="next-lesson"><p>Ready to connect the dots?</p><a class="btn primary" href="#quiz">Test your knowledge →</a></div>`;}
function renderDrive(){const d=driveLessons[state.drive];$('#driveLesson').innerHTML=`<div class="drive-art" aria-hidden="true"><div class="drive-block ${d.art}"></div><div class="drive-block ${d.art}" style="opacity:.45"></div></div><h3>${d.title}</h3><p>${d.text}</p><p><b class="muted">In UCS:</b> ${d.notice}</p>${modelButtons(d.ids)}${cite(d.source)}`;$$('[data-drive]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.drive===state.drive)));}
function quizView(){return `${intro('05 / MAKE IT STICK','A few questions. Better instincts.','Eight short checks on the ideas that matter. Choose an answer to see the reasoning and its source. You can revisit earlier questions.')}<section class="question" id="quizBody" aria-live="polite"></section>`;}
function renderQuiz(){const i=state.quizIndex,correct=state.answers.filter((a,i)=>a===quiz[i].answer).length;if(i>=quiz.length){const missed=quiz.filter((q,j)=>state.answers[j]!==q.answer);$('#quizBody').innerHTML=`<div class="eyebrow">KNOWLEDGE CHECK COMPLETE</div><div class="score">${correct}<span class="muted" style="font-size:35px"> / ${quiz.length}</span></div><h2>${correct===8?'You’ve got the core ideas.':'The useful part is what you learned.'}</h2><p class="muted">${correct===8?'You can distinguish the hardware families, CPU and GPU choices, drive formats and management layers.':'Revisit the explanations below, then try again when you’re ready.'}</p>${missed.map(q=>`<div class="feedback"><strong>${q.q}</strong><p>${q.why}</p>${cite(q.src)}</div>`).join('')}<div class="button-row"><button class="btn primary" data-restart-quiz>Try again ↻</button><a class="btn ghost" href="#lineup">Explore models →</a></div>`;return;}
 const q=quiz[i],a=state.answers[i],done=a!==null;$('#quizBody').innerHTML=`<div class="quiz-progress" role="progressbar" aria-label="Questions answered" aria-valuemin="0" aria-valuemax="${quiz.length}" aria-valuenow="${state.answers.filter(x=>x!==null).length}"><i style="width:${state.answers.filter(x=>x!==null).length/quiz.length*100}%"></i></div><div class="eyebrow">QUESTION ${i+1} OF ${quiz.length}</div><h2>${q.q}</h2>${q.options.map((o,j)=>`<button class="option ${done&&j===q.answer?'correct':done&&j===a?'wrong':''}" data-answer="${j}" ${done?'disabled':''}><span class="letter">${String.fromCharCode(65+j)}</span><span>${o}${done&&j===q.answer?' ✓':''}${done&&j===a&&a!==q.answer?' · Your answer':''}</span></button>`).join('')}${done?`<div class="feedback"><strong>${a===q.answer?'Exactly.':'Here’s the distinction.'}</strong><p>${q.why}</p>${cite(q.src)}</div>`:''}<div class="quiz-bottom"><button class="btn ghost" data-quiz-prev ${i===0?'disabled':''}>← Previous</button><span>${correct} correct so far</span><button class="btn primary" data-quiz-next ${!done?'disabled':''}>${i===quiz.length-1?'See results':'Next question'} →</button></div>`;}
function sourcesView(){return `${intro('06 / KEEP LEARNING','Go straight to the evidence.','The guide is a snapshot checked on October 7, 2026. Hardware illustrations are original schematics, and model summaries are paraphrased from Cisco’s official documentation.')}
 <div class="two-col"><article class="lesson"><h3>What this guide covers</h3><p>Representative M8 rack, modular, edge and AI servers; X-Series architecture; drive and GPU concepts; and lifecycle context for classic families.</p><p>It is an educational map, not an exhaustive catalog, ordering tool or validated compatibility matrix. Sources can change after the review date.</p></article><article class="lesson"><h3>How source differences were handled</h3><p>Model documents take priority over broad comparison pages for hardware details. Lifecycle notices apply to their listed part numbers.</p><p>The C220 M8 overview sources disagree on maximum RAM, so this guide shows DIMM slots instead. X580p’s chassis-wide GPU totals are inconsistent in its data sheet, so no aggregate maximum is inferred here.</p></article></div>
 <section class="section" id="glossary"><div class="eyebrow">PLAIN-ENGLISH REFERENCE</div><h2 style="margin-top:10px">Keep the acronyms under control.</h2><label class="visually-hidden" for="glossarySearch">Search glossary</label><input class="glossary-search" id="glossarySearch" type="search" placeholder="Find a term: NVMe, FI, socket…"><div class="glossary" id="glossaryList">${Object.entries(glossary).map(([term,def])=>`<details data-term="${esc((term+' '+def).toLowerCase())}"><summary>${esc(term)}</summary><p>${def}</p></details>`).join('')}</div><p id="glossaryEmpty" class="muted" hidden>No matching terms. Try a shorter search.</p></section>
 <section class="section"><div class="eyebrow">OFFICIAL SOURCE LIBRARY</div><h2 style="margin-top:10px">Follow the document behind the detail.</h2><p class="muted small">Dates below are Cisco’s displayed revision dates where available. “Reviewed” is this guide’s access date. No source documents were supplied by the user.</p><div class="source-list">${Object.entries(sources).map(([id,s])=>`<article class="source-item" id="source-${id}">${sourceLink(id)}<p>${s.scope}</p><small>${s.date} · ${s.loc}</small></article>`).join('')}</div></section>`;}
const views={lineup,platforms,components,quiz:quizView,sources:sourcesView};
function afterRender(page,sub){$('#diagramTip').hidden=true;if(innerWidth<=850)$('#nav .active').scrollIntoView({block:'nearest',inline:'center'});if(page==='lineup')renderModels();if(page==='components')renderDrive();if(page==='quiz')renderQuiz();if(sub){const target=document.getElementById(sub);if(target)setTimeout(()=>target.scrollIntoView(),30);}}
let toastTimer;
function toast(msg){$('#toast').textContent=msg;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.model)showModel(b.dataset.model);if(b.hasAttribute('data-close'))$('#modelDialog').close();if(b.hasAttribute('data-compare'))showCompare();if(b.hasAttribute('data-clear-compare')){state.selected.clear();renderModels();}if(b.hasAttribute('data-reset-filters')){state.filters={q:'',family:'All',vendor:'All',use:'All'};render();}if(b.dataset.drive){state.drive=b.dataset.drive;renderDrive();}if(b.dataset.answer!==undefined){state.answers[state.quizIndex]=Number(b.dataset.answer);renderQuiz();}if(b.hasAttribute('data-quiz-next')){state.quizIndex++;renderQuiz();$('#quizBody').scrollIntoView({block:'start'});}if(b.hasAttribute('data-quiz-prev')){state.quizIndex--;renderQuiz();}if(b.hasAttribute('data-restart-quiz')){state.quizIndex=0;state.answers.fill(null);renderQuiz();}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.selectModel){const id=el.dataset.selectModel;if(el.checked&&state.selected.size>=3){el.checked=false;toast('Compare up to three models. Uncheck one to add another.');return;}el.checked?state.selected.add(id):state.selected.delete(id);updateTray();}const key={familyFilter:'family',vendorFilter:'vendor',useFilter:'use'}[el.id];if(key){state.filters[key]=el.value;renderModels();}});
document.addEventListener('input',e=>{if(e.target.id==='modelSearch'){state.filters.q=e.target.value;renderModels();}if(e.target.id==='glossarySearch'){const q=e.target.value.toLowerCase().trim();const items=$$('[data-term]');items.forEach(d=>d.hidden=!d.dataset.term.includes(q));$('#glossaryEmpty').hidden=items.some(d=>!d.hidden);}});
$('#modelDialog').addEventListener('click',e=>{if(e.target===$('#modelDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
render();
