// BEGIN hardware
function hardware(shape='rack2',hero=false){
 const uid='dell-art-'+(++artSerial),metal=`url(#${uid}-metal)`,mesh=`url(#${uid}-mesh)`,grid=`url(#${uid}-grid)`;
 const r=(x,y,w,h,fill='#252f36',stroke='#849199',rad=1)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rad}" fill="${fill}" stroke="${stroke}" stroke-width=".65"/>`;
 const vent=(x,y,w,h)=>r(x,y,w,h,mesh,'#65737d');
 const badge=(x,y,size=8)=>`<circle cx="${x}" cy="${y}" r="${size}" fill="#10171e" stroke="#b3c2ce" stroke-width=".5"/><text x="${x}" y="${y+size*.3}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${size*.64}" font-weight="700" font-style="italic" fill="#e5edf4">DELL</text>`;
 const drive=(x,y,w,h,vertical=true)=>{const px=Math.min(1.5,w*.18),py=Math.min(2,h*.18),iw=w-2*px;return r(x,y,w,h,'#172027','#707c84')+vent(x+px,y+py,iw,h-2*py)+r(x+px,y+py,Math.min(5,iw),Math.min(2,h*.18),'#ba7334','#c99864',.3)+`<path d="M${x+px} ${y+h-py}h${iw}" stroke="#8fa0aa" stroke-width="${Math.min(1.2,w*.22)}"/>`;};
 const bank=(x,y,w,h,cols,rows=1)=>{let b='';for(let j=0;j<rows;j++)for(let i=0;i<cols;i++)b+=drive(x+i*w/cols,y+j*h/rows,w/cols-1,h/rows-1);return b;};
 const ears=(x,y,w,h)=>r(x,y,12,h,metal,'#adb7bf',2)+r(x+w-12,y,12,h,metal,'#adb7bf',2)+`<path d="M${x+5} ${y+5}v${Math.max(8,h-10)}M${x+w-7} ${y+5}v${Math.max(8,h-10)}" stroke="#61717d" stroke-width="2"/><path d="M${x+w-11} ${y+3}v${Math.min(18,h-6)}" stroke="#139bca" stroke-width="1.5"/>`;
 const shell=(x,y,w,h,ear=true,depth=24)=>`<path d="M${x} ${y}l${depth} -18h${w+9-depth}l-9 18z" fill="${metal}" stroke="#aab8c2" stroke-width=".7"/><path d="M${x+w} ${y}l9 -18v${h}l-9 18z" fill="#6c7b88" stroke="#a1afb8" stroke-width=".5"/>`+r(x,y,w,h,'#9daab4','#c0ccd5',2)+(ear?ears(x,y,w,h):'');
 const ports=(x,y,n=4,w=9)=>Array.from({length:n},(_,i)=>r(x+i*(w+3),y,w,4,'#07111a','#a5b3bd')).join('');
 const slots=(x,y,w,h,n,vertical=false)=>{let b='';for(let i=0;i<n;i++){let xx=x+(vertical?i*w/n:0),yy=y+(vertical?0:i*h/n),ww=vertical?w/n-2:w,hh=vertical?h:h/n-2;b+=r(xx,yy,ww,hh,metal,'#b5bfc6')+vent(xx+2,yy+2,ww-4,hh-4);}return b;};
 const bezel=(x,y,w,h,blue=false)=>{let b=r(x,y,w,h,mesh,'#8b99a4');const rx=Math.min(21,w/12),ry=Math.min(rx*.866,h*.49),step=rx*1.5;for(let col=-1;col<=Math.ceil(w/step);col++)for(let row=-1;row<=Math.ceil(h/(ry*2));row++){let cx=x+rx+col*step,cy=y+ry+row*ry*2+(col%2?ry:0);let pts=Array.from({length:6},(_,k)=>`${cx+Math.cos(k*Math.PI/3)*rx},${cy+Math.sin(k*Math.PI/3)*ry/.866}`).join(' ');b+=`<polygon points="${pts}" fill="none" stroke="${blue?'#325b7d':'#c0cbd3'}" stroke-width="${blue?.8:1.5}"/>`;}return `<g clip-path="url(#${uid}-bezel-${Math.round(x)}-${Math.round(y)})"><defs><clipPath id="${uid}-bezel-${Math.round(x)}-${Math.round(y)}"><rect x="${x}" y="${y}" width="${w}" height="${h}"/></clipPath></defs>${b}</g>`+badge(x+w*.51,y+h*.5,Math.min(9,h*.24));};
 const rack=(x,y,w,h,layout='bezel')=>{let b=shell(x,y,w,h),ix=x+16,iw=w-32;
 if(layout==='coldaisle'){b+=slots(ix,y+3,iw*.24,h-6,2)+bank(ix+iw*.26,y+3,iw*.41,h-6,2,4)+slots(ix+iw*.69,y+3,iw*.21,h*.55,1)+ports(ix+iw*.7,y+h*.73,3,6)+r(ix+iw*.93,y+3,iw*.055,h-6,'#263640','#8e9fa9');}
 else if(layout==='sff16'){b+=bank(ix,y+4,iw*.31,h-8,8)+r(ix+iw*.325,y+4,iw*.35,h-8,grid,'#4e5f6b')+bank(ix+iw*.69,y+4,iw*.31,h-8,8);}
 else b+=bezel(ix,y+3,iw,h-6);
 return b;
 };
 const mxFront=(x,y,w,h)=>r(x,y,w,h,'#17252f','#82939f')+r(x+1,y+2,w-2,5,'#273b46','#4e6878')+ports(x+2,y+3,1,7)+r(x+2,y+9,w-4,h*.22,grid,'#607582')+bank(x+2,y+h*.31,w-4,h*.57,4,2)+vent(x+2,y+h*.9,w-4,h*.07)+`<path d="M${x+1} ${y+12}v${h*.15}" stroke="#2797d4" stroke-width="2"/>`;
 const map={rack1:'r6715',rack2:'r7725',blade:'mx760',tower:'t560',edgesled:'xr8720',edge:'xr8720',gpu4:'xe7745',gpu6:'xe9680',gpu10:'xe9785',liquid:'xe9785l'};
 const model=shape.startsWith('physical-')?shape.slice(9):(map[shape]||shape);
 let b='',label='Dell reference-based exterior schematic';
 if(model==='portfolio'){b=rack(43,42,272,25)+rack(27,100,302,55)+rack(16,175,322,58,'sff16');label='PowerEdge portfolio with representative silver security bezels and a sixteen-SFF 2U front';}
 else if(model==='frame'){b=r(60,8,239,167,metal,'#adb9c2',3)+r(68,14,223,153,'#18252e','#7d8b98');for(let i=0;i<8;i++){const x=i<4?73+i*23:194+(i-4)*23;b+=mxFront(x,18,21,119);}for(let i=0;i<4;i++)b+=vent(168,19+i*29.5,23,27)+`<path d="M172 ${23+i*29.5}h6v18" stroke="#d49450" fill="none"/>`;for(let i=0;i<6;i++)b+=vent(73+i*35.3,143,33,21)+`<path d="M${77+i*35.3} 158h21" stroke="#aabac7" stroke-width="2"/>`;label='MX7000 front: eight vertical sled bays, four central fans and six bottom power supplies';}
 else if(model==='mx760'){b=`<path d="M115 14h29l93 22v130l-93 15h-29z" fill="${metal}" stroke="#a5b5c2"/><path d="M151 30l77 18v100l-77 12z" fill="#b2bdc6" stroke="#6f8290"/>`+mxFront(115,14,29,167);b+=r(181,62,29,52,'#8f9eaa','#7a8c98');label='MX760c full-height single-width compute sled: narrow vertical face with eight E3.S drives in two groups of four, long insertion chassis';}
 else if(model==='t560'){
  // Stabilizers are shaded solid parts beneath the side panel, not decals on it.
  b=`<path d="M177 23l90-14v155l-90 14z" fill="${metal}" stroke="#92a4b4" stroke-width=".7"/><path d="M112 23l90-14h65l-90 14z" fill="#c3cdd5" stroke="#aab9c5" stroke-width=".7"/>`+r(112,23,65,155,'#101c28','#71899c',3)+bezel(118,30,53,142,true)+r(134,29,20,5,'#203244','#385469')+`<path d="M218 86l11-2v10l-11 2z" fill="#566873" stroke="#85959f" stroke-width=".6"/>`;label='PowerEdge T560 tower with blue-black geometric security bezel, tall narrow face, silver side and a clean chassis base';
 }
 else if(model==='xr8720'){b=shell(79,77,190,65,false,58)+slots(84,81,169,36,2)+slots(137,120,103,17,1)+r(84,120,45,17,'#aab7c2','#788c9a')+ports(89,123,2,8)+r(87,129,8,6,'#0b1822','#899fac')+ports(109,130,2,6)+r(253,81,10,17,'#a9b8c4','#66869f')+r(253,103,10,17,'#a9b8c4','#66869f');label='XR8720t half-width 2U compute sled, front PCIe and network interfaces; requires the separate XR8000r enclosure, which is not shown';}
 else if(model==='xe7740'||model==='xe7745'){b=rack(21,45,310,113);label=`${model.toUpperCase()} 4U front with full-height silver geometric security bezel fitted; internal GPUs are not drawn as front fans`;}
 else if(model==='xe9680'){const x=47,y=31,w=258,h=144,ix=x+15,iw=w-30;b=shell(x,y,w,h)+bezel(ix,y+4,iw,43)+r(ix,y+52,iw,84,grid,'#4b5d6c');for(let i=0;i<4;i++)b+=slots(ix+9+i*52,y+56,25,45,2,true);b+=slots(ix+1,y+111,9,21,1)+slots(ix+iw-10,y+111,9,21,1);label='XE9680 six-U chassis: upper compute/storage security bezel and broad lower accelerator/network I/O zone';}
 else if(model==='xe9780'||model==='xe9785'){const x=92,y=24,w=174,h=159,ix=x+10,iw=w-20;b=shell(x,y,w,h)+r(ix,y+3,iw,48,grid,'#d0d7dd')+vent(ix,y+54,iw,12)+ports(ix+6,y+70,4,7)+ports(ix+iw-28,y+70,2,7)+bezel(ix,y+81,iw,28)+vent(ix,y+113,iw,40);b+=slots(ix+4,y+116,27,34,3,true)+slots(ix+61,y+116,36,34,4,true)+slots(ix+126,y+116,23,34,3,true);label=`${model.toUpperCase()} ten-U enclosure: large upper air grille, service strip, central compute bezel and lower I/O section`;}
 else if(model==='xe9785l'){const x=18,y=61,w=321,h=83,ix=x+11,iw=w-22;b=shell(x,y,w,h,false,37)+slots(ix,y+6,iw*.24,(h-14)/2,4,true)+slots(ix,y+h*.52,iw*.24,(h-14)/2,4,true)+bank(ix+iw*.285,y+10,iw*.18,h-25,4)+bank(ix+iw*.535,y+10,iw*.18,h-25,4)+slots(ix+iw*.76,y+6,iw*.24,(h-14)/2,4,true)+slots(ix+iw*.76,y+h*.52,iw*.24,(h-14)/2,4,true)+ports(ix+iw*.285,y+h-12,3,7)+ports(ix+iw*.54,y+h-12,3,7)+r(x-4,y+h*.55,8,17,metal,'#a7b6c3')+r(x+w-4,y+h*.55,8,17,metal,'#a7b6c3');label='XE9785L 3-OU liquid-cooled ORv3 node: central two banks of four U.2 bays, PCIe I/O on both sides; liquid couplings at rear';}
 else{const one=['r470','r670','r6715','r6725'].includes(model),h=one?29:58,layout=model==='r670'?'coldaisle':model==='r770'?'sff16':'bezel';b=rack(15,(195-h)/2,322,h,layout);label=`PowerEdge ${model.toUpperCase()} ${one?'1U':'2U'} front; ${layout==='coldaisle'?'official gallery cold-aisle I/O and central E3.S layout':layout==='sff16'?'sixteen-SFF layout in two eight-drive banks with center airflow panel':'optional silver geometric security bezel fitted; bay layout hidden'}`;}
 return `<svg viewBox="0 0 360 ${model==='portfolio'?248:195}" role="img" aria-label="${label}"><defs><linearGradient id="${uid}-metal" x2=".3" y2="1"><stop stop-color="#d4dce4"/><stop offset=".48" stop-color="#9fadb9"/><stop offset="1" stop-color="#637488"/></linearGradient><pattern id="${uid}-mesh" width="3" height="3" patternUnits="userSpaceOnUse"><rect width="3" height="3" fill="#34434f"/><circle cx="1.5" cy="1.5" r="1.05" fill="#08121b"/></pattern><pattern id="${uid}-grid" width="4" height="4" patternUnits="userSpaceOnUse"><rect width="4" height="4" fill="#17242e"/><path d="M0 0h4v4" stroke="#768a9b" stroke-width=".5"/></pattern></defs>${b}</svg>`;
}
// END hardware
// BEGIN architecture
function architecture(){
 let svg='<defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".65" fill="#466581" opacity=".45"/></pattern></defs><rect width="1000" height="540" fill="#0a1628"/><rect width="1000" height="540" fill="url(#grid)"/>';
 const box=(x,y,w,h,label)=>`<rect class="enclosure" x="${x}" y="${y}" width="${w}" height="${h}" rx="12"/><text class="tiny" x="${x+20}" y="${y+25}">${label}</text>`;
 if(state.mode==='rack'){
  svg+=box(75,168,825,328,'POWEREDGE R770 · 2U CHASSIS · COMPONENT GROUPS');
  svg+='<path class="trace management" d="M227 113V161H217v51"/><path class="trace" d="M745 108v104M745 264v27H574v22M270 340h42M637 340h40M370 367v33h-53v28M574 367v33h138v28M429 340h83"/>';
  svg+=node('ome',75,49,303,64,'OpenManage Enterprise','Fleet operations');svg+=node('network',590,49,310,59,'External Ethernet network','Workload traffic');
  svg+=node('idrac',112,212,210,52,'iDRAC10','Embedded management');svg+=node('nic',640,212,210,52,'NIC / OCP adapter','Network I/O');
  svg+=node('ram',126,313,144,54,'DDR5 DIMMs','CPU 1 memory');svg+=node('cpu',312,313,117,54,'CPU 1','Intel Xeon 6');svg+=node('cpu',512,313,125,54,'CPU 2','Optional socket');svg+=node('ram',677,313,173,54,'DDR5 DIMMs','CPU 2 memory');
  svg+=node('drives',112,428,410,45,'Front drive bays','SFF / E3.S configurations');svg+=node('pcie',573,428,277,45,'PCIe expansion','Qualified GPUs & adapters');
  svg+='<text class="tiny" x="75" y="523">LOGICAL COMPONENT GROUPS · COUNTS AND ROUTING SIMPLIFIED</text>';
 }else if(state.mode==='mx'){
  svg+=node('network',601,36,300,58,'External network / storage','Workload connections');
  svg+=box(75,132,850,372,'POWEREDGE MX7000 · 7U · FRONT AND REAR EXPANDED');
  svg+=node('frame',820,142,82,28,'','',{content:'<text x="861" y="161" text-anchor="middle" class="sublabel">Inspect</text>'});
  svg+='<text class="tiny" x="110" y="199">FRONT · EIGHT SINGLE-WIDTH BAYS</text><text class="tiny" x="586" y="199">REAR · I/O AND MANAGEMENT</text>';
  svg+='<path class="trace" d="M751 94v25H664v111M751 119h80v111M454 294h99v-11h33M553 294h279v-11"/><path class="trace management" d="M459 373h72v21h210v-9"/>';
  for(let i=0;i<8;i++){const x=111+i*44;svg+=node('blade',x,227,39,180,'','',{aria:'MX compute sled '+(i+1),content:`<text x="${x+19.5}" y="252" text-anchor="middle" class="sublabel">${String(i+1).padStart(2,'0')}</text><path d="M${x+7} 265h25v22h-25zM${x+7} 294h25v22h-25zM${x+7} 323h25v22h-25zM${x+8} 380h23" fill="#0c1827" stroke="#789db8"/><circle cx="${x+12}" cy="368" r="2" fill="#55b4f5"/>`});}
  svg+=node('iom',586,230,156,53,'Fabric I/O A1','Workload link');svg+=node('iom',757,230,144,53,'Fabric I/O A2','Redundant peer');
  svg+=node('omem',586,330,315,55,'MX9002m management','OME-Modular · up to two modules');
  svg+=node('shared',110,451,790,30,'','',{content:'<text x="505" y="471" text-anchor="middle" class="sublabel">SHARED POWER & COOLING · SIX FRONT PSUs · FRONT AND REAR FANS</text>'});
  svg+='<text class="tiny" x="75" y="527">TWO OF SIX I/O BAYS SHOWN · LINES REPRESENT GROUPED CONNECTIONS</text>';
 }else{
  svg+=node('network',586,31,314,56,'Cluster network / storage','Connect to other systems');
  svg+=box(75,132,825,368,'POWEREDGE XE9680 · 6U AIR-COOLED PLATFORM · LOGICAL CUTAWAY');
  svg+='<path class="trace" d="M743 87v111M585 227H417M720 254v37M264 254v20H96v186h14"/>';
  svg+=node('host',110,198,307,56,'2 × Intel Xeon + DDR5','Host processors and system RAM');svg+=node('aiio',585,198,270,56,'High-speed adapters','Network / accelerator I/O');
  svg+='<rect x="109" y="291" width="747" height="123" rx="9" fill="#10203b" stroke="#477aaa" stroke-dasharray="5 4"/>';
  for(let i=0;i<8;i++)svg+=node('gpu',122+i*91,311,80,76,'','',{aria:'Accelerator '+(i+1)+' in the eight-device subsystem',content:`<text x="${162+i*91}" y="341" text-anchor="middle" class="label">ACC ${i+1}</text><text x="${162+i*91}" y="364" text-anchor="middle" class="sublabel">+ HBM</text>`});
  svg+=node('aistorage',110,439,307,42,'Local NVMe + M.2 boot');svg+=node('cooling',459,439,396,42,'Air cooling matched to the configuration');
  svg+='<text class="tiny" x="75" y="523">NVIDIA / AMD / INTEL: SEPARATE BUILDS · INTERNAL ACCELERATOR LINKS NOT DRAWN</text>';
 }
 $('#diagramMount').innerHTML=`<svg class="diagram" viewBox="0 0 1000 540" role="group" aria-label="Interactive Dell ${state.mode} architecture schematic">${svg}</svg>`;
 const blurbs={rack:'<b>A self-contained server:</b> host CPUs, RAM, drives and adapters share one enclosure. iDRAC manages the server; OpenManage Enterprise adds a fleet view. Lines show functional connections, not a motherboard wiring map.',mx:'<b>A shared enclosure:</b> eight vertical bays hold independent sleds at the front. Fabric I/O and management modules occupy the rear. The views are expanded side by side; a management link is different from a workload link.',ai:'<b>A dedicated eight-accelerator platform:</b> XE9680 uses Intel host CPUs with separate NVIDIA, AMD or Intel accelerator builds. The boxes represent one qualified ecosystem, with local HBM per accelerator. Exact internal interconnect topology varies.'};
 $('#diagramBlurb').innerHTML=blurbs[state.mode];$$('#modeSwitch button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode)));
 const ids=$$('[data-concept]',$('#diagramMount')).map(n=>n.dataset.concept);if(!ids.includes(state.concept))state.concept={rack:'cpu',mx:'frame',ai:'gpu'}[state.mode];setConcept(state.concept);
}
// END architecture
// BEGIN overview
function overview(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">AN INTERACTIVE GUIDE TO DELL POWEREDGE</div><h1>Meet the servers.<br><em>Know the possibilities.</em></h1><p>From a single-socket workhorse to a rack built for AI. Learn the PowerEdge families, see how the pieces fit, and find your way through AMD, Intel and GPU options.</p><div class="button-row"><a class="btn primary" href="#lineup">Explore the servers <span>↗</span></a><button class="btn ghost" data-scroll="systemMap">Take the system tour <span>↓</span></button></div><div class="source-note">Based on ${sourceLink('catalog','Dell PowerEdge documentation')} and ${sourceLink('portfolio','the 17G portfolio guide')}.<br>Selected 16G / 17G platforms · reviewed 09 Oct 2026.</div></div><div class="hero-art"><div class="hero-stack">${hardware('portfolio',true)}</div><div class="art-label">POWEREDGE · ILLUSTRATIVE FRONT VIEWS</div></div></section>
 <div class="chapter-heading"><h2>Start with the shape of the system</h2><span class="small">Six ways to understand the offering.</span></div><section class="family-grid dell-families" aria-label="Dell hardware families">
 ${[['Rack','01 / EVERYDAY INFRASTRUCTURE','rack2','PowerEdge R','Self-contained rack servers for compute, virtualization, data and expansion.','Intel Xeon + AMD EPYC'],['Modular','02 / SHARED INFRASTRUCTURE','frame','PowerEdge MX','Independent compute sleds share a chassis, power, cooling and fabric modules.','MX760c + MX7000'],['Tower','03 / BUSINESS & BRANCH','tower','PowerEdge T','Expandable tower servers for offices, local applications and growing businesses.','Intel Xeon in T560'],['Edge','04 / BEYOND THE DATA CENTER','edge','PowerEdge XR','Purpose-built edge platforms; XR8720t is a half-width compute sled requiring an XR8000r chassis.','Xeon 6 SoC in XR8720t'],['AI','05 / PCIe ACCELERATION','gpu4','PowerEdge XE774x','GPU-focused rack servers with multiple qualified plug-in accelerator cards.','Intel or AMD host CPUs'],['AI','06 / INTEGRATED AI SYSTEMS','gpu6','PowerEdge XE9xxx','Dense accelerator subsystems with model-specific interconnects and cooling.','NVIDIA · AMD · Intel options']].map(([family,num,shape,title,desc,chip])=>`<button class="family-card" data-family="${family}"><span class="over">${num}</span><span class="arrow">↗</span><div class="hardware">${hardware(shape)}</div><h3>${title}</h3><p>${desc}</p><div class="chip-row"><span class="badge">${chip}</span></div></button>`).join('')}</section>
 <section class="two-col section"><article class="lesson"><div class="eyebrow">READ THE NAME</div><h3 style="margin-top:12px">Dell PowerEdge R7725</h3><div class="name-decoder"><div class="name-piece">R<small>Rack family</small></div><div class="name-piece">77<small>Model / 17G era</small></div><div class="name-piece">25<small>2-socket AMD here</small></div></div><p>In this AMD set, R6715 / R7715 are single-socket and R6725 / R7725 are dual-socket. The R6 models here are 1U; the R7 models are 2U. Keep the complete model name when checking specifications.</p><p class="small muted">This is a guide to these models, not a universal decoder for every historical Dell name.</p>${sourceLink('rack','Compare the complete model names')}</article><article class="lesson"><div class="eyebrow">THREE DIFFERENT GENERATIONS</div><h3 style="margin-top:12px">Server. Processor. Management.</h3><p><b>17G</b> identifies the PowerEdge platform generation. <b>Xeon 6</b> or <b>EPYC 9005</b> identifies the CPU family. <b>iDRAC10</b> identifies the embedded management generation.</p><p>They are related choices, not equivalent numbers. A 17G server does not have seventeen cores. A 1U server is not necessarily single-socket.</p>${sourceLink('portfolio','Dell’s 17G platform overview')}</article></section>
 <section class="panel section" id="systemMap"><div class="panel-head"><div><div class="eyebrow">THE SYSTEM, CONNECTED</div><h2 style="margin-top:8px">Open up three different designs.</h2><p>Choose a system, then select a component to learn its role.</p></div><div class="segmented" id="modeSwitch" aria-label="Dell system mode"><button data-mode="rack" aria-pressed="true">PowerEdge rack</button><button data-mode="mx" aria-pressed="false">MX modular</button><button data-mode="ai" aria-pressed="false">XE AI system</button></div></div><div id="diagramBlurb" class="diagram-notes"></div><div class="diagram-scroll" id="diagramMount"></div><div class="diagram-legend"><div class="legend-items"><span><i class="legend-dot"></i>System / data connection</span><span><i class="legend-dot" style="background:var(--purple)"></i>Management</span></div><span>Logical schematic · placement simplified · pan on mobile</span></div><div class="detail-panel" id="partDetail" aria-live="polite"></div></section>
 <details class="system-key"><summary>Diagram key: iDRAC, DIMM, NIC, OCP, PCIe, HBM</summary><p>iDRAC = Dell remote management controller; DIMM = memory module; NIC = network adapter; OCP = adapter form factor here; PCIe = expansion connection; HBM = accelerator-local high-bandwidth memory.</p></details>
 <div class="takeaway"><span class="symbol">↳</span><div><h3>PowerEdge is a portfolio, not one chassis.</h3><p>A rack server can stand alone. MX compute needs its shared enclosure. An integrated GPU node has its own power, cooling and rack requirements. The Dell logo does not make their parts interchangeable.</p></div></div>
 <section class="section panel panel-pad"><div class="eyebrow">MANAGEMENT, DECODED</div><h2 style="margin-top:10px">One server. A fleet. A modular chassis.</h2><div class="three-col"><article><h3>iDRAC</h3><p class="small muted">Health, power and remote administration for an individual server. This guide includes iDRAC9 and iDRAC10 platforms; features depend on firmware and license.</p>${sourceLink('r770','iDRAC in R770')}</article><article><h3>OpenManage Enterprise</h3><p class="small muted">A fleet view for discovery, monitoring and supported lifecycle tasks. Check the console release’s support matrix for each server and feature.</p>${sourceLink('ome','Fleet support matrices')}</article><article><h3>OME-Modular</h3><p class="small muted">Runs on MX9002m management modules in MX7000. It coordinates chassis resources, sleds and fabric management, including profiles and templates.</p>${sourceLink('omem','MX management overview')}</article></div><p class="small muted">Your operating system or hypervisor runs the applications and virtual machines. These management tools administer the infrastructure.</p></section><div class="next-lesson"><p>Next: meet the models and compare their options.</p><a class="btn primary" href="#lineup">Explore the lineup →</a></div>`;}
// END overview
// BEGIN lineup
function lineup(){return `${intro('02 / THE HARDWARE EXPLORER','Find the platform behind the name.','Explore 17 representative PowerEdge models. Filter by family, host CPU or workload, then open a profile or compare up to three.')}
 <div class="filterbar"><div class="filter search"><label for="modelSearch">SEARCH THE LINEUP</label><input id="modelSearch" type="search" placeholder="Try R7725, EPYC, E3.S, Gaudi…" value="${esc(state.filters.q)}"></div><div class="filter"><label for="familyFilter">FAMILY</label><select id="familyFilter">${selectOptions(['All','Rack','Modular','Tower','Edge','AI'],state.filters.family)}</select></div><div class="filter"><label for="vendorFilter">HOST CPU</label><select id="vendorFilter">${selectOptions(['All','AMD','Intel'],state.filters.vendor)}</select></div><div class="filter"><label for="useFilter">WORKLOAD</label><select id="useFilter">${selectOptions(['All','General compute','Virtualization','Data & storage','AI & GPUs','Edge & branch'],state.filters.use)}</select></div></div><div class="results-info"><p id="modelCount" aria-live="polite"></p><button class="text-btn" data-reset-filters>Reset filters ↻</button></div><div class="model-grid" id="modelGrid"></div><div class="compare-tray" id="compareTray" hidden><p id="compareStatus" aria-live="polite"></p><div class="button-row"><button class="btn compact ghost" data-clear-compare>Clear</button><button class="btn compact primary" id="compareButton" data-compare>Compare selected →</button></div></div>
 <div class="warning"><strong>Read “up to” as a configuration ceiling.</strong> Memory, drives and GPUs can reach their maxima in different builds. Workload filters are learning aids, not performance benchmarks or certified solution recommendations.</div>
 <section class="section" id="history"><h2>Where the rest of Dell fits</h2><div class="history-list"><article><span class="badge accent">MORE RACK CHOICES</span><h3 style="margin-top:16px">Optimized, performance, specialized</h3><p>R4715 / R5715 target more economical AMD single-socket configurations. R7725xd emphasizes storage density; R770AP is a distinct Xeon 6 6900-series platform. These are additional models, not interchangeable options on the servers above.</p>${sourceLink('portfolio','See Dell’s three rack categories')}</article><article><span class="badge accent">BEYOND x86</span><h3 style="margin-top:16px">Grace and integrated AI racks</h3><p>PowerEdge also includes Arm-based NVIDIA Grace systems, such as XE8712 and XE9712. A rack-scale GPU system has a different unit of deployment from a self-contained R-series server.</p>${sourceLink('catalog','Explore Dell’s broader compute portfolio')}</article></div><div class="lesson" style="margin-top:16px"><h3>Existing estates contain several generations.</h3><p>You will also see R660 / R760, R6615 / R7615, other towers, older modular designs and specialized platforms. A generation label alone is not an end-of-support date. Support depends on the exact product, configuration and service entitlement.</p><p class="scope-note">This guide selects 16G / 17G rack, tower, MX, XR and XE examples. It does not inventory every PowerEdge, integrated-rack or Dell storage product.</p></div></section><div class="next-lesson"><p>Next: separate host CPU choice from everything around it.</p><a class="btn primary" href="#platforms">AMD & Intel →</a></div>`;}
// END lineup
// BEGIN platforms
function platforms(){return `${intro('03 / TWO CPU ECOSYSTEMS','Start with the CPU. Keep going.','Dell offers AMD and Intel hosts across several designs. Socket count, memory topology, expansion and cooling matter as much as the processor logo.')}
 <div class="two-col"><article class="vendor-panel amd"><span class="badge amd">AMD CPU PLATFORMS</span><h2>EPYC</h2><p>One or two sockets in mainstream racks; AMD host processors also support dedicated AI platforms.</p><ul><li><b>R6715 / R7715:</b> one EPYC 9005.</li><li><b>R6725 / R7725:</b> up to two EPYC 9005.</li><li><b>XE7745:</b> two EPYC hosts for PCIe GPUs.</li><li><b>XE9785 / XE9785L:</b> two EPYC hosts with air or direct liquid cooling.</li></ul>${modelButtons(['r6715','r7715','r6725','r7725','xe7745','xe9785','xe9785l'])}<p class="small">CPU qualification differs by model. Do not assume every EPYC 9005 SKU fits every server listed here.</p></article><article class="vendor-panel intel"><span class="badge intel">INTEL CPU PLATFORMS</span><h2>Xeon</h2><p>Intel examples span racks, towers, MX sleds, edge systems and dedicated AI servers.</p><ul><li><b>R470 / R570:</b> one Xeon 6.</li><li><b>R670 / R770:</b> up to two Xeon 6.</li><li><b>T560 / MX760c:</b> qualified Xeon Scalable.</li><li><b>XR8720t:</b> one Xeon 6 SoC.</li><li><b>XE7740 / XE9780:</b> two Xeon 6 hosts.</li></ul>${modelButtons(['r470','r770','t560','mx760','xr8720','xe9780'])}<p class="small">Xeon 6 is a family, not one socket-compatible universal CPU. P-core, E-core and SoC options follow the exact platform’s qualification.</p></article></div>
 <div class="takeaway"><span class="symbol">≠</span><div><h3>CPU brand does not determine accelerator brand.</h3><p>XE9680 uses Intel host CPUs with NVIDIA, AMD MI300X or Intel Gaudi 3 accelerator builds. XE9785L uses AMD host CPUs with AMD MI355X or NVIDIA HGX B300 options. Each combination is qualified as a system.</p></div></div>
 <section class="section"><div class="chapter-heading"><h2>The practical platform map</h2><span class="small">Select a model for the specification.</span></div><div class="table-scroll"><table><caption class="visually-hidden">Dell form factors and socket counts by CPU vendor</caption><thead><tr><th scope="col">Design</th><th scope="col">AMD examples</th><th scope="col">Intel examples</th></tr></thead><tbody>${[['1U · one socket',['r6715'],['r470']],['2U · one socket',['r7715'],['r570']],['1U · two sockets',['r6725'],['r670']],['2U · two sockets',['r7725'],['r770']],['MX modular',[],['mx760']],['Tower',[],['t560']],['Compact edge',[],['xr8720']],['4U · PCIe accelerator platform',['xe7745'],['xe7740']],['Integrated eight-accelerator system',['xe9785','xe9785l'],['xe9680','xe9780']]].map(([label,a,b])=>`<tr><th scope="row">${label}</th><td>${a.length?modelButtons(a):'<span class="support-none">No example in this guide</span>'}</td><td>${b.length?modelButtons(b):'<span class="support-none">No example in this guide</span>'}</td></tr>`).join('')}</tbody></table></div><p class="matrix-note">Selected examples, not a performance ranking. An empty cell is not a Dell-wide support prohibition. The AI row includes different rack, cooling and accelerator designs.</p></section>
 <section class="section two-col"><article class="lesson"><div class="eyebrow">COMPARE THE CONSTRAINTS</div><h3>What will limit the workload first?</h3><p>A VM host can run out of RAM before CPU cores. A database may be constrained by licensing or storage latency. An AI model may depend most on accelerator memory and the links between devices.</p><p>Compare measured application performance, memory capacity and bandwidth, drive layout, network I/O, power, cooling and software support. Two-socket does not automatically mean better.</p></article><article class="lesson"><div class="eyebrow">SOFTWARE IS ANOTHER LAYER</div><h3>What runs on PowerEdge?</h3><p>Qualified Windows Server, Linux and virtualization releases vary by platform. GPU frameworks also depend on accelerator drivers and the supported software stack.</p><p>iDRAC and OpenManage manage equipment. The installed OS or hypervisor runs the workload. A listed OS family is not approval for every release or hardware combination.</p>${sourceLink('os','Dell OS and hypervisor support')}</article></section><div class="next-lesson"><p>Next: decode drives, GPU formats and cooling.</p><a class="btn primary" href="#components">Storage & GPUs →</a></div>`;}
// END platforms
// BEGIN driveLessons
const driveLessons={
 sff:{label:'2.5-inch SFF',art:'',title:'The shape is only the beginning.',text:'Small-form-factor bays commonly hold 2.5-inch drives. SAS, SATA and NVMe describe different interfaces or protocols; the backplane and controller decide which options work in a particular bay.',notice:'MX760c lists several SFF sled configurations. XE9680 also has a separate SFF NVMe layout, required for its documented Gaudi 3 build.',ids:['mx760','xe9680','r770'],source:'xe9680spec'},
 lff:{label:'3.5-inch LFF',art:'lff',title:'Larger bays for capacity-oriented storage.',text:'Large-form-factor bays commonly hold 3.5-inch hard drives. Drive count and raw capacity are different from usable capacity after RAID, spares and software overhead.',notice:'T560 documents up to twelve LFF drives, and other configurations that mix eight LFF bays with eight NVMe SSDs. These are distinct chassis layouts.',ids:['t560'],source:'t560'},
 e3:{label:'E3.S NVMe',art:'e3',title:'Enterprise flash with its own bay design.',text:'E3.S is part of the EDSFF family of SSD shapes. NVMe is the protocol. The drive, carrier, backplane and cooling all belong to the supported configuration.',notice:'XE7740 and XE7745 list up to eight front E3.S Gen5 NVMe SSDs. MX760c has an eight-E3.S sled configuration. These do not use the same physical server design.',ids:['xe7740','xe7745','mx760'],source:'xe7745'},
 e1:{label:'E1.S NVMe',art:'e1',title:'A different enterprise SSD form factor.',text:'E1.S and E3.S both serve enterprise flash storage, but their physical dimensions and carriers differ. A shared NVMe protocol does not make them interchangeable.',notice:'XE9785L documents a sixteen-E1.S configuration. The air-cooled XE9780 uses E3.S or U.2 configurations instead; similar model names do not establish common drive parts.',ids:['xe9785l','xe9780'],source:'xeai'},
 m2:{label:'M.2 / BOSS',art:'m2',title:'Give the operating system its own storage.',text:'Dell BOSS is a dedicated boot-storage subsystem. Supported versions can mirror two M.2 SSDs, leaving main drive bays available for workload data. M.2 describes the physical module, not a universal boot device.',notice:'MX760c lists BOSS-N1 with two M.2 NVMe SSDs and RAID 1. XR8720t also uses internal M.2 storage, but its three non-hot-swap drives should not be assumed to be that same BOSS layout.',ids:['mx760','xr8720','xe9785l'],source:'mx760'}
};
// END driveLessons
// BEGIN components
function components(){return `${intro('04 / UNDER THE COVER','Decode storage. Understand acceleration.','Separate the drive shape, connection protocol, accelerator format and qualified system. Similar names often describe very different hardware.')}
 <section class="panel"><div class="panel-head"><div><div class="eyebrow">STORAGE EXPLORER</div><h2 style="margin-top:8px">What does the drive label tell you?</h2><p>Select a format to see how it appears in PowerEdge.</p></div><span class="badge accent">FORM ≠ PROTOCOL</span></div><div class="storage-lab"><div class="lab-controls" aria-label="Drive formats">${Object.entries(driveLessons).map(([id,d])=>`<button data-drive="${id}" aria-pressed="${state.drive===id}">${d.label}</button>`).join('')}</div><div class="lab-content" id="driveLesson"></div></div></section>
 <div class="two-col section"><article class="lesson"><h3>PERC, HBA, BOSS: different jobs.</h3><p><b>PERC</b> is Dell’s RAID-controller family. An <b>HBA</b> connects storage with a different controller role. <b>BOSS</b> focuses on boot storage. The <b>backplane</b> is the bay-connection hardware.</p><p>NVMe is not automatically direct-only or incompatible with RAID. Use the controller and backplane combination listed for that PowerEdge model.</p>${sourceLink('r770','R770 storage and controller choices')}</article><article class="lesson"><h3>Three places to keep data.</h3><p><b>DDR5 RAM:</b> active working space for the host CPUs.<br><b>Accelerator memory:</b> local working space for GPUs / AI accelerators.<br><b>SSDs and hard drives:</b> persistent software and data.</p><p>Adding SSD capacity does not increase GPU HBM. Total HBM across devices is not automatically one flat pool available to every program.</p><a href="#sources/glossary">Explore the glossary →</a></article></div>
 <section class="section"><div class="chapter-heading"><h2>Three ways to add acceleration</h2><span class="small">Different chassis, power and cooling budgets.</span></div><div class="three-col"><article class="lesson"><div class="big-number">01</div><h3>GPUs in a general server</h3><p>A qualified PCIe card adds inference, visualization or parallel compute to a rack or tower platform. R770 and R7725 are still versatile general-purpose servers.</p>${modelButtons(['r770','r7725','t560'])}<p class="small muted">R7725 qualifies MI350P at 450 W per card. A two-card study illustrates a workload, while the model manual defines compatibility.</p>${sourceLink('faeR7725GPU','R7725 qualification and 450 W cap')}</article><article class="lesson"><div class="big-number">02</div><h3>A PCIe GPU-focused chassis</h3><p>XE7740 and XE7745 dedicate 4U to accelerator expansion, power and air cooling. They offer Intel and AMD host choices respectively.</p>${modelButtons(['xe7740','xe7745'])}<p class="small muted">XE7745 supports up to eight MI350P PCIe cards at 600 W with the correct PSU and redundancy configuration. NVIDIA alternatives use separate population rules.</p>${sourceLink('faeXE7745GPU','XE7745 accelerator qualification')}</article><article class="lesson"><div class="big-number">03</div><h3>An integrated GPU subsystem</h3><p>XE9680, XE9780, XE9785 and XE9785L use specialized accelerator platforms. SXM / OAM modules, their baseboards and high-speed links differ from plug-in PCIe cards.</p>${modelButtons(['xe9680','xe9780','xe9785','xe9785l'])}<p class="small muted">Air-cooled and direct-liquid-cooled systems have different facility requirements. “Eight GPUs” does not make them equivalent.</p>${sourceLink('xe9680','XE9680 system architecture')}</article></div></section>
 <section class="panel section"><div class="panel-head"><div><div class="eyebrow">THE CPU / ACCELERATOR CROSSOVER</div><h2 style="margin-top:8px">Documented pairings worth remembering</h2></div></div><div class="table-scroll" style="border:0;border-radius:0"><table><caption class="visually-hidden">Dell host CPU and accelerator examples</caption><thead><tr><th scope="col">Host CPU</th><th scope="col">Accelerator</th><th scope="col">Example</th><th scope="col">What to remember</th></tr></thead><tbody>
 <tr><th scope="row">AMD EPYC</th><td>NVIDIA PCIe / HGX</td><td>${modelButtons(['xe7745','xe9785l'])}</td><td>Same host vendor, different accelerator formats and cooling designs.</td></tr>
 <tr><th scope="row">AMD EPYC</th><td>AMD Instinct MI350P</td><td>${modelButtons(['r7725','xe7745'])}</td><td>R7725: up to two cards, capped at 450 W. XE7745: up to eight at 600 W; PSU and slot rules apply.</td></tr>
 <tr><th scope="row">AMD EPYC</th><td>8 × AMD Instinct MI355X</td><td>${modelButtons(['xe9785','xe9785l'])}</td><td>XE9785 is 10U air-cooled; XE9785L is a 3 OU liquid-cooled node requiring IR7000 infrastructure.</td></tr>
 <tr><th scope="row">Intel Xeon</th><td>NVIDIA PCIe / HGX</td><td>${modelButtons(['xe7740','xe9780'])}</td><td>Plug-in cards and integrated HGX platforms require different server designs.</td></tr>
 <tr><th scope="row">Intel Xeon</th><td>8 × AMD Instinct MI300X</td><td>${modelButtons(['xe9680'])}</td><td>AMD accelerators with Intel host CPUs are a documented pairing.</td></tr>
 <tr><th scope="row">Intel Xeon</th><td>8 × Intel Gaudi 3</td><td>${modelButtons(['xe9680'])}</td><td>Gaudi is the AI accelerator here. It is separate from the Xeon host CPU.</td></tr>
 </tbody></table></div></section>
 <div class="warning"><strong>These are separate supported builds, not a mix-and-match GPU tray.</strong> A PCIe MI350P card, an MI355X OAM module and an NVIDIA HGX baseboard are different hardware. CPU brand, connector shape and a vendor logo are not sufficient compatibility tests. ${sourceLink('xe9680','XE9680 platform rules')}</div>
 <section class="section two-col"><article class="lesson"><div class="eyebrow">RACK SPACE IS NOT THE WHOLE FACILITY</div><h3>10U air versus 3 OU liquid.</h3><p>XE9785 offers AMD-host MI355X in 10U with air cooling; XE9780 offers Intel-host NVIDIA HGX in 10U. XE9785L is a 3-OU node for IR7000 with direct liquid cooling and rack-level power infrastructure. An Open Rack Unit is 48 mm; a conventional rack unit is 44.45 mm.</p><p>Compare the full installed system: rack format, power delivery, cooling, network and service access—not only the compute node’s height.</p>${sourceLink('xe9785l','XE9785L rack and cooling requirements')}</article><article class="lesson"><div class="eyebrow">THE SOFTWARE ECOSYSTEM MATTERS</div><h3>GPU memory is only one requirement.</h3><p>Applications need a compatible runtime, drivers, supported OS and the right multi-device communication stack. A model that fits in memory still needs supported software to run efficiently.</p><p>For cluster workloads, also check the external network and storage design. This guide describes platform options; it does not benchmark competing accelerator ecosystems.</p>${sourceLink('os','Start with Dell’s software support references')}</article></section>
 <section class="section"><h2>From an option to a supported system</h2><div class="compat-steps"><article class="compat-step"><h3>Exact platform</h3><p>Complete model, chassis, CPU and accelerator configuration.</p></article><article class="compat-step"><h3>Population rules</h3><p>DIMMs, drive cages, controllers, risers and adapters.</p></article><article class="compat-step"><h3>Power & cooling</h3><p>PSUs, fans, ambient limits, rack and liquid infrastructure.</p></article><article class="compat-step"><h3>Software stack</h3><p>Firmware, drivers, OS, hypervisor and solution qualification.</p></article></div></section><div class="next-lesson"><p>Ready to connect the dots?</p><a class="btn primary" href="#quiz">Test your knowledge →</a></div>`;}
// END components
// BEGIN sourcesView
function sourcesView(){return `${intro('06 / KEEP LEARNING','Go straight to the evidence.','A source-linked learning snapshot reviewed on October 7, 2026. Hardware drawings are original simplified illustrations based on Dell’s product documentation.')}
 <div class="two-col"><article class="lesson"><h3>What this guide covers</h3><p>${models.length} representative PowerEdge platforms across rack, MX modular, tower, edge and AI systems. The focus is understanding CPU choices, memory, storage, accelerators, cooling and management.</p><p>This is a learning map, not an exhaustive catalog, ordering tool or support matrix. “Supported” depends on the exact model, options and software release; a listed future feature does not establish orderability today.</p></article><article class="lesson"><h3>How source differences were handled</h3><p>XE9785L is described as <b>3 OU</b>, following its model specifications, even where the broad portfolio table says 3U. T560’s conditional 1.5 TB memory limit follows its service manual, rather than the regional overview’s older 1 TB figure.</p><p>XE7745 follows the current service manual: MI350P qualification and up to 6 TB host RAM. R7725 MI350P is capped at 450 W. XE9785’s 6 TB ceiling is B300-specific; MI355X uses up to 3 TB. Broad CPU-family maxima are not assumed to apply to every model.</p></article></div>
 <section class="section" id="glossary"><div class="eyebrow">PLAIN-ENGLISH REFERENCE</div><h2 style="margin-top:10px">Keep the acronyms under control.</h2><label class="visually-hidden" for="glossarySearch">Search glossary</label><input class="glossary-search" id="glossarySearch" type="search" placeholder="Find a term: iDRAC, BOSS, NVMe…"><div class="glossary" id="glossaryList">${Object.entries(glossary).map(([term,def])=>`<details data-term="${esc((term+' '+def).toLowerCase())}"><summary>${esc(term)}</summary><p>${def}</p></details>`).join('')}</div><p id="glossaryEmpty" class="muted" hidden>No matching terms. Try a shorter search.</p></section>
 <section class="section"><div class="eyebrow">OFFICIAL SOURCE LIBRARY</div><h2 style="margin-top:10px">Follow the document behind the detail.</h2><p class="muted small">“Reviewed” is this guide’s access date. Publication dates are shown where verified. Some sources use regional Dell URLs; the XE9680 product page is Japanese, with its English technical guide linked separately. Linked documents can change. No source documents were supplied by the user.</p><div class="source-list">${Object.entries(sources).map(([id,s])=>`<article class="source-item" id="source-${id}">${sourceLink(id)}<p>${s.scope}</p><small>${s.date} · ${s.loc}</small></article>`).join('')}</div></section>`;}
// END sourcesView
