// Shared generation chronology for all vendor guides.
let selectedGeneration=null;
const generationAsOfYear=Number(generationData.reviewed.slice(0,4));
const generationAsOfLabel='8 Oct 2026';
const generationFor=m=>generationData.generations.find(g=>g.id===generationData.models[m.id].generationId);
const generationAge=year=>{const n=generationAsOfYear-year;return n===0?'This year':n>0?'About '+n+' year'+(n===1?'':'s')+' ago':'Future milestone';};
const generationSources=ids=>[...new Set(ids||[])].map(id=>sourceLink('generation_'+id)).join(' · ');
function generationSearchTerms(m){const d=generationData.models[m.id],g=generationFor(m);return [g.label,String(g.year),d.modelYear?String(d.modelYear):''];}
function modelGenerationBadge(m){const d=generationData.models[m.id],g=generationFor(m);return `<div class="model-era"><div><span class="era-kicker">${esc(g.dateLabel)}</span><span class="era-name">${esc(g.label)}</span></div><strong class="era-year">${g.year}</strong><small>${generationAge(g.year)}${d.modelYear?` · Model ${esc((d.modelDateKind||'Announced').toLowerCase())} ${d.modelYear}`:''}</small></div>`;}
function modelGenerationDetail(m){const d=generationData.models[m.id],g=generationFor(m);return `<section class="generation-model-detail" aria-label="Generation and model timing"><div class="generation-date-grid"><div><span class="era-kicker">${esc(g.dateLabel)}</span><strong>${g.year}</strong><span class="generation-model-name">${esc(g.label)}</span><span>${generationAge(g.year)}</span></div><div><span class="era-kicker">THIS MODEL</span>${d.modelYear?`<strong>${d.modelYear}</strong><span>${esc(d.modelDateKind||'Announced')}</span>`:'<strong class="date-unknown">Exact debut unconfirmed</strong><span>Generation year provides the context.</span>'}</div></div><p>${esc(d.note||g.summary)}</p><p class="generation-date-caution">Generation age is approximate as of ${generationAsOfLabel}. A later CPU or GPU option does not reset the original platform date.</p><div class="generation-citations">${generationSources([...(g.sourceIds||[]),...(d.sourceIds||[])])}</div></section>`;}
function generationCompareRows(list){return `<tr class="generation-compare"><th scope="row">Generation / platform date</th>${list.map(m=>{const g=generationFor(m);return `<td><b>${g.year} · ${esc(g.label)}</b><br><small>${esc(g.dateLabel)} · ${generationAge(g.year)} as of ${generationAsOfLabel}</small><div class="generation-citations">${generationSources(g.sourceIds)}</div></td>`;}).join('')}</tr><tr><th scope="row">This model’s timing</th>${list.map(m=>{const d=generationData.models[m.id];return `<td>${d.modelYear?`<b>${esc(d.modelDateKind||'Announced')} ${d.modelYear}</b>`:'Exact model debut unconfirmed'}<p class="small muted">${esc(d.note||'Use the generation date as context, not an exact release date for this model.')}</p>${d.sourceIds?.length?`<div class="generation-citations">${generationSources(d.sourceIds)}</div>`:''}</td>`;}).join('')}</tr>`;}
function generationTimeline(){
 const generations=[...generationData.generations].sort((a,b)=>a.year-b.year);
 if(!selectedGeneration)selectedGeneration=generationData.defaultGeneration||[...generations].reverse().find(g=>models.some(m=>generationData.models[m.id].generationId===g.id))?.id||generations[generations.length-1].id;
 return `<section class="generation-timeline" id="generations" aria-labelledby="generationHeading"><div class="generation-heading"><div><div class="eyebrow">A LITTLE HISTORY. A LOT MORE CONTEXT.</div><h2 id="generationHeading">When did these generations begin?</h2><p>${esc(generationData.intro)}</p></div><span class="generation-asof">DATES CHECKED<br><b>${generationAsOfLabel}</b></span></div><div class="generation-track" aria-label="Generation milestones">${generations.map(g=>`<button class="generation-stop" data-generation="${esc(g.id)}" aria-pressed="${g.id===selectedGeneration}" aria-controls="generationDetail"><span class="generation-dot" aria-hidden="true"></span><strong>${g.year}</strong><span>${esc(g.label)}</span></button>`).join('')}</div><div class="generation-detail" id="generationDetail" aria-live="polite"></div><p class="generation-footnote"><b>Read the date, then the scope.</b> These are documented generation introductions, family debuts and later rollout milestones. Individual models, CPU support and availability can follow later. Approximate age uses calendar years; it is separate from end-of-sale and support dates.</p></section>`;
}
function renderGenerationDetail(){if(!$('#generationDetail'))return;const track=$('.generation-track'),active=$('[data-generation="'+selectedGeneration+'"]');if(track&&active)track.scrollLeft+=active.getBoundingClientRect().left-track.getBoundingClientRect().left-(track.clientWidth-active.clientWidth)/2;const g=generationData.generations.find(g=>g.id===selectedGeneration),ids=models.filter(m=>generationData.models[m.id].generationId===g.id).map(m=>m.id);$$('[data-generation]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.generation===g.id)));$('#generationDetail').innerHTML=`<div class="generation-year-display"><strong>${g.year}</strong><span>${generationAge(g.year)}</span></div><div class="generation-story"><span class="era-kicker">${esc(g.dateLabel)}</span><h3>${esc(g.label)}</h3><p>${esc(g.summary)}</p>${ids.length?`<button class="btn compact ghost" data-generation-filter="${esc(g.id)}">Explore ${ids.length} model${ids.length===1?'':'s'} from this group →</button>`:'<p class="generation-history-note">Earlier-generation context · no full model profile in this guide.</p>'}<div class="generation-citations">${generationSources(g.sourceIds)}</div></div>`;}
function generationFilter(){return `<div class="filter generation-filter"><label for="generationFilter">GENERATION / PLATFORM</label><select id="generationFilter"><option value="All">All generations</option>${[...generationData.generations].filter(g=>models.some(m=>generationData.models[m.id].generationId===g.id)).sort((a,b)=>b.year-a.year).map(g=>`<option value="${esc(g.id)}" ${state.filters.generation===g.id?'selected':''}>${g.year} · ${esc(g.label)}</option>`).join('')}</select></div>`;}
function withGenerationContext(page,html){
 if(page==='overview')return html.replace(/(<section class="family-grid[\s\S]*?<\/section>)/,`$1${generationTimeline()}`);
 if(page==='lineup'){
  html=html.replace('<div class="filterbar">',`<div class="generation-lineup-intro"><span class="generation-mini-icon" aria-hidden="true">◷</span><p><b>Now with generation years.</b> Each model shows its generation or platform milestone, with separate model dates where verified. Approximate ages are as of ${generationAsOfLabel}.</p><a href="#overview/generations">See the timeline →</a></div><div class="filterbar">`);
  const start=html.indexOf('<div class="filterbar">'),end=html.indexOf('</select></div></div>',start);if(end!==-1)html=html.slice(0,end)+html.slice(end).replace('</select></div></div>','</select></div>'+generationFilter()+'</div>');
 }
 if(page==='platforms')html=html.replace('</p></div>','</p></div><div class="generation-reading-note"><b>Server generation ≠ CPU generation.</b> The dates on model profiles refer to the server platform. A later processor qualification can extend an existing generation. <a href="#overview/generations">Explore the generation timeline →</a></div>');
 if(page==='sources')html=html.replace('<section class="section" id="glossary">','<div class="generation-reading-note"><b>Chronology added '+generationAsOfLabel+'.</b> Dated announcements establish generation introductions; model-specific announcements or dated documentation are labeled separately. The date references appear in the source library below. <a href="#overview/generations">Open the timeline →</a></div><section class="section" id="glossary">');
 return html;
}
document.addEventListener('click',e=>{const generation=e.target.closest('[data-generation]');if(generation){selectedGeneration=generation.dataset.generation;renderGenerationDetail();}const filter=e.target.closest('[data-generation-filter]');if(filter){state.filters={q:'',family:'All',vendor:'All',use:'All',generation:filter.dataset.generationFilter};if(state.page==='lineup')render();else location.hash='lineup';}});
document.addEventListener('change',e=>{if(e.target.id==='generationFilter'){state.filters.generation=e.target.value;renderModels();}});
