// BEGIN hardware
function hardware(shape='rack2',hero=false){
 // Physical references and configuration limits: work/physical-hpe.json.
 // Shared primitives describe carriers; each model retains its source front layout.
 const uid='hpe-art-'+(++artSerial),metal=`url(#${uid}-metal)`,mesh=`url(#${uid}-mesh)`;
 const rect=(x,y,w,h,fill='#171d1f',stroke='#6a7679',r=1)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="${fill}" stroke="${stroke}" stroke-width=".65"/>`;
 const logo=(x,y,w=10)=>`<rect x="${x}" y="${y}" width="${w}" height="${w*.38}" fill="none" stroke="#00b388" stroke-width="1.25"/>`;
 const vent=(x,y,w,h)=>rect(x,y,w,h,mesh,'#525d60');
 const led=(x,y,c='#59d5ab',r=1)=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${c}"/>`;
 const vdrive=(x,y,w,h,thin=false)=>rect(x,y,w,h,'#22292c','#7c8688',.7)+rect(x+Math.min(1.2,w*.12),y+2,w-2*Math.min(1.2,w*.12),h-4,'#0b0f11','#151a1c',.5)+`<path d="M${x+w*.28} ${y+4}v${Math.max(2,h-13)}l${w*.2} 2h${w*.23}V${y+4}" fill="#30373b" stroke="#596367" stroke-width=".6"/>`+rect(x+Math.min(1.7,w*.15),y+h-9,w-2*Math.min(1.7,w*.15),3,thin?'#4c5a61':'#913b60','#171d1f',.2)+led(x+w*.34,y+h-3.2,'#46cbb4',.75)+led(x+w*.7,y+h-3.2,'#99b5c0',.6);
 const hdrive=(x,y,w,h,thin=false)=>rect(x,y,w,h,'#242b2e','#738084',.6)+rect(x+2,y+1,w-4,h-2,'#0b0f11','#262f33',.4)+`<path d="M${x+5} ${y+h*.3}h${w*.68}v${h*.36}H${x+5}" fill="#30383d" stroke="#646f73" stroke-width=".5"/>`+rect(x+w-6,y+1.7,2.2,Math.max(1,h-3.4),thin?'#5c6872':'#824360','#202729',.2)+led(x+w-10,y+h*.6,'#48c7a8',.7);
 const bank=(x,y,w,h,cols,rows=1,horizontal=false,thin=false)=>{let b='';for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const dw=(w-(cols-1)*1.8)/cols,dh=(h-(rows-1)*1.5)/rows;b+=(horizontal?hdrive:vdrive)(x+c*(dw+1.8),y+r*(dh+1.5),dw,dh,thin);}return b;};
 const io=(x,y,w,h,rows=2)=>{let b=rect(x,y,w,h,'#9ba6a8','#ccd1d0');for(let i=0;i<rows;i++)b+=vent(x+2,y+2+i*(h-4)/rows,w-4,(h-4)/rows-2);return b;};
 const boot=(x,y,w,h)=>vent(x,y,w,h)+rect(x+w*.24,y+h*.22,w*.52,h*.5,'#171d1f','#7e898d')+led(x+w*.39,y+h*.55)+led(x+w*.63,y+h*.55,'#8ca6bf');
 const shell=(x,y,w,h)=>`<path d="M${x} ${y}l21 -15h${w-37}l16 15z" fill="${metal}" stroke="#939e9f" stroke-width=".6"/>`+rect(x,y,w,h,'#353e41','#9aa4a5',2)+rect(x+1,y+1,12,h-2,'#161d20','#5b676b',1.5)+rect(x+w-13,y+1,12,h-2,'#171e21','#5b676b',1.5)+logo(x+w-11,y+h-9,8)+led(x+w-7,y+8)+led(x+w-7,y+13,'#719cbf')+`<path d="M${x+6} ${y+7}v${Math.max(4,h-15)}" stroke="#77868a" stroke-width="1.4"/>`;
 const rack=(units,draw)=>{const w=units>=8?178:units>=5?304:332,h=w*units*44.45/482.6,x=(360-w)/2,y=(190-h)/2+7;return shell(x,y,w,h)+draw(x+16,y+3,w-32,h-6);};
 const group1=(x,y,w,h,kind)=>{
  let b='',g=(w-8)/5;
  if(kind==='sff-media'){b+=bank(x,y,g*3+4,h,3,2,true);b+=bank(x+3*(g+2),y+h*.51,g*2+2,h*.49,2,1,true);b+=vent(x+3*(g+2),y,g*2+2,h*.43)+rect(x+3*(g+2)+8,y+2,g*1.65,h*.25,'#272f33','#737d80');}
  else if(kind==='sff10'){b+=bank(x,y,g*4+6,h,4,2,true);b+=rect(x+4*(g+2),y,g,h,'#1a2226','#626e73');for(let i=0;i<2;i++)b+=vent(x+4*(g+2)+2,y+2+i*h/2,g-4,h/2-4);}
  else if(kind==='hybrid'){b+=bank(x,y,g,h,1,2,true)+bank(x+g+2,y,g,h,1,4,true,true)+io(x+2*(g+2),y,g,h,2)+bank(x+3*(g+2),y,g,h,1,4,true,true)+boot(x+4*(g+2),y,g,h);}
  else {for(let c of [0,1,3,4])b+=bank(x+c*(g+2),y,g,h,1,4,true,true);b+=kind==='gen13'?boot(x+2*(g+2),y,g,h*.52)+io(x+2*(g+2),y+h*.6,g,h*.4,1):boot(x+2*(g+2),y,g,h);}
  return b;
 };
 const group2=(x,y,w,h,kind)=>{
  const g=(w-4)/3;let b='';
  if(kind==='all-sff'){for(let c=0;c<3;c++)b+=bank(x+c*(g+2),y,g,h,8);}
  else if(kind==='mixed-amd'){b+=bank(x,y,g,h,12,1,false,true);b+=bank(x+g+2,y,g*.37,h,4,1,false,true)+boot(x+g*1.4+2,y,g*.3,h)+io(x+g*1.75+2,y,g*.25-2,h,2);b+=bank(x+2*(g+2),y,g,h,8);}
  else if(kind==='mixed-intel'){b+=vent(x,y,g,h);b+=bank(x+g+2,y,g*.3,h,4,1,false,true)+boot(x+g*1.34+2,y,g*.3,h)+io(x+g*1.69+2,y,g*.31-2,h,2);b+=bank(x+2*(g+2),y,g,h,8);}
  else {b+=bank(x,y,g,h,8)+bank(x+g+2,y,g*.65,h,8,1,false,true)+io(x+g*1.7+2,y,g*.3-2,h,2)+vent(x+2*(g+2),y,g,h);}
  return b;
 };
 const frame=(x=91,y=12,w=176,h=164,highlight=false)=>{
  let b=rect(x,y,w,h,metal,'#a6b0b2',2)+rect(x+5,y+4,w-10,h-8,'#10181b','#626c71');
  const left=x+16,top=y+7,iw=w-29,ih=h-15,cw=(iw-5*2)/6,rh=(ih-3)/2;
  for(let r=0;r<2;r++){b+=vent(x+6,top+r*(rh+3),8,rh);for(let c=0;c<6;c++){const xx=left+c*(cw+2),yy=top+r*(rh+3);b+=rect(xx,yy,cw,rh,'#222a2e',highlight&&r===0&&c===0?'#00b388':'#626e72');b+=bank(xx+3,yy+4,cw-6,rh*.3,2)+vent(xx+3,yy+rh*.39,cw-6,rh*.16)+bank(xx+3,yy+rh*.61,cw-6,rh*.31,2);}}
  return b+logo(x+w-11,y+h-13,6);
 };
 let body='',label='HPE hardware illustration';
 const key=shape.startsWith('hpe-')?shape.slice(4):({rack1:'dl325',rack2:'dl380',rack4:'dl580',gpu4:'dl380a',gpu6:'xd685',gpu10:'xd690',blade:'sy480',tower:'ml350',edge:'dl145',ocp4:'xd245',ocp2:'xd285'}[shape]||shape);
 if(key==='portfolio'){
  body=`<g transform="translate(0 -38)">${rack(1,(x,y,w,h)=>group1(x,y,w,h,'sff-media'))}</g><g transform="translate(0 23)">${rack(2,(x,y,w,h)=>group2(x,y,w,h,'mixed-intel'))}</g>`;label='HPE ProLiant 1U and 2U rack fronts, representative configurations';
 }else if(key==='frame'){body=frame();label='Synergy 12000 frame front with twelve upright half-height compute bays and two left appliance bays';}
 else if(['dl320','dl325','dl360','dl365','dl525'].includes(key)){
  const kinds={dl320:'sff-media',dl325:'edsff',dl360:'hybrid',dl365:'sff10',dl525:'gen13'};body=rack(1,(x,y,w,h)=>group1(x,y,w,h,kinds[key]));label=`HPE ${key.toUpperCase()} 1U front, model-specific horizontal drive-cage arrangement`;
 }else if(['dl340','dl345','dl380','dl385'].includes(key)){
  const kinds={dl340:'sff-left',dl345:'mixed-amd',dl380:'mixed-intel',dl385:'all-sff'};body=rack(2,(x,y,w,h)=>group2(x,y,w,h,kinds[key]));label=`HPE ${key.toUpperCase()} 2U front, three configurable cages in the documented layout`;
 }else if(key==='sy480'){
  // Installed orientation is upright. The side cover makes the blade's 600 mm depth legible.
  body=`<path d="M98 13L264 26V151L98 178Z" fill="${metal}" stroke="#b6c0c0" stroke-width=".8"/><path d="M57 12L224 21L264 26L98 13Z" fill="#bcc7c6" stroke="#8c9999" stroke-width=".6"/><path d="M104 19L258 30V146L104 171Z" fill="#9ba7a7" stroke="#d0d7d4" stroke-width=".65"/><path d="M108 26L251 35M110 162L251 141" stroke="#748486" stroke-width=".6"/>`+rect(53,12,47,165,'#1b2428','#b0bdbe',1.2)+rect(53,12,10,165,'#1b2226','#99a7ab')+bank(68,22,26,56,2)+vent(68,82,26,24)+bank(68,111,26,57,2)+logo(54.5,18,6)+led(58,31,'#6eb4d1',1)+led(58,37)+led(58,43)+rect(54,62,7,68,'#aebabb','#617276',1.4)+rect(55.5,70,4,51,'#34454b','#647779')+rect(55,149,5,14,'#d3dddd','#7f9297')+rect(110,80,3,15,'#476b91','#657c91')+`<path d="M69 15h25v4H69M69 170h25v4H69" fill="#b9c5c5" stroke="#7c8b8d" stroke-width=".6"/>`;
  body+=`<g transform="translate(280 104) scale(.35)">${frame(0,0,176,164,true)}</g><text x="311" y="177" text-anchor="middle" fill="#b6c6cf" font-size="10" font-family="monospace">FRAME</text>`;label='Synergy 480 Gen12 upright half-height blade, four vertical SFF drives in two pairs, long side cover; small Synergy frame shows installation context';
 }else if(key==='dl580'){
  body=rack(4,(x,y,w,h)=>{const cw=(w-4)/3,rh=(h-3)/2;return vent(x,y,cw,rh)+vent(x+cw+2,y,cw,rh)+bank(x+2*(cw+2),y,cw,rh,8)+boot(x,y+rh+3,cw,rh)+vent(x+cw+2,y+rh+3,cw,rh)+bank(x+2*(cw+2),y+rh+3,cw,rh,12,1,false,true)+rect(x+6,y+6,cw-12,3,'#1b2529','#69777b');});label='DL580 Gen12 4U, two rows of three front cages; 8 SFF above 12 EDSFF at right';
 }else if(key==='dl380a'){
  body=rack(4,(x,y,w,h)=>vent(x,y,w,h*.73)+group1(x,y+h*.79,w,h*.21,'edsff'));label='DL380a Gen12 4U, large upper GPU airflow panel and lower EDSFF storage band with center boot cage';
 }else if(key==='xd685'){
  body=rack(5,(x,y,w,h)=>{let b=rect(x,y,w,h,'#a1abad','#d4d9d7');for(let c=0;c<4;c++)b+=io(x+4+c*(w*.58/4),y+3,w*.135,h*.12,1);b+=vent(x+w*.6,y+3,w*.38,h*.2);b+=io(x+4,y+h*.17,w*.56,h*.09,1);b+=bank(x+4,y+h*.29,w*.57,h*.19,3,4,true,true)+io(x+w*.72,y+h*.29,w*.25,h*.19,2);b+=io(x+4,y+h*.51,w*.27,h*.1,1)+io(x+w*.73,y+h*.51,w*.25,h*.1,1);b+=vent(x+w*.27,y+h*.55,w*.47,h*.39);for(let c=0;c<4;c++){b+=io(x+7+c*10,y+h*.66,8,h*.26,1)+io(x+w-48+c*10,y+h*.66,8,h*.26,1);}b+=led(x+w*.47,y+h*.965)+led(x+w*.51,y+h*.965,'#7db5db');return b;});label='XD685 5U direct-liquid-cooled front, silver modular IO sections, 12 E3.S example cage, lower GPU-attached PCIe slots';
 }else if(key==='xd690'){
  body=rack(10,(x,y,w,h)=>{let b='';const ph=h*.18;for(let r=0;r<2;r++)for(let c=0;c<6;c++){let xx=x+c*w/6,yy=y+r*ph/2;b+=rect(xx,yy,w/6-1,ph/2-1,'#444e52','#98a3a4')+`<circle cx="${xx+w/12}" cy="${yy+ph/4}" r="${ph*.19}" fill="#111a1e" stroke="#828f94" stroke-width=".6"/>`+led(xx+w/6-3,yy+ph/4,'#dbcf67',.9);}b+=vent(x,y+ph+2,w,h*.54);const ny=y+h*.75;for(let c=0;c<4;c++){b+=rect(x+c*w*.08+1,ny,w*.075-2,h*.035,'#0c171d','#9ba8ac')+rect(x+w*.68+c*w*.08+1,ny,w*.075-2,h*.035,'#0c171d','#9ba8ac');}b+=vent(x+w*.34,ny,w*.32,h*.035);b+=vent(x,ny+h*.05,w*.32,h*.13)+bank(x+w*.34,ny+h*.05,w*.32,h*.13,8,1,false,true)+vent(x+w*.68,ny+h*.05,w*.32,h*.13);b+=vent(x,y+h*.94,w*.49,h*.06)+io(x+w*.51,y+h*.94,w*.49,h*.06,1);return b;});label='XD690 10U front: twelve power-supply fan faces at top, large GPU sled grille, eight OSFP ports and lower CPU sled with eight E1.S drives';
 }else if(key==='dl585a'){
  body=rack(10,(x,y,w,h)=>{let b=bank(x,y,w,h*.11,4,4,true,true);b+=io(x,y+h*.125,w*.3,h*.12,2)+boot(x+w*.32,y+h*.125,w*.36,h*.12)+io(x+w*.7,y+h*.125,w*.3,h*.12,2);b+=vent(x,y+h*.26,w*.31,h*.055)+io(x+w*.34,y+h*.26,w*.32,h*.055,1)+vent(x+w*.69,y+h*.26,w*.31,h*.055);b+=rect(x,y+h*.33,w,h*.28,'#20292d','#636f73')+logo(x+w*.42,y+h*.34,w*.16);for(let i=0;i<8;i++)b+=io(x+3+i*(w-6)/8,y+h*.62,(w-6)/8-2,h*.28,1);b+=vent(x,y+h*.92,w,h*.08);return b;});label='DL585a Gen13 10U front: upper drive and IO cages, broad center shroud, lower eight double-width GPU positions';
 }else if(key==='ml350'){
  // Stabilizing feet omitted for a clean tower silhouette.
  body=`<path d="M199 25l44-13v149l-44 13z" fill="${metal}" stroke="#8c9da1" stroke-width=".7"/><path d="M127 25l44-13h72l-44 13z" fill="#b6c1c2" stroke="#a8b6b9" stroke-width=".7"/><g transform="translate(0 11) scale(1 .94)">`+rect(127,15,72,159,'#a6b1b3','#d2d9d7',1.5)+vent(133,21,60,13)+bank(133,40,60,37,4)+boot(133,81,60,10)+bank(133,98,60,30,8)+vent(133,132,60,7)+bank(133,144,60,25,12,1,false,true)+logo(179,24,8)+led(189,30)+'</g>';label='ML350 Gen12 tower without bezel: three stacked front cages, shown as 4 LFF, 8 SFF and 12 EDSFF, with a clean chassis base';
 }else if(key==='dl145'){
  body=`<path d="M54 70L115 38H299L306 70Z" fill="#465154" stroke="#7d8d92"/><path d="M306 70L299 38V96L306 119Z" fill="#263337" stroke="#536b71"/>`+rect(54,70,252,49,'#1c262b','#788b91',3)+rect(57,73,14,43,'#10191e','#566c74')+rect(288,73,14,43,'#10191e','#566c74');for(let i=0;i<31;i++)body+=`<path d="M${76+i*6.6} 77l-2 33" stroke="#607278" stroke-width="2.3"/>`;body+=logo(163,91,32);label='DL145 Gen11 compact 2U edge chassis with fitted filter bezel, central HPE badge and two carry handles';
 }else if(key==='xd245'||key==='xd285'){
  const rows=key==='xd245'?2:1;body=rect(31,58,298,66,'#243137','#94a5ac',2);for(let r=0;r<rows;r++)for(let c=0;c<2;c++){const x=37+c*145,y=64+r*(54/rows);body+=rect(x,y,140,50/rows,'#151f24','#687e88',1)+`<text x="${x+70}" y="${y+27/rows+2}" text-anchor="middle" fill="#a9bac3" font-size="9" font-family="monospace">NODE ${r*2+c+1}</text>`;}body+=`<text x="180" y="146" text-anchor="middle" fill="#93a8b4" font-size="9" font-family="monospace">HALF-WIDTH NODE LAYOUT · SCHEMATIC</text>`;label=`${key.toUpperCase()} ${rows*2} half-width nodes in shared OCP chassis; node layout schematic, exact front panel not verified`;
 }
 return `<svg viewBox="0 0 360 190" role="img" aria-label="${label}"><defs><linearGradient id="${uid}-metal" x2=".4" y2="1"><stop stop-color="#d1d9d7"/><stop offset=".46" stop-color="#9facae"/><stop offset="1" stop-color="#62777d"/></linearGradient><pattern id="${uid}-mesh" width="3" height="3" patternUnits="userSpaceOnUse"><rect width="3" height="3" fill="#68787d"/><rect x=".5" y=".5" width="2" height="2" rx=".25" fill="#111b20"/></pattern></defs>${body}</svg>`;
}
// END hardware
// BEGIN architecture
function architecture(){
 let svg='<defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".65" fill="#45614c" opacity=".45"/></pattern></defs><rect width="1000" height="540" fill="#0a1911"/><rect width="1000" height="540" fill="url(#grid)"/>';
 const box=(x,y,w,h,label)=>`<rect class="enclosure" x="${x}" y="${y}" width="${w}" height="${h}" rx="12"/><text class="tiny" x="${x+20}" y="${y+25}">${label}</text>`;
 if(state.mode==='rack'){
  svg+='<path class="trace management" d="M227 113V161H217v51"/><path class="trace" d="M745 108v104"/>';
  svg+=node('com',75,49,303,64,'Compute Ops Management','Cloud fleet operations');svg+=node('network',590,49,310,59,'External Ethernet network','Workload traffic');
  svg+=box(75,168,825,328,'PROLIANT DL380 GEN12 · 2U CHASSIS · COMPONENT GROUPS');
  svg+='<text class="tiny" x="866" y="191" text-anchor="end">REAR ↑</text>';
  svg+='<path class="trace" d="M745 264v27H574v22M270 340h42M637 340h40M370 367v33h-53v28M574 367v33h138v28"/>';
  svg+=node('ilo',112,212,210,52,'iLO 7','Embedded management');svg+=node('nic',640,212,210,52,'NIC / OCP adapter','Network I/O');
  svg+=node('ram',126,313,144,54,'DDR5 DIMMs','CPU 1 memory');svg+=node('cpu',312,313,117,54,'CPU 1','Intel Xeon 6');svg+=node('cpu',512,313,125,54,'CPU 2','Optional socket');svg+=node('ram',677,313,173,54,'DDR5 DIMMs','CPU 2 memory');
  svg+='<path class="trace" d="M429 340h83"/>';
  svg+=node('drives',112,428,410,45,'Front drive bays','SFF / LFF / E3.S variants');svg+=node('pcie',573,428,277,45,'PCIe expansion','Qualified GPUs & adapters');
  svg+='<text class="tiny" x="75" y="523">FRONT ↓ · COUNTS AND ROUTING SIMPLIFIED · CHOOSE A COMPONENT</text>';
 }else if(state.mode==='synergy'){
  svg+=node('network',600,37,300,58,'External network / storage','Workload connections');
  svg+=box(75,132,850,372,'SYNERGY 12000 FRAME · 10U · FRONT AND REAR EXPANDED');
  svg+=node('frame',820,142,82,28,'', '',{content:'<text x="861" y="161" text-anchor="middle" class="sublabel">Inspect</text>'});
  svg+='<text class="tiny" x="110" y="199">FRONT · UP TO 12 HALF-HEIGHT NODES</text><text class="tiny" x="585" y="199">REAR · SHARED INFRASTRUCTURE</text>';
  svg+='<path class="trace" d="M750 95v29h-85v105M750 124h79v105M465 300h80v4h120v-21M545 304h284v-21"/><path class="trace management" d="M154 408v22h588v-38"/>';
  svg+=node('composer',110,226,88,182,'','',{aria:'Synergy Composer management appliance',content:'<text x="154" y="294" text-anchor="middle" class="sublabel">Composer</text><text x="154" y="314" text-anchor="middle" class="sublabel">OneView</text><path d="M130 338h48M130 344h48M130 350h48" stroke="#789779"/>'});
  for(let row=0;row<2;row++)for(let col=0;col<6;col++){const x=214+col*43,y=226+row*95,n=row*6+col+1;svg+=node('blade',x,y,36,86,'','',{aria:'Synergy compute module '+n,content:`<text x="${x+18}" y="${y+23}" text-anchor="middle" class="sublabel">${String(n).padStart(2,'0')}</text><path d="M${x+7} ${y+35}h22v20h-22zM${x+7} ${y+65}h22" fill="#0c1b12" stroke="#6d9276"/>`});}
  svg+=node('interconnect',585,229,160,54,'Interconnect A','Workload fabric');svg+=node('interconnect',758,229,142,54,'Interconnect B','Redundant peer');
  svg+=node('flm',585,338,315,54,'Frame Link Modules','Management connectivity');
  svg+=node('shared',110,452,790,29,'','',{content:'<text x="505" y="471" text-anchor="middle" class="sublabel">SHARED POWER & COOLING · REAR FAN / POWER-SUPPLY BAYS</text>'});
  svg+='<text class="tiny" x="75" y="527">REAR: TWO OF SIX INTERCONNECT BAYS SHOWN · MANAGEMENT AND DATA PATHS DIFFER</text>';
 }else{
  svg+=node('network',586,31,314,56,'Cluster network / storage','Connect to other systems');
  svg+=box(75,132,825,368,'PROLIANT COMPUTE XD685 · 5U LIQUID / 6U AIR · LOGICAL CUTAWAY');
  svg+='<path class="trace" d="M743 87v111M585 227H417M720 254v37M264 254v20H96v186h14"/>';
  svg+=node('host',110,198,307,56,'2 × AMD EPYC + DDR5','Host processors and system RAM');svg+=node('aiio',585,198,270,56,'High-speed adapters','GPU-attached / fabric slots');
  svg+='<rect x="109" y="291" width="747" height="123" rx="9" fill="#0b2013" stroke="#46704b" stroke-dasharray="5 4"/>';
  for(let i=0;i<8;i++)svg+=node('gpu',122+i*91,311,80,76,'','',{aria:'Accelerator '+(i+1)+' in the eight-GPU subsystem',content:`<text x="${162+i*91}" y="341" text-anchor="middle" class="label">GPU ${i+1}</text><text x="${162+i*91}" y="364" text-anchor="middle" class="sublabel">+ HBM</text>`});
  svg+=node('aistorage',110,439,307,42,'E3.S NVMe + M.2 boot');svg+=node('cooling',459,439,396,42,'Cooling matched to GPU configuration');
  svg+='<text class="tiny" x="75" y="523">ONE QUALIFIED GPU PLATFORM PER SYSTEM · ACCELERATOR LINKS NOT DRAWN</text>';
 }
 $('#diagramMount').innerHTML=`<svg class="diagram" viewBox="0 0 1000 540" role="group" aria-label="Interactive HPE ${state.mode} architecture schematic">${svg}</svg>`;
 const blurbs={rack:'<b>A self-contained server:</b> CPUs, memory, storage and adapters live in one chassis. iLO handles individual-server management; Compute Ops Management adds fleet operations. Internal lines are conceptual connections, not a motherboard wiring diagram.',synergy:'<b>A shared frame:</b> twelve half-height compute bays sit at the front. Interconnects, power and cooling sit at the rear. Composer runs OneView; Frame Link Modules provide management connectivity. Front and rear are expanded side by side below.',ai:'<b>An eight-GPU system:</b> host CPUs, local flash and network adapters support an integrated accelerator subsystem. NVIDIA and AMD options use different qualified builds. GPU memory is separate from CPU memory; the drawing does not imply a universal interconnect topology.'};
 $('#diagramBlurb').innerHTML=blurbs[state.mode];$$('#modeSwitch button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode)));
 const ids=$$('[data-concept]',$('#diagramMount')).map(n=>n.dataset.concept);if(!ids.includes(state.concept))state.concept={rack:'cpu',synergy:'frame',ai:'gpu'}[state.mode];setConcept(state.concept);
}
// END architecture
// BEGIN overview
function overview(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">AN INTERACTIVE GUIDE TO HPE COMPUTE</div><h1>Know the families.<br><em>See what fits.</em></h1><p>From a branch-office tower to an eight-GPU AI system. Discover what HPE builds, how the pieces connect, and where AMD and Intel fit.</p><div class="button-row"><a class="btn primary" href="#lineup">Explore the servers <span>↗</span></a><button class="btn ghost" data-scroll="systemMap">Take the system tour <span>↓</span></button></div><div class="source-note">Based on ${sourceLink('catalog','HPE ProLiant Compute')} and ${sourceLink('frame','HPE Synergy 12000 Frame QuickSpecs')}.<br>Selected Gen10 Plus / Gen11 / Gen12 / XD systems and announced Gen13 platforms · reviewed 09 Oct 2026.</div></div><div class="hero-art"><div class="hero-stack">${hardware('portfolio',true)}</div><div class="art-label">PROLIANT · ILLUSTRATIVE FRONT VIEWS</div></div></section>
 <div class="chapter-heading"><h2>Find your way around the families</h2><span class="small">Start with the physical shape.</span></div><section class="family-grid hpe-families" aria-label="HPE hardware families">
 ${[['Rack','01 / RACK SERVERS','rack2','ProLiant DL','Self-contained servers, from 1U compute to expandable 2U and four-socket systems.','Intel Xeon + AMD EPYC'],['Modular','02 / MODULAR SYSTEMS','frame','Synergy','Compute modules share a frame, power, cooling and interconnect infrastructure.','Intel Xeon in 480 Gen12'],['Tower','03 / TOWER SERVERS','tower','ProLiant ML','Expandable local compute for businesses, offices and distributed sites.','Intel Xeon in ML350 Gen12'],['Edge','04 / COMPACT EDGE','edge','ProLiant DL145','Short-depth compute built for locations outside a traditional data center.','AMD EPYC 8004 / 8005'],['AI','05 / ACCELERATED RACK','gpu4','DL380a','A rack server designed around multiple plug-in GPU accelerators.','Intel host CPU + NVIDIA GPUs'],['AI','06 / DENSE GPU SYSTEMS','gpu6','Compute XD','Integrated multi-GPU systems for large AI models and intensive computation.','AMD or Intel host platforms']].map(([family,num,shape,title,desc,chip])=>`<button class="family-card" data-family="${family}"><span class="over">${num}</span><span class="arrow">↗</span><div class="hardware">${hardware(shape)}</div><h3>${title}</h3><p>${desc}</p><div class="chip-row"><span class="badge">${chip}</span></div></button>`).join('')}</section>
 <section class="two-col section"><article class="lesson"><div class="eyebrow">READ THE NAME</div><h3 style="margin-top:12px">HPE ProLiant DL325 Gen12</h3><div class="name-decoder"><div class="name-piece">DL<small>Rack family</small></div><div class="name-piece">325<small>Model</small></div><div class="name-piece">Gen12<small>HPE generation</small></div></div><p>Keep three separate questions in mind: which family, which model, and which generation? Then look up the processor options. “Gen12” does not mean a twelfth-generation CPU.</p>${sourceLink('dl325','See the complete model specification')}</article><article class="lesson"><div class="eyebrow">A USEFUL STARTING MAP</div><h3 style="margin-top:12px">Shape → sockets → options</h3><p><b>1U / 2U</b> describes rack height. <b>1P / 2P</b> describes CPU socket count. A <b>tower</b> stands vertically. A <b>compute module</b> needs a compatible frame.</p><p>For this DL300 set, DL320 / 325 are 1U single-socket; DL340 / 345 are 2U single-socket. DL360 / 365 and DL380 / 385 are two-socket designs. Use this as a guide to these models, not a universal naming rule.</p><a href="#platforms">See the AMD / Intel map →</a></article></section>
 <section class="panel section" id="systemMap"><div class="panel-head"><div><div class="eyebrow">THE SYSTEM, CONNECTED</div><h2 style="margin-top:8px">Three designs. Different ways to build.</h2><p>Choose a system. Select a part to learn what it does.</p></div><div class="segmented" id="modeSwitch" aria-label="HPE system mode"><button data-mode="rack" aria-pressed="true">ProLiant rack</button><button data-mode="synergy" aria-pressed="false">Synergy</button><button data-mode="ai" aria-pressed="false">XD GPU system</button></div></div><div id="diagramBlurb" class="diagram-notes"></div><div class="diagram-scroll" id="diagramMount"></div><div class="diagram-legend"><div class="legend-items"><span><i class="legend-dot"></i>System / data connection</span><span><i class="legend-dot" style="background:var(--purple)"></i>Management</span></div><span>Logical schematic · placement simplified · pan on mobile</span></div><div class="detail-panel" id="partDetail" aria-live="polite"></div></section>
 <details class="system-key"><summary>Diagram key: iLO, DIMM, NIC, OCP, PCIe, HBM</summary><p>iLO = Integrated Lights-Out management; DIMM = memory module; NIC = network adapter; OCP = adapter form factor here; PCIe = expansion connection; HBM = GPU-local high-bandwidth memory.</p></details>
 <div class="takeaway"><span class="symbol">↳</span><div><h3>HPE is a portfolio, with several management layers.</h3><p>A ProLiant server can stand alone. Synergy is built around a shared frame. An XD GPU system has its own platform rules. The name “HPE” alone does not establish a common chassis or management design.</p></div></div>
 <section class="section panel panel-pad"><div class="eyebrow">MANAGEMENT, DECODED</div><h2 style="margin-top:10px">One server. A fleet. A composed system.</h2><div class="three-col"><article><h3>iLO</h3><p class="small muted">Embedded control for supported individual servers: health, power, firmware and remote administration. Gen11 examples here use iLO 6; Gen12 examples use iLO 7. Announced Gen13 platforms introduce iLO 8.</p>${sourceLink('dl380','iLO in DL380 Gen12')} · ${sourceLink('hpeGen13','Announced iLO 8 in Gen13')}</article><article><h3>Compute Ops Management</h3><p class="small muted">Cloud operations across supported servers. It organizes inventory, firmware and lifecycle tasks through a fleet view.</p>${sourceLink('com','Fleet management QuickSpecs')}</article><article><h3>OneView & Composer</h3><p class="small muted">Profiles and templates for infrastructure. In Synergy, Composer is the appliance running OneView, coordinating the shared frame and its resources.</p>${sourceLink('frame','Synergy management architecture')}</article></div><p class="small muted">These tools do not run your virtual machines. The installed operating system or hypervisor runs the workload. XD690 has its own BMC; do not assume every HPE server uses iLO.</p></section>
 <div class="next-lesson"><p>Next: explore the actual models and compare their options.</p><a class="btn primary" href="#lineup">Explore the lineup →</a></div>`;}
// END overview
// BEGIN lineup
function lineup(){return `${intro('02 / THE HARDWARE EXPLORER','A server for each kind of job.','Explore '+models.length+' representative HPE platforms. Filter by family, host CPU or workload, then open a profile or compare up to three models.')}
 <div class="filterbar"><div class="filter search"><label for="modelSearch">SEARCH THE LINEUP</label><input id="modelSearch" type="search" placeholder="Try DL385, EPYC, E3.S, MI355X…" value="${esc(state.filters.q)}"></div><div class="filter"><label for="familyFilter">FAMILY</label><select id="familyFilter">${selectOptions(['All','Rack','Modular','Tower','Edge','AI'],state.filters.family)}</select></div><div class="filter"><label for="vendorFilter">HOST CPU</label><select id="vendorFilter">${selectOptions(['All','AMD','Intel'],state.filters.vendor)}</select></div><div class="filter"><label for="useFilter">WORKLOAD</label><select id="useFilter">${selectOptions(['All','General compute','Virtualization','Data & storage','AI & GPUs','Edge & branch'],state.filters.use)}</select></div></div><div class="results-info"><p id="modelCount" aria-live="polite"></p><button class="text-btn" data-reset-filters>Reset filters ↻</button></div><div class="model-grid" id="modelGrid"></div><div class="compare-tray" id="compareTray" hidden><p id="compareStatus" aria-live="polite"></p><div class="button-row"><button class="btn compact ghost" data-clear-compare>Clear</button><button class="btn compact primary" id="compareButton" data-compare>Compare selected →</button></div></div>
 <div class="warning"><strong>Read “up to” as a configuration ceiling.</strong> Highest drive, GPU, CPU and memory values may require different builds. Workload filters are learning aids, not performance benchmarks or certified solution recommendations.</div>
 <section class="section" id="history"><h2>Where the rest of the portfolio fits</h2><div class="history-list"><article><span class="badge accent">MORE MAINSTREAM CHOICES</span><h3 style="margin-top:16px">Smaller towers & other generations</h3><p>ML110, ML30 and MicroServer serve other tower and small-site needs. Gen10, Gen10 Plus and other Gen11 / Gen12 models may appear in existing estates. Keep the full generation name when checking options and support.</p>${sourceLink('catalog','Explore HPE’s broader catalog')}</article><article><span class="badge accent">SPECIALIZED COMPUTE</span><h3 style="margin-top:16px">Arm, scale-out & supercomputing</h3><p>HPE’s compute portfolio extends beyond the AMD / Intel models profiled here, including NVIDIA CPU-based designs and specialized AI / supercomputing systems. The model explorer is a curated starting set, not the entire offering.</p>${sourceLink('ai','Explore the broader AI portfolio')}</article></div><div class="lesson" style="margin-top:16px"><h3>A generation label is not an end-of-support date.</h3><p>Older systems can remain in service. Support depends on the exact product, option, software release and service entitlement. This guide does not label an entire HPE generation as obsolete.</p><p class="hpe-scope">Profiles cover selected Gen11 / Gen12 / XD systems and four announced Gen13 platforms. Gen13 records use launch evidence and planned availability; incomplete qualification is labeled explicitly.</p></div></section><div class="next-lesson"><p>Next: separate the CPU choice from the rest of the system.</p><a class="btn primary" href="#platforms">AMD & Intel →</a></div>`;}
// END lineup
// BEGIN platforms
function platforms(){return `${intro('03 / TWO CPU ECOSYSTEMS','AMD or Intel? Follow the model.','HPE offers both across several server types. Socket count, CPU family and server generation are separate axes—and GPU support is a separate qualification.')}
 <div class="two-col"><article class="vendor-panel amd"><span class="badge amd">AMD CPU PLATFORMS</span><h2>EPYC</h2><p>The AMD set includes single-socket and dual-socket rack servers, edge systems and integrated GPU systems.</p><ul><li><b>DL325 / DL345 Gen12:</b> one EPYC 9005.</li><li><b>DL365 / DL385 Gen11:</b> up to two qualified EPYC 9004 or 9005.</li><li><b>DL145 Gen11:</b> one EPYC 8004 / 8005.</li><li><b>XD685:</b> two EPYC 9005 host processors.</li><li><b>Announced Gen13:</b> EPYC 9006 in DL525, DL585a and multi-node XD245 / XD285. Planned availability spans late 2026–2027.</li></ul>${modelButtons(['dl325','dl345','dl365','dl385','dl145','xd685','dl525','dl585a','xd245','xd285'])}<p class="small">The processor family’s maximum is not necessarily the server’s maximum. For example, the documented DL365 / DL385 CPU list differs from DL325 / DL345.</p></article><article class="vendor-panel intel"><span class="badge intel">INTEL CPU PLATFORMS</span><h2>Xeon</h2><p>Intel Xeon 6 spans rack, tower, Synergy and dedicated GPU platforms in this guide.</p><ul><li><b>DL320 / DL340:</b> one socket.</li><li><b>DL360 / DL380:</b> up to two sockets.</li><li><b>DL580:</b> up to four sockets.</li><li><b>ML350 / Synergy 480:</b> up to two sockets.</li><li><b>DL380a / XD690:</b> two host processors.</li></ul>${modelButtons(['dl320','dl380','dl580','ml350','sy480','xd690'])}<p class="small">P-core and E-core options are not interchangeable promises. Read the exact CPU list; some models use only qualified P-core processors.</p></article></div>
 <div class="takeaway"><span class="symbol">≠</span><div><h3>CPU brand does not determine GPU brand.</h3><p>XD685 uses AMD host CPUs with qualified AMD Instinct or NVIDIA accelerator platforms. DL380a and XD690 pair Intel host CPUs with NVIDIA GPUs. These examples do not establish support on every server from the same CPU vendor.</p></div></div>
 <section class="section"><div class="chapter-heading"><h2>The practical platform map</h2><span class="small">Select any model to see its evidence.</span></div><div class="table-scroll"><table><caption class="visually-hidden">HPE form factor and socket count by CPU vendor</caption><thead><tr><th scope="col">Design</th><th scope="col">AMD examples</th><th scope="col">Intel examples</th></tr></thead><tbody>${[['1U · single socket',['dl325'],['dl320']],['2U · single socket',['dl345'],['dl340']],['1U · two sockets',['dl365'],['dl360']],['2U · two sockets',['dl385'],['dl380']],['Four-socket scale-up',[],['dl580']],['Synergy modular',[],['sy480']],['Expandable tower',[],['ml350']],['Compact edge',['dl145'],[]],['Integrated eight-GPU AI',['xd685'],['xd690']]].map(([label,a,b])=>`<tr><th scope="row">${label}</th><td>${a.length?modelButtons(a):'<span class="support-none">No example in this guide</span>'}</td><td>${b.length?modelButtons(b):'<span class="support-none">No example in this guide</span>'}</td></tr>`).join('')}</tbody></table></div><p class="matrix-note">Selected models only. An empty cell is not a statement that HPE can never support that vendor or form factor. The paired models can differ in features and generation; this is not a performance ranking.</p></section>
 <section class="section two-col"><article class="lesson"><div class="eyebrow">A BETTER COMPARISON</div><h3>Start with the workload’s constraints.</h3><p>A virtual-machine host may run out of RAM before it runs out of cores. A licensed database may care about per-core cost. A GPU workload may care more about accelerator memory and interconnects than host CPU brand.</p><p>Compare measured application performance, memory capacity and bandwidth, local storage, network I/O, power, cooling and software support.</p></article><article class="lesson"><div class="eyebrow">SOFTWARE IS ANOTHER LAYER</div><h3>What runs on an HPE server?</h3><p>Supported Windows Server, Linux and virtualization releases depend on the model and configuration. The hardware, firmware, drivers and OS / hypervisor must form a supported combination.</p><p>iLO and Compute Ops Management administer the server. They are not the guest-VM hypervisor or the storage software.</p>${sourceLink('os','HPE Servers Support & Certification Matrices')}</article></section><div class="next-lesson"><p>Next: understand the drives and accelerators.</p><a class="btn primary" href="#components">Storage & GPUs →</a></div>`;}
// END platforms
// BEGIN driveLessons
const driveLessons={
 sff:{label:'2.5-inch SFF',art:'',title:'A drive shape, not a protocol.',text:'Small-form-factor bays commonly hold 2.5-inch drives. A supported cage might accept SAS, SATA or NVMe options. The carrier, backplane and controller decide what actually works.',notice:'Synergy 480 Gen12 has 4-SFF cage options. Direct-connect NVMe and controller-connected SAS / SATA / NVMe cages follow different rules.',ids:['sy480','dl380','dl345'],source:'sy480'},
 lff:{label:'3.5-inch LFF',art:'lff',title:'Larger bays for capacity-oriented storage.',text:'Large-form-factor bays commonly hold 3.5-inch hard drives. Drive count, drive capacity and usable RAID capacity are three different quantities.',notice:'DL345 Gen12 offers an LFF configuration with up to twelve drives. That is a different build from the high-density E3.S or GPU chassis.',ids:['dl345','dl340','ml350'],source:'dl345'},
 e3:{label:'E3.S NVMe',art:'e3',title:'Enterprise flash in a purpose-built carrier.',text:'E3.S belongs to the EDSFF family of enterprise SSD shapes. NVMe is its storage protocol. E3.S requires the correct cage and connections; it is not a drop-in 2.5-inch substitute.',notice:'DL325 Gen12 lists up to 20 E3.S; DL345 Gen12 up to 36; Synergy 480 Gen12 up to eight. These are separate model-specific configurations.',ids:['dl325','dl345','sy480'],source:'dl325'},
 e1:{label:'E1.S NVMe',art:'e1',title:'A different enterprise SSD format.',text:'E1.S and E3.S are different physical sizes. Both can use NVMe, but their carriers and cooling arrangements are not interchangeable.',notice:'Compute XD690 lists eight E1.S NVMe bays. XD685 uses E3.S instead. Similar system names do not guarantee the same storage parts.',ids:['xd690','xd685'],source:'xd690'},
 m2:{label:'M.2 boot',art:'m2',title:'Separate the boot device from the data drives.',text:'Small M.2 SSDs can hold the operating system while the main bays hold workload data. Model-specific HPE boot devices can mirror a pair of drives, but the device suffix and support matrix matter.',notice:'Synergy 480 Gen12 offers the NS204i-d v2 with two M.2 NVMe drives for hardware RAID boot. Rack and edge examples can use different NS204i-u devices.',ids:['sy480','dl325','dl145'],source:'boot'}
};
// END driveLessons
// BEGIN components
function components(){return `${intro('04 / UNDER THE COVER','Decode storage. Understand GPUs.','Separate physical form, connection protocol and platform support. A familiar acronym is only one part of a supported configuration.')}
 <section class="panel"><div class="panel-head"><div><div class="eyebrow">STORAGE EXPLORER</div><h2 style="margin-top:8px">What does the drive label tell you?</h2><p>Select a format to see how HPE uses it.</p></div><span class="badge accent">FORM ≠ PROTOCOL</span></div><div class="storage-lab"><div class="lab-controls" aria-label="Drive formats">${Object.entries(driveLessons).map(([id,d])=>`<button data-drive="${id}" aria-pressed="${state.drive===id}">${d.label}</button>`).join('')}</div><div class="lab-content" id="driveLesson"></div></div></section>
 <div class="two-col section"><article class="lesson"><h3>Backplanes, controllers and boot devices.</h3><p>The backplane connects the drive bays. A RAID controller can organize drives into arrays. A direct connection or passthrough arrangement may let software manage drives differently.</p><p>HPE model documents list controller and cage combinations. A specification mentioning SAS, SATA and NVMe does not mean any drive will work in any front bay.</p>${sourceLink('sy480','An example: Synergy drive-cage choices')}</article><article class="lesson"><h3>Three different places to keep data.</h3><p><b>CPU RAM:</b> the host’s active working space.<br><b>GPU memory:</b> the accelerator’s working space.<br><b>Drives:</b> persistent software and data storage.</p><p>Adding SSDs does not increase GPU memory. Adding DIMMs does not change the memory physically attached to an accelerator.</p><a href="#sources/glossary">Open the glossary →</a></article></div>
 <section class="section"><div class="chapter-heading"><h2>Three ways to add acceleration</h2><span class="small">Different physical and thermal designs.</span></div><div class="three-col"><article class="lesson"><div class="big-number">01</div><h3>GPUs in a general server</h3><p>A qualified PCIe GPU can add inference, graphics or compute capability to a rack, tower or edge server. The right slot is only part of the requirement.</p>${modelButtons(['dl385','ml350','dl145'])}<p class="small muted">DL145 supports small NVIDIA L4 cards or specific larger-GPU builds; cooling and temperature limits change with the choice.</p>${sourceLink('dl145','DL145 GPU and thermal rules')}</article><article class="lesson"><div class="big-number">02</div><h3>A GPU-focused rack chassis</h3><p>DL380a Gen12 gives accelerators more space, power and cooling in a dedicated 4U design. It uses qualified PCIe GPUs.</p>${modelButtons(['dl380a'])}<p class="small muted">Its headline maximum is up to ten double-wide GPUs. The valid count depends on the accelerator and the system configuration.</p>${sourceLink('dl380a','DL380a platform rules')}</article><article class="lesson"><div class="big-number">03</div><h3>An integrated eight-GPU system</h3><p>XD685 and XD690 are built around accelerator subsystems. Specialized GPU modules and their links differ from ordinary plug-in PCIe cards.</p>${modelButtons(['xd685','xd690'])}<p class="small muted">XD685 has NVIDIA and AMD builds. XD690 combines Intel host CPUs with NVIDIA HGX B300.</p>${sourceLink('xd685','XD685 GPU and cooling options')}</article></div></section>
 <section class="panel section"><div class="panel-head"><div><div class="eyebrow">THE CPU / GPU CROSSOVER</div><h2 style="margin-top:8px">Documented pairings to remember</h2></div></div><div class="table-scroll" style="border:0;border-radius:0"><table><caption class="visually-hidden">Examples of supported host CPU and GPU ecosystems</caption><thead><tr><th scope="col">Host CPU</th><th scope="col">GPU example</th><th scope="col">Where it appears</th><th scope="col">The distinction</th></tr></thead><tbody><tr><th scope="row">AMD EPYC</th><td>NVIDIA PCIe / integrated GPUs</td><td>${modelButtons(['dl385','xd685'])}</td><td>AMD CPUs can host NVIDIA GPUs. The PCIe and integrated systems are different platforms.</td></tr><tr><th scope="row">AMD EPYC</th><td>AMD Instinct MI350P</td><td>${modelButtons(['dl385'])}</td><td>1–4 cards quotable now; shipment planned December 2026. Mandatory 450 W iLO GPU cap plus specified kits.</td></tr><tr><th scope="row">AMD EPYC</th><td>8 × AMD Instinct MI355X</td><td>${modelButtons(['xd685'])}</td><td>A direct-liquid-cooled accelerator system; not a GPU swap into an ordinary ProLiant.</td></tr><tr><th scope="row">Intel Xeon</th><td>NVIDIA PCIe / HGX B300</td><td>${modelButtons(['dl380a','xd690'])}</td><td>The host CPU brand is the same; GPU format and system layout differ.</td></tr><tr><th scope="row">Intel Xeon</th><td>AMD or Intel accelerators</td><td class="support-none">No pairing established in this selected set</td><td>This guide makes no platform-wide prohibition. Use the exact server’s current qualification list.</td></tr></tbody></table></div></section>
 <div class="warning"><strong>GPU names that sound similar can describe different hardware.</strong> MI350P is a PCIe card planned to ship in DL385 during December 2026, with a required 450 W cap; MI355X here is part of an eight-GPU DLC system. Likewise, a NVIDIA PCIe GPU and an HGX baseboard are not interchangeable. ${sourceLink('dl385','DL385 options')} · ${sourceLink('xd685','XD685 options')}</div>
 <section class="section"><h2>From an option to a supported system</h2><p class="muted">Read the model rules in this order.</p><div class="compat-steps"><article class="compat-step"><h3>Exact platform</h3><p>Full model, generation, CPU and chassis part number.</p></article><article class="compat-step"><h3>Population rules</h3><p>Memory, cages, risers, controllers, GPUs and adapters.</p></article><article class="compat-step"><h3>Power & cooling</h3><p>Fans, power supplies, ambient limits and liquid infrastructure.</p></article><article class="compat-step"><h3>Software support</h3><p>Firmware, drivers, OS, hypervisor and solution certification.</p></article></div><p class="source-note">Use the model’s QuickSpecs alongside ${sourceLink('os','HPE’s support and certification matrices')}.</p></section><div class="next-lesson"><p>Ready to connect the dots?</p><a class="btn primary" href="#quiz">Test your knowledge →</a></div>`;}
// END components
// BEGIN sourcesView
function sourcesView(){return `${intro('06 / KEEP LEARNING','Go straight to the evidence.','A source-linked snapshot reviewed on October 7, 2026. Hardware drawings are original simplified illustrations based on HPE’s product documentation.')}
 <div class="two-col"><article class="lesson"><h3>What this guide covers</h3><p>${models.length} representative models, including announced Gen13 platforms, rack / tower / edge / modular / AI designs, CPU platforms, drive formats, GPU pairings and management layers.</p><p>It is a learning map, not a complete current catalog, ordering configurator or support matrix. HPE’s broader catalog includes other models and generations. Every hardware profile links to its own evidence.</p></article><article class="lesson"><h3>Why model-level documents matter</h3><p>The XD685 portfolio overview lists up to 6 TB RAM. Its August 2026 QuickSpecs removes 256 GB DIMMs and gives a 3 TB limit; this guide uses that newer model-level qualification.</p><p>XD690 is described using its own BMC, rather than assuming iLO. Where no GPU option is established in the selected document, the guide says so instead of claiming universal incompatibility.</p>${sourceLink('xd685','XD685: Memory and Summary of Changes')}</article></div>
 <section class="section" id="glossary"><div class="eyebrow">PLAIN-ENGLISH REFERENCE</div><h2 style="margin-top:10px">Keep the acronyms under control.</h2><label class="visually-hidden" for="glossarySearch">Search glossary</label><input class="glossary-search" id="glossarySearch" type="search" placeholder="Find a term: iLO, NVMe, Synergy…"><div class="glossary" id="glossaryList">${Object.entries(glossary).map(([term,def])=>`<details data-term="${esc((term+' '+def).toLowerCase())}"><summary>${esc(term)}</summary><p>${def}</p></details>`).join('')}</div><p id="glossaryEmpty" class="muted" hidden>No matching terms. Try a shorter search.</p></section>
 <section class="section"><div class="eyebrow">OFFICIAL SOURCE LIBRARY</div><h2 style="margin-top:10px">Follow the document behind the detail.</h2><p class="muted small">Revision dates are shown when verified. “Reviewed” means this guide’s access date. Linked documents can change. QuickSpecs take priority over broad portfolio tables for exact options; no documents were supplied by the user.</p><div class="source-list">${Object.entries(sources).map(([id,s])=>`<article class="source-item" id="source-${id}">${sourceLink(id)}<p>${s.scope}</p><small>${s.date} · ${s.loc}</small></article>`).join('')}</div></section>`;}
// END sourcesView
