const sources={};
const doc=(id,title,url,scope,loc='Standard specifications; storage configurations; GPU adapters; systems management',date='Reviewed 07 Oct 2026')=>sources[id]={title,url,scope,loc,date};
const guide=(id,code,slug,title,scope)=>doc(id,title,`https://lenovopress.lenovo.com/${code}-${slug}`,scope);
doc('portfolio','Lenovo Servers and Storage Portfolio Guide','https://lenovopress.lenovo.com/lp1553-lenovo-servers-and-storage-portfolio-guide','ThinkSystem, ThinkEdge, ThinkAgile and the surrounding portfolio.','Rack, tower, edge, AI and solution portfolio sections');
doc('comparison','Lenovo ThinkSystem Server Comparison','https://lenovopress.lenovo.com/lp1263-lenovo-thinksystem-server-comparison','Broad model discovery and lifecycle context. Individual model guides take precedence.','Model columns; change history');
guide('sr630','lp1971','thinksystem-sr630-v4-server','ThinkSystem SR630 V4 Product Guide','1U Intel P-core / E-core choices, memory, E3.S and XCC3.');
sources.sr630.date='Updated 07 Oct 2026';
guide('sr650','lp2127','thinksystem-sr650-v4-server','ThinkSystem SR650 V4 Product Guide','2U Intel P-core platform, storage / GPU alternatives, Neptune Core and artwork reference.');
sources.sr650.loc='Figures 2–8; standard specifications; GPU adapters; cooling';sources.sr650.date='Updated 24 Sep 2026';
guide('sr635','lp1609','thinksystem-sr635-v3-server','ThinkSystem SR635 V3 Product Guide','Single-socket AMD 1U, 12 DIMMs and supported low-profile GPUs.');
guide('sr655','lp1610','thinksystem-sr655-v3-server','ThinkSystem SR655 V3 Product Guide','Single-socket AMD 2U, storage layouts and GPU rules.');
guide('sr645','lp1607','thinksystem-sr645-v3-server','ThinkSystem SR645 V3 Product Guide','Dual-socket AMD 1U, 24 DIMMs and storage / expansion tradeoffs.');
guide('sr665','lp1608','thinksystem-sr665-v3-server','ThinkSystem SR665 V3 Product Guide','Dual-socket AMD 2U, 6 TB memory, drive layouts and GPU qualification.');
guide('sr860','lp2231','thinksystem-sr860-v4-server','ThinkSystem SR860 V4 Product Guide','4U, two or four Intel CPUs, 16 TB memory and CXL / storage choices.');
guide('st45','lp1994','thinksystem-st45-v3-server','ThinkSystem ST45 V3 Product Guide','Entry AMD tower; 64 GB ECC UDIMM, non-hot-swap storage, no add-in GPU or integrated XCC.');
guide('st650','lp1604','thinksystem-st650-v3-server','ThinkSystem ST650 V3 Product Guide','Dual-socket Intel tower, storage and accelerator expansion.');
guide('se455','lp1724','thinkedge-se455-v3-server','ThinkEdge SE455 V3 / SE455i V3 Product Guide','AMD EPYC 8004 edge platform; front versus internal SSDs and slot-sharing rules.');
guide('se100','lp1995','lenovo-thinkedge-se100-server','ThinkEdge SE100 Product Guide','Core Ultra compact edge platform, M.2-only storage and qualified GPU options.');
guide('sd535','lp1892','thinksystem-sd535-v3-server','ThinkSystem SD535 V3 and D3 Chassis Product Guide','Four independent nodes in 2U; shared power, node-local fans, networking and XCC2.');
sources.sd535.loc='Figures 1–6; SD535 and D3 standard specifications; memory options';
guide('sc750','lp2009','thinksystem-sc750-v4-neptune-server','ThinkSystem SC750 V4 Neptune Product Guide','Direct-water-cooled Intel nodes, two per tray in N1380; per-node specifications.');
sources.sc750.loc='Standard specifications: SC750 tray / N1380 enclosure; internal storage; cooling';
guide('sr650a','lp2128','thinksystem-sr650a-v4-server','ThinkSystem SR650a V4 / SR650i V4 Product Guide','Front PCIe GPUs in 2U, inference configuration and power-capped GPU variants.');
guide('sr675','lp1611','thinksystem-sr675-v3-server','ThinkSystem SR675 V3 / SR675i V3 Product Guide','3U AMD GPU system; distinct PCIe / SXM shuttles, drive choices and Neptune hybrid cooling.');
guide('sr685a','lp1910','thinksystem-sr685a-v3-server','ThinkSystem SR685a V3 Product Guide — withdrawn','Existing-platform reference for AMD hosts with MI300X or NVIDIA HGX configurations.');
sources.sr685a.loc='Withdrawal notice / 26 Sep 2026 change history; standard specifications; GPU accelerators';sources.sr685a.date='Withdrawal documented 26 Sep 2026';
guide('sr680a','lp2264','thinksystem-sr680a-v4-server','ThinkSystem SR680a V4 Product Guide','8U air-cooled Xeon 6 / HGX B300 platform and original illustration references.');
sources.sr680a.loc='Figures 2–4; standard specifications; GPU accelerators; networking';
doc('gpu','ThinkSystem and ThinkAgile GPU Summary','https://lenovopress.lenovo.com/lp0768-thinksystem-thinkagile-gpu-summary','Accelerator formats, model compatibility and qualification footnotes.','GPU specifications and server support tables');
doc('xc1','Lenovo XClarity One Product Guide','https://lenovopress.lenovo.com/lp1992-lenovo-xclarity-one','Fleet management with cloud or on-premises portal and local management hubs.','Components; implementation options; supported endpoints','Updated 17 Jul 2026');
doc('os','Lenovo OS Interoperability Guide','https://lenovopress.lenovo.com/osig','Check the exact server, operating system / hypervisor release and support category.','Server and OS filters; configuration notes');
doc('proven','Lenovo ServerProven','https://serverproven.lenovo.com/','Hardware and software interoperability for exact machine types and options.','Server, adapter and software compatibility');
doc('sc777','ThinkSystem SC777 V4 Neptune Product Guide','https://lenovopress.lenovo.com/lp2048-thinksystem-sc777-v4','Arm-based NVIDIA Grace and Blackwell platform beyond the selected x86 profiles.','Introduction; standard specifications; N1380 enclosure');
doc('mx','ThinkAgile MX Solutions','https://lenovopress.lenovo.com/datasheet/ds0058-lenovothinkagile-mx-solutions','ThinkAgile MX combines Lenovo systems and Microsoft Azure Local.','Solution overview; specifications');

doc("faeMI210","AMD Instinct MI210 Accelerator Product Guide (withdrawn product)","https://lenovopress.lenovo.com/lp1862-amd-instinct-mi210-accelerator","Historical server qualification and required power kits; MI210 option withdrawn from marketing, not the host servers.","May 15 2026 change history; server support; auxiliary power cables","15 May 2026");
doc("faeSR675Rules","ThinkSystem SR675 V3 and SR675i V3 Servers: GPU configuration rules","https://lenovopress.lenovo.com/lp1611-thinksystem-sr675-v3-server","H200 C3V2/C3V3 and RTX PRO 6000 CBK8 require EPYC 9005 plus C5WW high-performance fan; MI210 historical shuttle options.","GPU adapters; configuration rules and field-upgrade requirements","Reviewed 09 Oct 2026");
doc("sd665","ThinkSystem SD665 V3 Neptune DWC Server Product Guide","https://lenovopress.lenovo.com/lp1612-thinksystem-sd665-v3-server","Two AMD sockets per node, two nodes per tray, DW612S enclosure, direct-water cooling and no GPU support.","Standard specifications; processors; GPU accelerators; internal storage; cooling","18 Aug 2026");
doc("faeSD665History","ThinkSystem SD665 V3: publication and CPU-refresh history","https://lenovopress.lenovo.com/lp1612-thinksystem-sd665-v3-server","First documented in November 2022; EPYC 9005 support added October 2024.","Full change history: First published 10 November 2022; 10 October 2024 update","Reviewed 09 Oct 2026");
doc("faeST45CPU","ThinkSystem ST45 V3: supported processors and GPU restrictions","https://lenovopress.lenovo.com/lp1994-thinksystem-st45-v3-server","EPYC 4004/4005 processor options; add-in GPUs unsupported.","Table 14 Supported processors; GPU adapters; OS support","Reviewed 09 Oct 2026");

const models=[
{"id":"sr630","name":"SR630 V4","family":"Rack","vendor":"Intel","shape":"physical-sr630","tag":"ThinkSystem · compact Intel workhorse","cpu":"Up to 2 × Intel Xeon 6","cpuDetail":"6500P / 6700P P-core or 6700E E-core options; qualify the exact SKU and memory configuration.","sockets":2,"memory":"32 DDR5 DIMMs · up to 8 TB in qualified P-core configurations","storage":"Up to 12 SFF (10 front + 2 rear) or 16 front E3.S; separate M.2 options","drive":["SFF","E3.S","M.2"],"gpu":"Up to 3 single-wide GPUs, up to 75 W each","gpuV":["NVIDIA"],"form":"1U rack","job":"Dense virtualization, cloud services and scale-out compute.","note":"E-core support belongs to this model. Do not assume the larger SR650 V4 offers the same CPU list.","management":"XClarity Controller 3 (XCC3); XClarity One","sources":["sr630"],"use":["Virtualization","General compute"]},
{"id":"sr650","name":"SR650 V4","family":"Rack","vendor":"Intel","shape":"physical-sr650","tag":"ThinkSystem · versatile Intel 2U","cpu":"Up to 2 × Intel Xeon 6","cpuDetail":"Qualified 6500P / 6700P P-core processors, up to 86 cores per CPU.","sockets":2,"memory":"32 DDR5 DIMMs · up to 8 TB; MRDIMM / CXL options have separate rules","storage":"Alternative builds: up to 40 SFF, 16 LFF or 32 E3.S; M.2 boot options","drive":["SFF","LFF","E3.S","M.2"],"gpu":"Up to 10 single-wide or 2 double-wide PCIe GPUs; configuration dependent","gpuV":["NVIDIA"],"form":"2U rack","job":"A flexible host for virtual machines, databases, software-defined storage and qualified accelerator cards.","note":"Drive and GPU maxima are different layouts. SR650a V4 changes the chassis around front GPUs; it is a distinct platform.","management":"XCC3; XClarity One","sources":["sr650"],"use":["Virtualization","General compute","Data & storage","AI & GPUs"]},
{"id":"sr635","name":"SR635 V3","family":"Rack","vendor":"AMD","shape":"physical-sr635","tag":"ThinkSystem · one socket in 1U","cpu":"1 × AMD EPYC 9004 / 9005","cpuDetail":"Qualified 4th- or 5th-generation EPYC; model CPU limits apply.","sockets":1,"memory":"12 DDR5 DIMMs · up to 3 TB","storage":"SFF / E1.S configurations; up to 12 SFF or 16 E1.S, plus M.2 options","drive":["SFF","E1.S","M.2"],"gpu":"Examples: up to 4 NVIDIA L4 or 5 A2; different slot / thermal rules","gpuV":["NVIDIA"],"form":"1U rack","job":"Dense single-socket compute with substantial memory and I/O capability.","note":"V3 is the Lenovo server generation. This V3 server supports qualified EPYC 9005 CPUs as well as 9004.","management":"XCC2; XClarity One","sources":["sr635"],"use":["Virtualization","General compute"]},
{"id":"sr655","name":"SR655 V3","family":"Rack","vendor":"AMD","shape":"physical-sr655","tag":"ThinkSystem · one socket, more expansion","cpu":"1 × AMD EPYC 9004 / 9005","cpuDetail":"Qualified 4th- or 5th-generation EPYC, up to 160 cores in listed options.","sockets":1,"memory":"12 DDR5 DIMMs · up to 3 TB","storage":"Up to 40 SFF or 20 LFF across front, middle and rear; M.2 options","drive":["SFF","LFF","M.2"],"gpu":"Qualified NVIDIA PCIe options, including L4 and L40S; build-specific quantities; historical AMD MI210 option withdrawn May 2026","gpuV":["NVIDIA","AMD"],"form":"2U rack","job":"Single-socket compute with room for storage-heavy applications and accelerator expansion.","note":"Rear and middle drive cages use space that can otherwise support adapters and airflow. A 40-drive build is not also a maximum-GPU build. MI210 supported up to three cards with the GPU enablement kit; that accelerator option is withdrawn, not this server.","management":"XCC2; XClarity One","sources":["sr655","faeMI210"],"use":["Virtualization","General compute","Data & storage","AI & GPUs"]},
{"id":"sr645","name":"SR645 V3","family":"Rack","vendor":"AMD","shape":"physical-sr645","tag":"ThinkSystem · two sockets in 1U","cpu":"Up to 2 × AMD EPYC 9004 / 9005","cpuDetail":"Qualified 4th- or 5th-generation EPYC; CPU, memory and cooling choices are linked.","sockets":2,"memory":"24 DDR5 DIMMs · up to 6 TB","storage":"Alternative front cages: 4 LFF, up to 10 SFF, or 16 E1.S; rear SFF and M.2 options are separate","drive":["SFF","LFF","E1.S","M.2"],"gpu":"Up to 5 single-wide GPUs; exact GPU and slot selection matter","gpuV":["NVIDIA"],"form":"1U rack","job":"Dense dual-socket AMD compute for virtualization and scale-out services.","note":"SR635 and SR645 share a 1U height. The extra CPU socket changes memory topology and available I/O, not rack height. The illustrated four-LFF cage is an alternative to the SFF/E1.S fronts, not an additional set of bays.","management":"XCC2; XClarity One","sources":["sr645"],"use":["Virtualization","General compute"]},
{"id":"sr665","name":"SR665 V3","family":"Rack","vendor":"AMD","shape":"physical-sr665","tag":"ThinkSystem · versatile AMD 2U","cpu":"Up to 2 × AMD EPYC 9004 / 9005","cpuDetail":"Qualified 4th- or 5th-generation EPYC, up to 160 cores per CPU in listed options.","sockets":2,"memory":"24 DDR5 DIMMs · up to 6 TB","storage":"Up to 40 SFF or 20 LFF; NVMe and AnyBay layouts; separate M.2 options","drive":["SFF","LFF","M.2"],"gpu":"Examples include up to 3 double-wide NVIDIA H100 NVL / L40S; historical AMD MI210 option withdrawn May 2026","gpuV":["NVIDIA","AMD"],"form":"2U rack","job":"Virtualization, databases, analytics and storage with optional PCIe acceleration.","note":"AMD is the host CPU vendor here. Documented NVIDIA GPU options demonstrate why CPU and GPU branding must be considered separately. Historical MI210 builds supported up to three cards with the GPU thermal kit; accelerator withdrawal does not retire the server.","management":"XCC2; XClarity One","sources":["sr665","faeMI210"],"use":["Virtualization","General compute","Data & storage","AI & GPUs"]},
{"id":"sr860","name":"SR860 V4","family":"Scale-up","vendor":"Intel","shape":"physical-sr860","tag":"ThinkSystem · four-socket memory scale","cpu":"2 or 4 × Intel Xeon 6700P","cpuDetail":"Xeon 6 P-core, qualified two- or four-processor populations.","sockets":4,"memory":"64 DDR5 DIMMs with 4 CPUs · up to 16 TB; separate CXL options","storage":"Up to 48 SFF, or 32 E3.S + 24 SFF; separate M.2 boot","drive":["SFF","E3.S","M.2"],"gpu":"Up to 8 single-wide or 4 double-wide GPUs in qualified builds","gpuV":["NVIDIA"],"form":"4U rack","job":"Large databases, in-memory workloads and consolidation needing a larger shared-memory system.","note":"Four CPUs in one server share a system architecture. Four independent nodes in a D3 chassis do not create the same kind of computer.","management":"XCC3; XClarity One","sources":["sr860"],"use":["Virtualization","General compute","Data & storage","AI & GPUs"]},
{"id":"st45","name":"ST45 V3","family":"Tower","vendor":"AMD","shape":"physical-st45","tag":"ThinkSystem · entry business tower","cpu":"1 × AMD EPYC 4004 / 4005","cpuDetail":"Entry platform with model-qualified processors up to 16 cores / 65 W; CPU options are CTO or preconfigured, not retail upgrade parts.","sockets":1,"memory":"2 DDR5 ECC UDIMMs · up to 64 GB","storage":"Up to 3 LFF + 1 SFF non-hot-swap bays; 2 onboard NVMe M.2 sockets","drive":["LFF","SFF","M.2"],"gpu":"Add-in GPUs are not supported in the product guide","gpuV":[],"form":"Compact tower","job":"Small-business applications, local files and basic infrastructure in an office.","note":"This entry tower has a different management and expansion design. Do not assume it has the XCC controller found in larger ThinkSystem servers.","management":"XClarity Provisioning Manager Lite; no integrated XCC remote controller","sources":["st45","faeST45CPU"],"use":["General compute","Edge & branch"]},
{"id":"st650","name":"ST650 V3","family":"Tower","vendor":"Intel","shape":"physical-st650","tag":"ThinkSystem · expandable dual-socket tower","cpu":"Up to 2 × Intel Xeon Scalable","cpuDetail":"Qualified 4th / 5th Gen processors, up to 32 cores and 250 W per CPU.","sockets":2,"memory":"32 DDR5 DIMMs · up to 4 TB","storage":"Up to 32 SFF or 16 LFF; internal M.2; media-bay options vary","drive":["SFF","LFF","M.2"],"gpu":"Qualified single- and double-wide NVIDIA PCIe GPUs; population and fan rules apply","gpuV":["NVIDIA"],"form":"Tower / 4U rack conversion","job":"Branch applications, virtualization, storage and GPU-assisted work with tower-style expansion.","note":"The larger ST650 is a different class from ST45: two sockets, registered memory and integrated remote management.","management":"XCC2; XClarity One","sources":["st650"],"use":["General compute","Virtualization","Data & storage","AI & GPUs","Edge & branch"]},
{"id":"se455","name":"ThinkEdge SE455 V3","family":"Edge","vendor":"AMD","shape":"physical-se455","tag":"ThinkEdge · short-depth AMD compute","cpu":"1 × AMD EPYC 8004","cpuDetail":"Siena edge-oriented processor family; up to 64 cores in qualified options.","sockets":1,"memory":"6 DDR5 DIMMs · up to 768 GB","storage":"4 front hot-swap SFF + optional 4 internal non-hot-swap SFF; SATA / NVMe SSDs; M.2 boot","drive":["SFF","M.2"],"gpu":"Up to 6 single-wide or 2 double-wide GPUs / accelerators; configuration dependent","gpuV":["NVIDIA"],"form":"2U short-depth · 438 mm from rack flange","job":"Edge AI and local services where environmental limits, depth and service access matter.","note":"Internal SSDs use carriers but are not hot-swappable. Some NVMe layouts also consume connections otherwise used by PCIe slots. SE455i V3 is a defined inference build.","management":"XCC2; ThinkShield edge security options; XClarity One","sources":["se455"],"use":["Edge & branch","AI & GPUs"]},
{"id":"se100","name":"ThinkEdge SE100","family":"Edge","vendor":"Intel","shape":"physical-se100","tag":"ThinkEdge · compact local AI","cpu":"1 × Intel Core Ultra Series 2","cpuDetail":"Soldered processor; qualified options up to 16 cores. This is not a Xeon rack-server socket.","sockets":1,"memory":"2 DDR5 SO-DIMM / CSODIMM slots · up to 64 GB","storage":"1 M.2 boot + up to 2 M.2 data drives; no SFF / LFF bays","drive":["M.2"],"gpu":"One qualified PCIe GPU, such as NVIDIA RTX 2000E Ada; environment / enclosure rules apply","gpuV":["NVIDIA"],"form":"Compact edge node · 1U high","job":"Retail, branch and local inference deployments with a small hardware footprint.","note":"Core Ultra, Xeon and EPYC are different CPU platform families. The common Intel logo does not imply common memory modules or server expansion.","management":"XCC2; ThinkShield edge security options","sources":["se100"],"use":["Edge & branch","AI & GPUs"]},
{"id":"sd535","name":"SD535 V3","family":"Dense","vendor":"AMD","shape":"physical-sd535","tag":"ThinkSystem · four nodes per D3 chassis","cpu":"1 × AMD EPYC 9004 / 9005 per node","cpuDetail":"Each node is independent. Qualified CPU and cooling combinations include high-density EPYC configurations.","sockets":1,"memory":"12 DDR5 DIMMs per node · up to 1.5 TB","storage":"6 SFF AnyBay SSD bays per node; onboard / adapter M.2 options","drive":["SFF","M.2"],"gpu":"Up to 1 qualified single-wide GPU per node","gpuV":["NVIDIA"],"form":"Half-width 1U node · four in 2U D3","job":"Dense scale-out compute and virtualization with independent servers sharing chassis power.","note":"D3 has no integrated networking or switching and no enclosure-level manager. Each node keeps its own networking, XCC2 and fans.","management":"XCC2 per node; XClarity One; no D3 chassis manager","sources":["sd535"],"use":["Virtualization","General compute","HPC & density"]},
{"id":"sd665","name":"SD665 V3 Neptune","family":"Neptune","vendor":"AMD","shape":"physical-sd665","tag":"ThinkSystem · AMD direct-water HPC","cpu":"2 × AMD EPYC 9004 / 9005 per node","cpuDetail":"Two independent nodes per tray. Each node requires two qualified processors, up to 160 cores / 400 W each.","sockets":2,"memory":"24 DDR5 DIMMs per node · up to 3 TB; 12 channels per socket","storage":"Up to 4 E3.S or thin 7 mm SFF SSDs, or 2 standard 15 mm SFF SSDs; drive cages trade off with PCIe slots; one M.2","drive":["E3.S","SFF","M.2"],"gpu":"GPUs are explicitly not supported in SD665 V3","gpuV":[],"form":"1U two-node tray · six trays in 6U DW612S","job":"CPU-focused simulation, technical computing and dense HPC with facility-connected warm-water cooling.","note":"A tray contains two separate two-socket servers; it does not pool their RAM. DW612S supports up to twelve nodes. Internal drives are not hot-swap; two PCIe slots leave only M.2 internal storage. SD665-N is a different GPU platform.","management":"XCC2 per node; enclosure SMM; XClarity tools","sources":["sd665"],"use":["General compute","HPC & density"]},
{"id":"sc750","name":"SC750 V4 Neptune","family":"Neptune","vendor":"Intel","shape":"physical-sc750","tag":"ThinkSystem · direct-water-cooled HPC","cpu":"2 × Intel Xeon 6900-series per node","cpuDetail":"Two independent nodes per tray; model-qualified 6900-series processors, not the SR650 V4 CPU list.","sockets":2,"memory":"24 DDR5 DIMMs per node · up to 3 TB; RDIMM / MRDIMM choices","storage":"Up to 6 E3.S NVMe SSDs per node; front drive bays can replace PCIe slots","drive":["E3.S"],"gpu":"CPU-oriented HPC platform; dedicated GPU designs are separate offerings","gpuV":[],"form":"Vertical 2-node tray · 13U N1380 enclosure","job":"CPU-heavy scientific computing and technical workloads in dense water-cooled infrastructure.","note":"N1380 holds up to eight SC750 trays / sixteen nodes. Its midplane carries power and control, not the workload network.","management":"XCC3 per node; SMM3 enclosure management","sources":["sc750"],"use":["General compute","HPC & density"]},
{"id":"sr650a","name":"SR650a V4","family":"AI","vendor":"Intel","shape":"physical-sr650a","tag":"ThinkSystem · front PCIe GPUs in 2U","cpu":"2 × Intel Xeon 6500P / 6700P","cpuDetail":"Qualified Xeon 6 P-core hosts for a GPU-focused 2U layout.","sockets":2,"memory":"32 DDR5 DIMMs · up to 8 TB","storage":"Up to 8 front SFF or 8 E3.S; internal / hot-swap M.2 options","drive":["SFF","E3.S","M.2"],"gpu":"Examples: 4 H100 NVL, 2 H200 NVL, or 8 L4; RTX PRO 6000 Blackwell variants","gpuV":["NVIDIA"],"form":"2U rack · front GPU slots","job":"Inference, visual computing and AI workloads with multiple PCIe GPUs in a familiar rack height.","note":"RTX PRO 6000 Blackwell: up to two at 600 W or four slot-capped at 450 W. SR650i V4 is a specific inference configuration based on this platform.","management":"XCC3; XClarity One","sources":["sr650a"],"use":["AI & GPUs","Virtualization"]},
{"id":"sr675","name":"SR675 V3","family":"AI","vendor":"AMD","shape":"physical-sr675","tag":"ThinkSystem · AMD GPU flexibility","cpu":"Up to 2 × AMD EPYC 9004 / 9005","cpuDetail":"Qualified AMD hosts; supported GPU / CPU combinations depend on the selected shuttle.","sockets":2,"memory":"24 DDR5 DIMMs · up to 6 TB with qualified 256 GB DIMMs","storage":"SFF, E1.S or E3.S layouts depend on the GPU shuttle; M.2 boot options","drive":["SFF","E1.S","E3.S","M.2"],"gpu":"Up to 8 PCIe GPUs including H200 NVL / RTX PRO 6000; historical MI210, H100 and 4-GPU HGX variants","gpuV":["NVIDIA","AMD"],"form":"3U rack · PCIe or SXM configurations","job":"AMD-based AI and technical computing with several purpose-built accelerator layouts.","note":"H200 NVL (C3V3) and RTX PRO 6000 (CBK8) require EPYC 9005 and C5WW fans, including field upgrades. H100 PCIe/NVL and four-GPU HGX H100/H200 are withdrawn options. The historical SXM shuttle used Neptune hybrid liquid-to-air cooling. MI210 withdrawal is recorded March 2026 in this model guide; the host model remains current.","management":"XCC2; XClarity One","sources":["sr675","faeMI210","faeSR675Rules","faeSR675Lifecycle"],"use":["AI & GPUs","HPC & density"]},
{"id":"sr680a","name":"SR680a V4","family":"AI","vendor":"Intel","shape":"physical-sr680a","tag":"ThinkSystem · eight Blackwell Ultra GPUs","cpu":"2 × Intel Xeon 6700P","cpuDetail":"Qualified Xeon 6 P-core processors, up to 86 cores per CPU.","sockets":2,"memory":"32 DDR5 DIMMs · up to 4 TB","storage":"8 SFF PCIe 5.0 NVMe bays; 2 hot-swap M.2 boot bays","drive":["SFF","M.2"],"gpu":"8 × NVIDIA HGX B300 GPUs · integrated NVL8 subsystem","gpuV":["NVIDIA"],"form":"8U rack · air cooling","job":"Large-scale AI inference, training and demanding multi-GPU computation.","note":"HGX B300 is an integrated eight-GPU platform with dedicated interconnect and networking. These are not ordinary interchangeable PCIe expansion cards.","management":"XCC3; XClarity One","sources":["sr680a"],"use":["AI & GPUs","HPC & density"]},
{"id":"sr685a","name":"SR685a V3","family":"AI","vendor":"AMD","shape":"physical-sr685a","tag":"ThinkSystem · existing-system reference","cpu":"2 × AMD EPYC 9004 / 9005","cpuDetail":"Documented host options up to 128 cores per CPU; qualification depends on the accelerator build.","sockets":2,"memory":"24 DDR5 DIMMs · up to 3 TB","storage":"Up to 16 SFF PCIe 5.0 NVMe bays; 2 M.2 boot drives","drive":["SFF","M.2"],"gpu":"Historical builds: 8 AMD MI300X, or 8 NVIDIA H100 / H200","gpuV":["AMD","NVIDIA"],"form":"8U rack · air cooling","job":"A reference for understanding existing AMD-host, eight-accelerator deployments.","note":"Withdrawn from marketing, documented September 26, 2026. Listed GPU alternatives describe documented past configurations. Withdrawal is not itself an end-of-support date.","management":"XCC2; release-specific fleet support","sources":["sr685a"],"use":["AI & GPUs","HPC & density"],"lifecycle":true}
];

const concepts={
 cpu:{name:'Host processors',what:'CPUs run the operating system and general application work.',design:'SR650 V4 supports one or two qualified Xeon 6500P / 6700P CPUs. The two-socket example links processors through UPI and gives each CPU local memory.',src:'sr650'},
 ram:{name:'DDR5 memory banks',what:'DIMMs provide the host’s working memory; their contents are separate from SSD storage.',design:'SR650 V4 has sixteen DIMM slots per CPU. Slot count, memory channels and populated DIMMs are different numbers. MRDIMM and water-cooled layouts have separate population rules.',src:'sr650'},
 drives:{name:'Drives and their backplane',what:'The backplane connects installed drives to the selected controller or onboard ports.',design:'SR650 V4 offers SFF, LFF and E3.S alternatives. AnyBay supports multiple drive interfaces only with the appropriate cabling and controller; not every bay is AnyBay.',src:'sr650'},
 pcie:{name:'PCIe expansion',what:'Expansion connections carry traffic to network, storage and accelerator devices.',design:'SR650 V4 offers several riser layouts. Rear drives, GPUs, liquid-cooling tubes and risers can compete for space and connectivity.',src:'sr650'},
 nic:{name:'OCP network adapter',what:'A NIC connects the server to a workload network. OCP 3.0 describes the adapter form factor.',design:'SR650 V4 has dedicated OCP adapter positions. The network carries application traffic; XCC management is a separate role even when a port is shared.',src:'sr650'},
 xcc:{name:'XClarity Controller 3',what:'XCC is an embedded service processor for hardware health, remote power and management.',design:'This SR650 V4 uses XCC3. Its management connection is distinct from the host’s OS. Optional remote-console functions depend on the license.',src:'sr650'},
 fleet:{name:'XClarity One portal',what:'A central interface for inventory, monitoring and lifecycle operations across supported equipment.',design:'The portal can be Lenovo-hosted or an on-premises virtual appliance. The local hub connects it to managed devices. XClarity One is not a hypervisor.',src:'xc1'},
 hub:{name:'Local XClarity One hub',what:'A local virtual appliance that connects managed devices to the XClarity One portal.',design:'The dashed route shows management communication through the hub to XCC. It is not the application-data path.',src:'xc1'},
 network:{name:'External workload network',what:'Switches and adapters connect servers to clients, storage and other compute systems.',design:'Links here summarize workload connectivity. They do not specify a deployment’s switch model, redundancy, speed or cabling plan.',src:'sd535'},
 d3:{name:'D3 shared chassis',what:'A 2U enclosure that houses independent compute nodes.',design:'This example has four half-wide, 1U SD535 V3 nodes. D3 shares power but has no built-in network switch and needs no enclosure-level manager.',src:'sd535'},
 denseNode:{name:'SD535 V3 compute node',what:'An independent single-socket server installed in the D3 chassis.',design:'Each node has its own AMD EPYC CPU, twelve DIMM slots, up to six SFF SSDs, networking, XCC2 and local fans. Node memory is not pooled across the chassis.',src:'sd535'},
 denseNic:{name:'Node-local networking',what:'The network adapter belongs to an individual server node.',design:'D3 has no built-in switching. Each node’s adapter connects outward to the external network; the diagram groups its cabling into a simple path.',src:'sd535'},
 densePower:{name:'Shared chassis power',what:'Chassis power supplies provide electrical power to the installed nodes.',design:'Power sharing saves duplicated infrastructure. It does not combine CPUs, memory, networking or operating systems into one server. Fans remain local to each SD535 node.',src:'sd535'},
 host:{name:'AI host CPUs and RAM',what:'The host coordinates work, prepares data and runs software around the GPU computation.',design:'SR680a V4 combines two Xeon 6700P CPUs with up to 32 DDR5 DIMMs. Host DDR5 is separate from the B300 GPUs’ HBM.',src:'sr680a'},
 gpu:{name:'HGX B300 eight-GPU subsystem',what:'A purpose-built accelerator subsystem with eight GPUs and high-bandwidth GPU interconnects.',design:'SR680a V4 uses NVIDIA HGX B300 NVL8. The eight GPU tiles belong to one qualified subsystem; they are not a mix-and-match set of PCIe cards.',src:'sr680a'},
 nvlink:{name:'GPU-to-GPU NVLink domain',what:'High-bandwidth links let GPUs exchange data during parallel workloads.',design:'The shared bar abstracts the HGX internal interconnect. It is not an Ethernet switch and does not promise that software sees all GPU memory as one automatic pool.',src:'sr680a'},
 aiio:{name:'ConnectX-8 GPU connectivity',what:'High-speed I/O connects the GPU subsystem toward the external cluster network.',design:'SR680a V4 uses ConnectX-8 GPU Direct switches and eight front OSFP cages. The grouped paths simplify the official topology; individual lanes and links are omitted.',src:'sr680a'},
 aistorage:{name:'AI-system local flash',what:'Persistent SSD storage holds boot software and local data.',design:'SR680a V4 has eight front SFF NVMe bays and two hot-swap M.2 boot bays. These are separate from the GPUs’ high-bandwidth memory.',src:'sr680a'},
 cooling:{name:'Power and air cooling',what:'Power supplies, heatsinks and fans sustain this accelerator system.',design:'SR680a V4 is an 8U air-cooled design. “Air-cooled” does not imply a small power or airflow requirement; Neptune water-cooled designs are separate configurations.',src:'sr680a'}
};

const glossary={
 'ThinkSystem':'Lenovo’s infrastructure hardware family. Use the complete model and generation when checking a server’s options.',
 'ThinkEdge':'Purpose-built edge systems. Short depth, environmental limits, physical security and local inference may shape the design.',
 'ThinkAgile':'Validated infrastructure solutions combining Lenovo hardware with specific software stacks. Common examples include HX with Nutanix, VX with VMware and MX with Microsoft Azure Local.',
 'SR / ST / SD / SC / SE':'Useful family cues: rack, tower, dense nodes, supercomputing and edge. Treat the full product name as the compatibility key.',
 'V3 / V4':'The Lenovo server generation. It is not a CPU generation, GPU generation, socket count or support end date.',
 'Socket / 1P / 2P / 4P':'The number of host processors in one server. Four nodes each with one CPU are four independent computers, not a four-socket server.',
 'U / 2U4N':'One rack unit is 44.45 mm high. 2U4N means four independent server nodes in two rack units.',
 'EPYC 4005 / 8004 / 9005':'Different AMD server processor families used here for entry towers, edge and data-center racks. They are not interchangeable sockets.',
 'Xeon 6 P-cores / E-cores':'Intel CPU choices emphasize different core designs. The precise server, processor series and memory rules determine support.',
 'Core Ultra':'An Intel processor family also used in the compact SE100 edge server. This does not make SE100 equivalent to a Xeon rack platform.',
 'DDR5 / DIMM / DPC':'DDR5 is memory technology; a DIMM is a physical module; DPC means DIMMs per memory channel. Channels and slots are different counts.',
 'RDIMM / UDIMM / SO-DIMM':'Different physical and electrical memory designs. ST45’s ECC UDIMMs and SE100’s compact modules do not interchange with rack-server RDIMMs.',
 'MRDIMM / CXL':'MRDIMMs increase memory bandwidth in qualified platforms. CXL enables supported memory expansion over an appropriate link. CPU, bay and OS support all matter.',
 'AnyBay':'Lenovo bays designed for multiple drive interfaces. Correct drives, backplane, cabling and controller remain necessary; the name does not make all bays universal.',
 'SFF / LFF':'Usually 2.5-inch and 3.5-inch drive-size classes. Either size can encompass different drive interfaces and media.',
 'SAS / SATA / NVMe':'Drive interfaces or protocols. NVMe commonly uses PCIe. A compatible carrier alone does not establish support.',
 'E1.S / E3.S / EDSFF':'Enterprise drive form factors. E1.S and E3.S need different carriers and bays. Some E3.S 2T bays instead support CXL memory modules.',
 'M.2':'A compact module shape used for boot and sometimes data SSDs. SATA versus NVMe, RAID capability and serviceability vary by adapter.',
 'RAID / HBA':'RAID organizes drives for resilience or performance; an HBA provides storage connectivity. RAID does not replace backups.',
 'PCIe / OCP NIC':'PCI Express connects devices to the system. An OCP NIC is a network card using a standardized server-adapter form factor.',
 'XCC2 / XCC3':'Embedded XClarity Controllers for individual-server monitoring and remote management. They work outside the workload operating system.',
 'XClarity One':'Fleet management with a cloud or local portal and local hubs. Check supported endpoints, firmware and licenses.',
 'D3 / N1380':'Different enclosures: D3 is a 2U dense-node chassis; N1380 is a 13U water-cooled supercomputing enclosure. Their nodes and management differ.',
 'Neptune':'Lenovo cooling technologies across several architectures. A hybrid liquid-to-air system and an open-loop direct-water system need different infrastructure.',
 'CDU':'Coolant distribution unit. It manages heat transfer and coolant circulation between the IT cooling loop and the facility cooling system.',
 'GPU / HBM':'A GPU accelerates parallel work; HBM is local high-bandwidth accelerator memory. Host RAM and SSD storage are separate resources.',
 'PCIe GPU / SXM / OAM / HGX':'PCIe cards, NVIDIA SXM modules and OAM modules are different hardware formats. HGX describes an integrated NVIDIA GPU platform.',
 'NVLink / Infinity Fabric':'Different interconnect technologies used by specific accelerator systems. GPU brand does not follow automatically from host CPU brand.',
 'Inference / training':'Training changes a model’s parameters; inference uses a trained model to produce results. Both can require substantial GPU memory and supported software.',
 'Withdrawn from marketing':'A sales-lifecycle milestone. It does not, by itself, state when service or support ends for an installed system.'
};
const quiz=[
 {q:'What does V3 in SR665 V3 identify?',options:['Third-generation EPYC only.','Lenovo’s server generation.','Three CPU sockets.'],answer:1,why:'SR665 V3 supports qualified EPYC 9004 and 9005 processors. The Lenovo generation and the CPU generation are separate labels.',src:'sr665'},
 {q:'Which pair shows single-socket AMD in 1U and 2U?',options:['SR635 V3 and SR655 V3','SR645 V3 and SR665 V3','SR630 V4 and SR650 V4'],answer:0,why:'SR635 V3 is 1U / one AMD socket; SR655 V3 is 2U / one AMD socket. SR645 / SR665 are two-socket platforms.',src:'comparison'},
 {q:'Can an AMD EPYC server use NVIDIA GPUs?',options:['Only when the GPU is built by AMD.','No, CPU and GPU brands must match.','Yes, in a qualified configuration such as SR675 V3.'],answer:2,why:'SR675 V3 combines AMD host CPUs with NVIDIA PCIe or HGX GPU configurations. CPU brand is not a GPU compatibility rule.',src:'sr675'},
 {q:'What does the D3 chassis share between SD535 nodes?',options:['One operating system and one RAM pool.','Chassis power; nodes retain their own compute and networking.','An integrated Ethernet switch.'],answer:1,why:'D3 has no built-in networking or switching and needs no enclosure manager. Each SD535 keeps its own CPU, memory, NIC, XCC2 and fans.',src:'sd535'},
 {q:'What does E3.S NVMe tell you?',options:['A drive form factor and a storage protocol.','The exact capacity of an SSD.','A RAID level.'],answer:0,why:'E3.S describes the physical drive family; NVMe is the protocol. A complete supported bay, backplane and controller configuration still matters.',src:'sr650'},
 {q:'How do XCC and XClarity One differ?',options:['XCC runs guest virtual machines.','They are two names for the same embedded chip.','XCC manages one server; XClarity One manages a supported fleet.'],answer:2,why:'The embedded XCC service processor monitors hardware. XClarity One adds a portal and local hubs for fleet operations.',src:'xc1'},
 {q:'Does every Neptune system need the same cooling infrastructure?',options:['Yes, the name guarantees an identical water connection.','No, hybrid liquid-to-air and open-loop designs differ.','Neptune only names a processor.'],answer:1,why:'SR675’s SXM model uses hybrid liquid-to-air cooling. SC750 uses direct water cooling in N1380. Read the exact cooling architecture.',src:'sr675'},
 {q:'How should you read the SR685a V3 profile in this guide?',options:['As a withdrawn platform reference for existing systems.','As proof that every listed GPU is currently orderable.','As a declaration that all support has ended.'],answer:0,why:'Lenovo documented withdrawal from marketing on September 26, 2026. That is different from an end-of-support date.',src:'sr685a'}
];

// Installed-base profiles added after the October 2026 FAE audit.
models.push(...[
  {
    "id": "sr665original",
    "name": "SR665 (original)",
    "family": "Rack",
    "vendor": "AMD",
    "shape": "installed-sr665original",
    "tag": "Original SR665 · DDR4 installed base",
    "cpu": "1 or 2 × AMD EPYC 7002 / 7003",
    "cpuDetail": "Rome, Milan and qualified Milan-X; P-suffix CPU entries are single-socket only.",
    "sockets": 2,
    "memory": "32 DDR4 RDIMM / 3DS RDIMM slots · 8 channels per CPU",
    "storage": "SFF/LFF SAS/SATA and NVMe configurations; front/mid/rear options are not all simultaneous.",
    "drive": [
      "SFF",
      "LFF",
      "NVMe",
      "M.2"
    ],
    "gpu": "Qualified PCIe GPU configurations; exact AMD accelerator support not recorded here.",
    "gpuV": [
      "NVIDIA"
    ],
    "form": "2U rack",
    "job": "Compare the DDR4 installed base with the separately listed SR665 V3 DDR5 platform.",
    "note": "This is the original SR665, not SR665 V3. One CPU exposes 16 DIMM slots; two expose 32.",
    "management": "XClarity Controller; XClarity Administrator",
    "sources": [
      "auditSR665",
      "auditSR665Memory"
    ],
    "use": [
      "Virtualization",
      "General compute",
      "Data & storage"
    ]
  }
]);
Object.assign(sources,{
  "auditSR665": {
    "title": "ThinkSystem SR665 Product Guide",
    "url": "https://lenovopress.lenovo.com/lp1269-thinksystem-sr665-server",
    "loc": "Standard specifications; processor options; full change history",
    "scope": "Original SR665 (no V3 suffix), CPU families, physical form, and withdrawal history.",
    "date": "Updated 21 Apr 2026; first published 5 May 2020",
    "publicationDate": "2020-05-05",
    "reviewed": "2026-10-09",
    "revision": "Updated 21 Apr 2026; first published 5 May 2020"
  },
  "auditSR665Memory": {
    "title": "ThinkSystem SR665: memory installation rules",
    "url": "https://pubs.lenovo.com/sr665/memory_module_install_rules",
    "loc": "Memory population table: processor count, DIMM quantity and slots",
    "scope": "One/two CPU DDR4 population; exact speed depends on the selected DIMM and CPU.",
    "date": "Publication date not recorded",
    "publicationDate": null,
    "reviewed": "2026-10-09"
  }
});
// BEGIN AUDIT PROSE ALIGNMENT
for(const [id,changes] of Object.entries({"sr630":{"memory":"32 DDR5 DIMM slots in conventional builds; 16 slots / 1DPC in the Compute Complex Neptune variant. Capacity and memory types depend on the qualified CPU and layout."},"sr650":{"memory":"32 DDR5 DIMM slots in conventional builds; 16 slots / 1DPC in the Compute Complex Neptune variant. Capacity and memory types depend on the qualified CPU and layout."},"sr650a":{"cpu":"1 or 2 × Intel Xeon 6500P / 6700P"}}))Object.assign(models.find(m=>m.id===id),changes);

