// BEGIN hardware
function hardware(shape='rack2',hero=false){
 const uid='lenovo-art-'+(++artSerial),metal=`url(#${uid}-metal)`,mesh=`url(#${uid}-mesh)`;
 const r=(x,y,w,h,fill='#202123',stroke='#5a6064',rad=1)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rad}" fill="${fill}" stroke="${stroke}" stroke-width=".6"/>`;
 const vent=(x,y,w,h)=>r(x,y,w,h,mesh,'#585e61');
 const drive=(x,y,w,h,vertical=false)=>r(x,y,w,h,'#17191a','#85898d')+vent(x+2,y+2,w-4,h-4)+`<path d="M${x+2} ${y+2}${vertical?'h'+(w-4):'v'+(h-4)}" stroke="#e43a48" stroke-width="1.2"/>`+r(x+w*.26,y+h-3,w*.56,2,'#414548','#303436');
 const bank=(x,y,w,h,cols,rows=1,vertical=false)=>{let q='';for(let j=0;j<rows;j++)for(let i=0;i<cols;i++)q+=drive(x+i*w/cols,y+j*h/rows,w/cols-1.5,h/rows-1.5,vertical);return q;};
 const ports=(x,y,n=3)=>Array.from({length:n},(_,i)=>r(x+i*9,y,7,4,'#080d10','#929ba0')).join('');
 const lights=(x,y)=>`<circle cx="${x}" cy="${y}" r="1.5" fill="#87d8b8"/><circle cx="${x}" cy="${y+5}" r="1" fill="#83b4e0"/>`;
 const shell=(x,y,w,h,ears=true,depth=22)=>`<path d="M${x} ${y}l${depth} -16h${w+8-depth}l-8 16z" fill="${metal}" stroke="#92999d" stroke-width=".7"/><path d="M${x+w} ${y}l8 -16v${h}l-8 16z" fill="#626a70" stroke="#92999d" stroke-width=".5"/>`+r(x,y,w,h,'#383e43','#a7afb4',2)+(ears?r(x,y,12,h,'#24292e','#626b72')+r(x+w-12,y,12,h,'#24292e','#626b72')+lights(x+w-6,y+7)+`<path d="M${x+2} ${y+h-5}h8M${x+w-10} ${y+h-5}h8" stroke="#73a7d3"/>`: '');
 const slots=(x,y,w,h,count,vertical=false)=>{let q='';for(let i=0;i<count;i++){let sx=x+(vertical?i*w/count:0),sy=y+(vertical?0:i*h/count),sw=vertical?w/count-2:w,sh=vertical?h:h/count-2;q+=r(sx,sy,sw,sh,metal,'#949da4')+vent(sx+3,sy+2,sw-6,sh-4);}return q;};
 const rack=(x,y,w,h,kind='sff24')=>{let q=shell(x,y,w,h),ix=x+16,iw=w-32;
  if(kind==='sff10'){q+=bank(ix,y+3,iw*.86,h-6,5,2)+vent(ix+iw*.87,y+2,iw*.12,h-4)+ports(ix+iw*.88,y+7,2)+lights(ix+iw*.97,y+8);}
  else if(kind==='lff4'){q+=bank(ix,y+h*.34,iw,h*.61,4)+ports(ix+iw*.67,y+3,3)+vent(ix,y+2,iw*.55,h*.25);}
  else if(kind==='mixed'){q+=bank(ix,y+4,iw,(h-9)*.5,4,8)+bank(ix,y+h*.53,iw,h*.43,24,1,true);}
  else q+=bank(ix,y+4,iw,h-8,24,1,true);
  return q;
 };
 const nodeFront=(x,y,w,h)=>r(x,y,w,h,'#24292d','#8c969d')+bank(x+2,y+2,w-4,h-7,3,2)+ports(x+w*.37,y+h-4,2)+`<path d="M${x+w*.58} ${y+h-2}h${w*.18}" stroke="#77ace8" stroke-width="2"/>`;
 const waterFront=(x,y,w,h)=>{let q=r(x,y,w,h,metal,'#a3adb4');for(let n=0;n<2;n++){let nx=x+n*w/2;q+=slots(nx+7,y+3,w*.41,h*.36,2,true)+ports(nx+8,y+h*.7,4)+lights(nx+w*.45,y+h*.68);}return q;};
 const map={rack1:'sr630',rack2:'sr650',rack4:'sr860',node:'sd535',tower:'st650',smalltower:'st45',edge:'se455',microedge:'se100',neptunetray:'sd665',gpu2:'sr650a',gpu3:'sr675',gpu8:'sr680a',gpu8legacy:'sr685a'};
 const model=shape.startsWith('physical-')?shape.slice(9):(map[shape]||shape);
 let b='',label='Lenovo reference-based schematic';
 if(model==='portfolio'){b=rack(42,45,272,25,'sff10')+rack(26,102,303,55)+rack(18,169,318,58);label='ThinkSystem portfolio: representative 1U ten-SFF and 2U twenty-four-SFF fronts';}
 else if(['sr630','sr635','sr645'].includes(model)){b=rack(15,89,322,29,model==='sr645'?'lff4':'sff10');label=`${model.toUpperCase()} reference front; ${model==='sr645'?'four horizontal LFF carriers with upper control strip':'ten horizontal SFF carriers in two rows of five and right control panel'}`;}
 else if(['sr650','sr655','sr665'].includes(model)){b=rack(15,77,322,58);label=`${model.toUpperCase()} reference front; one row of twenty-four vertical SFF carriers, bezel removed`;}
 else if(model==='sr860'){b=rack(19,46,314,113,'mixed');label='SR860 V4 reference front; upper 32 E3.S positions in four stacks, lower 24 vertical SFF bays';}
 else if(model==='sd535'){b=shell(69,86,205,32,false,55)+nodeFront(69,86,205,32);label='SD535 V3 single half-width node, six front SFF bays in two rows; separate D3 enclosure required';}
 else if(model==='dense'){b=shell(15,76,322,58);for(let i=0;i<4;i++){const x=30+(i%2)*145,y=79+Math.floor(i/2)*26;let n=nodeFront(x,y,142,25);b+=i%2?`<g transform="rotate(180 ${x+71} ${y+12.5})">${n}</g>`:n;}label='D3 enclosure front with four SD535 nodes; right-hand nodes installed inverted, as in Lenovo Figure 7';}
 else if(model==='st45'){b=`<path d="M193 37l48-16v135l-48 16z" fill="${metal}" stroke="#78848c" stroke-width=".7"/><path d="M132 37l48-16h61l-48 16z" fill="#a7b0b6" stroke="#8c989f" stroke-width=".7"/><g transform="translate(0 15) scale(1 .92)">`+r(132,24,61,147,'#202327','#697279',3)+vent(136,29,52,137)+r(137,32,33,51,'#272b2f','#373e44')+r(177,30,11,58,'#252a2f','#252a2f')+lights(182,37);for(let i=0;i<4;i++)b+=r(179,53+i*6,7,3,'#070a0c','#697278');b+=`<text x="141" y="126" font-size="6" fill="#bfc8ce">ThinkSystem</text></g>`;label='ST45 V3 compact tower: perforated front, upper-left media area and upper-right I/O strip; no hot-swap carriers';}
 else if(model==='st650'){
  b=`<path d="M193 25l49-13v148l-49 14z" fill="${metal}" stroke="#77848a" stroke-width=".7"/><path d="M118 25l49-13h75l-49 13z" fill="#a6afb5" stroke="#87949d" stroke-width=".7"/><g transform="translate(0 11) scale(1 .94)">`+r(118,15,75,158,'#20262b','#78848c')+r(123,21,65,12,'#161b20','#58636c')+r(123,38,65,12,'#161b20','#58636c')+bank(125,59,62,107,8,4,true)+'</g>';label='ST650 V3 tower: two upper media bays, four eight-SFF drive banks and a clean chassis base';
 }
 else if(model==='se455'){b=shell(15,72,322,58);b+=slots(32,77,77,34,3)+slots(113,77,77,34,3)+bank(198,76,119,25,2,2)+ports(33,116,8);for(let i=0;i<2;i++){let x=198+i*60;b+=r(x,104,57,22,metal,'#999fa4')+`<circle cx="${x+12}" cy="115" r="9" fill="#151c20" stroke="#c5cbd0"/>`+r(x+26,108,15,14,'#0b1015','#30383e')+r(x+46,108,4,14,'#b8792b','#e4a657');}label='SE455 V3 front-service layout: PCIe banks at left, four SSD bays above two power supplies at right';}
 else if(model==='se100'){
  // Parallel, finite-thickness fins share one lid plane and stay inside its perimeter.
  b=`<path d="M78 105l36-38h198l-36 38z" fill="#414a50" stroke="#7b878f" stroke-width=".7"/><path d="M276 105l36-38v35l-36 38z" fill="#242e35" stroke="#626f78" stroke-width=".7"/><path d="M92 103l35-35h172l-35 35z" fill="#1c252b" stroke="#68757e" stroke-width=".7"/>`;
  for(let i=0;i<13;i++){const x=103+i*12;b+=`<path d="M${x} 101V81l34-34v20z" fill="#333e46"/><path d="M${x} 81l34-34h2l-34 34z" fill="#89949b"/><path d="M${x} 81h2v20h-2z" fill="#606e77"/>`;}
  b+=r(78,105,198,35,'#333e46','#8b989f')+ports(89,124,2)+r(132,116,15,15,'#111820','#a7b0b6')+ports(156,116,2)+ports(156,128,2)+lights(249,127)+r(226,111,38,9,'#252c31','#657078');label='ThinkEdge SE100: compact passive cooling fins, HDMI/serial/USB and status controls on the front; no disk trays or rack ears';
 }
 else if(model==='sd665'){b=shell(21,92,310,29,false,49)+waterFront(21,92,310,29);label='SD665 V3 two-node tray front with adapter slots and I/O; water connections are at the rear, DW612S enclosure required';}
 else if(model==='sc750'){b=`<path d="M131 14h28l75 36v123l-75 12h-28z" fill="${metal}" stroke="#a8b0b6"/>`+`<g transform="translate(131 185) rotate(-90)">${waterFront(0,0,171,28)}</g>`+r(135,13,17,5,'#424c54','#848f98')+r(135,179,17,5,'#424c54','#848f98');label='SC750 V4 single vertical two-node tray, front I/O face and long enclosure sled; requires N1380';}
 else if(model==='neptune'){b=r(101,10,158,177,metal,'#a1aab1')+r(109,17,142,163,'#4c565e','#76848f');for(let i=0;i<8;i++)b+=`<g transform="translate(${111+i*17.3} 177) rotate(-90)">${waterFront(0,0,157,16)}</g>`;label='N1380 enclosure front with eight vertical SC750 two-node trays, sixteen independent nodes';}
 else if(model==='sr650a'){b=shell(15,77,322,58)+slots(32,81,88,50,4)+bank(124,81,100,50,8,1,true)+slots(230,81,88,50,4);label='SR650a V4 front: eight central SFF bays flanked by four horizontal PCIe openings on each side';}
 else if(model==='sr675'){b=shell(15,61,322,86)+bank(32,69,32,69,1,6)+slots(69,67,240,73,16,true)+ports(313,76,1);label='SR675 V3 eight double-wide GPU configuration: left six-E1.S stack, broad vertical PCIe GPU opening bank, right I/O';}
 else if(model==='sr680a'||model==='sr685a'){const legacy=model==='sr685a',x=66,y=25,w=222,h=158,ix=x+12,iw=w-24;b=shell(x,y,w,h);const fans=legacy?5:6;for(let i=0;i<fans;i++){let fx=ix+i*iw/fans;b+=vent(fx,y+3,iw/fans-2,37)+r(fx+iw/fans*.45,y+4,7,4,'#dd8b32','#e7a861');}b+=ports(ix+3,y+44,3)+vent(ix,y+50,iw,45);if(legacy){b+=bank(ix+13,y+56,63,36,8,1,true)+bank(ix+115,y+56,63,36,8,1,true)+slots(ix,y+99,iw,52,8,true);}else{b+=bank(ix+3,y+61,63,32,8,1,true)+slots(ix+109,y+48,50,44,4,true)+r(ix+167,y+48,29,8,'#12191e','#56646e')+vent(ix,y+99,iw,53);for(let i=0;i<8;i++)b+=r(ix+10+(i<4?i:i+1)*20,y+105,14,8,'#0b1015','#9aa6ae');}label=legacy?'SR685a V3 front: five fan modules, two banks of eight NVMe bays, eight lower networking PCIe openings':'SR680a V4 front: six fan modules, eight NVMe bays on left, four vertical PCIe slots, lower eight OSFP ports';}
 else b=rack(15,77,322,58);
 return `<svg viewBox="0 0 360 ${model==='portfolio'?240:195}" role="img" aria-label="${label}"><defs><linearGradient id="${uid}-metal" x2=".25" y2="1"><stop stop-color="#c1c5c8"/><stop offset=".4" stop-color="#90979d"/><stop offset="1" stop-color="#5a6269"/></linearGradient><pattern id="${uid}-mesh" width="3.6" height="4.2" patternUnits="userSpaceOnUse"><rect width="3.6" height="4.2" fill="#41464a"/><path d="m1.8 .3 1.4 .8v1.7l-1.4 .8-1.4-.8V1.1z" fill="#0a0e12"/></pattern></defs>${b}</svg>`;
}
// END hardware
// BEGIN architecture
function architecture(){
 let svg='<defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".6" fill="#695053" opacity=".48"/></pattern></defs><rect width="1000" height="540" fill="#131519"/><rect width="1000" height="540" fill="url(#grid)"/>';
 const box=(x,y,w,h,label)=>`<rect class="enclosure" x="${x}" y="${y}" width="${w}" height="${h}" rx="12"/><text class="tiny" x="${x+18}" y="${y+25}">${label}</text>`;
 if(state.mode==='rack'){
  svg+=box(60,174,880,324,'THINKSYSTEM SR650 V4 · 2U · LOGICAL COMPONENT GROUPS');
  svg+='<path class="trace management" d="M310 75h40M490 107v41H41v94h51"/><path class="trace" d="M811 107v105M794 264v27H612v32M235 349h40M440 349h90M695 349h40M350 375v22H300v31M612 375v22h145v31"/>';
  svg+=node('fleet',60,43,250,64,'XClarity One portal','Cloud or on premises');svg+=node('hub',350,43,280,64,'Local management hub','Fleet-to-device connection');svg+=node('network',691,43,249,64,'External network','Workload traffic');
  svg+=node('xcc',92,212,210,52,'XClarity Controller 3','Embedded management');svg+=node('nic',688,212,212,52,'OCP network adapter','Workload I/O');
  svg+=node('ram',95,323,140,52,'DDR5 DIMMs','CPU 1 memory');svg+=node('cpu',275,323,165,52,'CPU 1','Xeon 6 P-core');svg+=node('cpu',530,323,165,52,'CPU 2','Optional socket');svg+=node('ram',735,323,165,52,'DDR5 DIMMs','CPU 2 memory');
  svg+=node('drives',95,428,414,48,'Drive bays + backplane','SFF / LFF / E3.S configurations');svg+=node('pcie',590,428,310,48,'PCIe expansion','Qualified GPUs and adapters');
 }else if(state.mode==='dense'){
  svg+=node('network',550,30,390,58,'External workload network','Each node connects through its own NIC');
  svg+=box(60,138,880,360,'D3 · 2U · FOUR SD535 V3 NODES');
  svg+=node('d3',72,30,388,58,'D3 shared chassis','Inspect the enclosure');
  svg+='<path class="trace" d="M745 88v32H504v238M504 232H475M504 358H475M504 232h33M504 358h33"/>';
  for(let i=0;i<4;i++){
   const x=i%2?537:90,y=i<2?197:323;
   svg+=node('denseNode',x,y,385,83,'','',{aria:'SD535 compute node '+(i+1),content:`<text x="${x+18}" y="${y+26}" class="label">NODE ${i+1} · SD535 V3</text><text x="${x+18}" y="${y+47}" class="sublabel">1 EPYC · local DDR5 · SSDs</text><text x="${x+18}" y="${y+66}" class="sublabel">Own OS · XCC2 · fans</text>`});
  }
  svg+=node('denseNic',308,96,167,30,'','',{content:'<text x="391.5" y="116" text-anchor="middle" class="sublabel">Node-local networking</text>'});
  svg+=node('densePower',90,443,832,32,'','',{content:'<text x="506" y="464" text-anchor="middle" class="sublabel">SHARED POWER · NO BUILT-IN NETWORK SWITCH · NO SHARED RAM POOL</text>'});
 }else{
  svg+=box(60,112,880,386,'THINKSYSTEM SR680a V4 · 8U AIR-COOLED AI SERVER');
  svg+=node('network',603,26,337,56,'External AI cluster network','Connect other systems and storage');
  svg+='<path class="trace" d="M770 82v76M520 190h69M350 221v29M706 221v29M93 190H78v269h15"/>';
  svg+=node('host',93,158,427,63,'2 × Xeon 6700P + DDR5','The host system');svg+=node('aiio',589,158,317,63,'ConnectX-8 GPU I/O','Grouped PCIe / network connections');
  svg+='<rect x="94" y="250" width="811" height="177" rx="10" fill="#1c171e" stroke="#725360" stroke-dasharray="4 4"/>';
  for(let i=0;i<8;i++){const x=111+i*97;svg+=node('gpu',x,270,86,61,'GPU '+(i+1),'B300');svg+=`<path class="trace gpu-trace" d="M${x+43} 331v27"/>`;}
  svg+=node('nvlink',112,358,776,47,'HGX B300 NVL8 · NVLink GPU-to-GPU domain','Eight GPUs, each with local HBM');
  svg+=node('aistorage',93,443,386,33,'','',{content:'<text x="286" y="465" text-anchor="middle" class="sublabel">8 SFF NVMe + 2 M.2 BOOT BAYS</text>'});
  svg+=node('cooling',525,443,381,33,'','',{content:'<text x="715.5" y="465" text-anchor="middle" class="sublabel">CHASSIS POWER + AIR COOLING</text>'});
 }
 svg+='<text class="tiny" x="60" y="525">LOGICAL SCHEMATIC · PLACEMENT, CONNECTIONS AND QUANTITIES SIMPLIFIED</text>';
 $('#diagramMount').innerHTML=`<svg class="diagram" viewBox="0 0 1000 540" role="group" aria-label="Interactive Lenovo ${state.mode} system diagram">${svg}</svg>`;
 $('#diagramBlurb').innerHTML={rack:`A self-contained server connects to your network. XClarity One reaches its embedded controller through a local hub. ${sourceLink('sr650','SR650 V4 architecture')} · ${sourceLink('xc1','XClarity One roles')}`,dense:`Four servers share an enclosure and power, while their CPUs, RAM, fans, management and networking remain independent. ${sourceLink('sd535','D3 and SD535 architecture')}`,ai:`The host, local storage and integrated GPU subsystem have different roles. The GPU links are grouped here; this is not a lane-by-lane wiring diagram. ${sourceLink('sr680a','SR680a V4 architecture')}`}[state.mode];
 $$('#modeSwitch button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode)));
 const ids=$$('[data-concept]',$('#diagramMount')).map(n=>n.dataset.concept);if(!ids.includes(state.concept))state.concept={rack:'cpu',dense:'d3',ai:'gpu'}[state.mode];setConcept(state.concept);
}
// END architecture
// BEGIN overview
function overview(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">AN INTERACTIVE GUIDE TO LENOVO SERVERS</div><h1>Meet ThinkSystem.<br><em>Think beyond the rack.</em></h1><p>From an office tower to liquid-cooled supercomputing. Get to know the server families, see how the pieces fit, and make sense of AMD, Intel and GPU options.</p><div class="button-row"><a class="btn primary" href="#lineup">Explore the servers <span>↗</span></a><button class="btn ghost" data-scroll="systemMap">Take the system tour <span>↓</span></button></div><div class="source-note">Based on ${sourceLink('portfolio','Lenovo’s portfolio')} and model-specific Lenovo Press guides.<br>${models.length} selected platforms · reviewed 09 Oct 2026.</div></div><div class="hero-art"><div class="hero-stack">${hardware('portfolio',true)}</div><div class="art-label">THINKSYSTEM · ILLUSTRATIVE FRONT VIEWS</div></div></section>
 <div class="chapter-heading"><h2>Start with the shape of the system</h2><span class="small">Six ways to explore the offering.</span></div><section class="family-grid lenovo-families" aria-label="Lenovo hardware families">
 ${[['Rack','01 / EVERYDAY INFRASTRUCTURE','rack2','ThinkSystem rack','Self-contained servers for VMs, databases, storage and general compute.','SR630 / SR650 · SR635 / SR665'],['Tower','02 / BUSINESS & BRANCH','tower','ThinkSystem tower','From compact entry systems to large, expandable dual-socket servers.','ST45 V3 · ST650 V3'],['Edge','03 / COMPUTE CLOSE TO DATA','edge','ThinkEdge','Compact platforms for local services and AI beyond the data center.','SE100 · SE455 V3'],['Dense','04 / MORE NODES, LESS SPACE','dense','ThinkSystem dense','Independent compute nodes share chassis power in a compact enclosure.','SD535 V3 + D3 chassis'],['AI','05 / ACCELERATED COMPUTING','gpu8','ThinkSystem AI','PCIe GPU servers and integrated multi-GPU systems serve different needs.','SR650a · SR675 · SR680a'],['Neptune','06 / WATER-COOLED COMPUTE','neptune','Neptune systems','Purpose-built supercomputing and cooling options across selected servers.','SD665 V3 / SC750 V4']].map(([family,num,shape,title,desc,chip])=>`<button class="family-card" data-family="${family}"><span class="over">${num}</span><span class="arrow">↗</span><div class="hardware">${hardware(shape)}</div><h3>${title}</h3><p>${desc}</p><div class="chip-row"><span class="badge">${chip}</span></div></button>`).join('')}</section>
 <section class="two-col section"><article class="lesson"><div class="eyebrow">READ THE NAME</div><h3 style="margin-top:12px">ThinkSystem SR665 V3</h3><div class="name-decoder"><div class="name-piece">SR<small>Rack family</small></div><div class="name-piece">665<small>Model identity</small></div><div class="name-piece">V3<small>Server generation</small></div></div><p>In this AMD rack set, SR635 / SR655 have one socket and SR645 / SR665 have two. SR63x / SR64x here are 1U; SR65x / SR66x are 2U.</p><p><b>V3 does not mean third-generation EPYC.</b> These V3 platforms support qualified 9004 and 9005 CPUs. Keep the full name when checking an option.</p>${sourceLink('comparison','Explore Lenovo’s model comparison')}</article><article class="lesson"><div class="eyebrow">THREE NAMES, DIFFERENT JOBS</div><h3 style="margin-top:12px">ThinkSystem. ThinkEdge. ThinkAgile.</h3><p><b>ThinkSystem</b> is the hardware family. <b>ThinkEdge</b> emphasizes edge deployments. <b>ThinkAgile</b> packages selected hardware with a validated infrastructure software stack.</p><p>ThinkAgile <b>HX</b> uses Nutanix, <b>VX</b> uses VMware, and <b>MX</b> uses Microsoft Azure Local. A ThinkAgile solution has its own qualification rules.</p>${sourceLink('portfolio','See the hardware and solution families')}</article></section>
 <section class="panel section" id="systemMap"><div class="panel-head"><div><div class="eyebrow">THE SYSTEM, CONNECTED</div><h2 style="margin-top:8px">Open up three different designs.</h2><p>Choose a system, then select a component to understand its role.</p></div><div class="segmented" id="modeSwitch" aria-label="Lenovo system mode"><button data-mode="rack" aria-pressed="true">Rack server</button><button data-mode="dense" aria-pressed="false">D3 dense nodes</button><button data-mode="ai" aria-pressed="false">Eight-GPU AI</button></div></div><div class="diagram-scroll"><div id="diagramMount"></div></div><div class="diagram-legend"><span><i></i>Workload / component connection</span><span><i style="background:var(--purple)"></i>Management connection</span><span>Tap or use Tab + Enter to inspect</span></div><div class="diagram-blurb" id="diagramBlurb"></div><div class="detail-panel" id="partDetail" aria-live="polite"></div></section>
 <section class="three-col section"><article class="lesson"><div class="big-number">01</div><h3>Pick the physical design.</h3><p>A tower, a rack server, a D3 node and a Neptune tray need different infrastructure. Start with where the system lives and how it is serviced.</p></article><article class="lesson"><div class="big-number">02</div><h3>Separate CPU from GPU.</h3><p>AMD and Intel identify host processors. NVIDIA and AMD also supply accelerators. The complete server configuration determines which pairing works.</p></article><article class="lesson"><div class="big-number">03</div><h3>Read the configuration.</h3><p>Drive count, GPU count and maximum memory are not automatically simultaneous. The product guide explains the tradeoffs.</p></article></section><div class="next-lesson"><p>Next: meet the models behind those families.</p><a class="btn primary" href="#lineup">Explore the lineup →</a></div>`;}
// END overview
// BEGIN lineup
function lineup(){return `${intro('02 / THE HARDWARE EXPLORER','Find the platform behind the name.','Explore '+models.length+' representative models, including clearly marked historical references. Filter by design, host CPU or workload, then compare up to three.')}
 <div class="filterbar"><div class="filter search"><label for="modelSearch">SEARCH THE LINEUP</label><input id="modelSearch" type="search" placeholder="Try SR665, EPYC, Neptune, B300…" value="${esc(state.filters.q)}"></div><div class="filter"><label for="familyFilter">FAMILY</label><select id="familyFilter">${selectOptions(['All','Rack','Scale-up','Tower','Edge','Dense','Neptune','AI'],state.filters.family)}</select></div><div class="filter"><label for="vendorFilter">HOST CPU</label><select id="vendorFilter">${selectOptions(['All','AMD','Intel'],state.filters.vendor)}</select></div><div class="filter"><label for="useFilter">WORKLOAD</label><select id="useFilter">${selectOptions(['All','General compute','Virtualization','Data & storage','AI & GPUs','Edge & branch','HPC & density'],state.filters.use)}</select></div></div><div class="results-info"><p id="modelCount" aria-live="polite"></p><button class="text-btn" data-reset-filters>Reset filters ↻</button></div><div class="model-grid" id="modelGrid"></div><div class="compare-tray" id="compareTray" hidden><p id="compareStatus" aria-live="polite"></p><div class="button-row"><button class="btn compact ghost" data-clear-compare>Clear</button><button class="btn compact primary" id="compareButton" data-compare>Compare selected →</button></div></div>
 <div class="warning"><strong>“Up to” describes a particular configuration.</strong> Drive, memory and GPU maxima can require different builds. Workload labels are learning aids, not benchmarks. Rack filtering includes the AI and scale-up rack platforms.</div>
 <section class="section" id="history"><h2>Where the rest of Lenovo fits</h2><div class="history-list"><article><span class="badge accent">THE INFERENCE “i”</span><h3 style="margin-top:16px">SR650i, SR675i and SE455i</h3><p>These names identify defined inference configurations based on SR650a V4, SR675 V3 and SE455 V3. They are useful shortcuts to a solution design, not a promise that every possible GPU configuration is identical.</p>${sourceLink('sr650a','See the SR650i configuration')}</article><article><span class="badge accent">BEYOND AMD AND INTEL</span><h3 style="margin-top:16px">NVIDIA Grace and Blackwell</h3><p>SC777 V4 Neptune combines Arm-based NVIDIA Grace CPUs with Blackwell GPUs. Lenovo also offers rack-scale AI systems. The two CPU columns in this guide are a starting point, not the entire portfolio.</p>${sourceLink('sc777','Explore SC777 V4 Neptune')}</article></div><div class="lesson" style="margin-top:16px"><span class="badge warn">LIFECYCLE CONTEXT</span><h3 style="margin-top:14px">Existing systems still matter.</h3><p>SR685a V3 was withdrawn from marketing in Lenovo’s September 26, 2026 update. Its profile remains here to explain AMD MI300X and NVIDIA eight-GPU configurations you may encounter in an installed estate.</p><p>A withdrawal notice is not automatically the end of support. Earlier SR630 / SR650 generations, additional entry towers and racks, other dense nodes, and ThinkAgile solutions extend beyond this selected set.</p>${sourceLink('sr685a','Read the model’s withdrawal notice')}</div></section><div class="next-lesson"><p>Next: compare host CPU platforms without losing the system context.</p><a class="btn primary" href="#platforms">AMD & Intel →</a></div>`;}
// END lineup
// BEGIN platforms
function platforms(){return `${intro('03 / THE CPU PLATFORM MAP','Start with the processor. See the whole system.','Lenovo spans AMD EPYC, Intel Xeon and compact edge processors. Socket count, memory topology and expansion define what the platform can do.')}
 <div class="two-col"><article class="vendor-panel amd"><span class="badge amd">AMD CPU PLATFORMS</span><h2>EPYC</h2><p>Entry, edge and mainstream EPYC families appear in this guide. Their CPU sockets and memory designs are not interchangeable.</p><ul><li><b>4004 / 4005:</b> ST45 V3 entry tower.</li><li><b>8004:</b> SE455 V3 edge system.</li><li><b>9004 / 9005:</b> mainstream V3 racks, SD535 dense nodes, SD665 Neptune and qualified AI systems.</li><li><b>One or two sockets:</b> choose the platform for memory, I/O and workload needs.</li></ul>${modelButtons(['st45','se455','sr635','sr665','sd535','sd665','sr675'])}</article><article class="vendor-panel intel"><span class="badge intel">INTEL CPU PLATFORMS</span><h2>Xeon + Core Ultra</h2><p>Intel choices span small edge nodes, expandable towers, mainstream racks and four-socket systems.</p><ul><li><b>Core Ultra Series 2:</b> compact SE100.</li><li><b>4th / 5th Gen Xeon Scalable:</b> ST650 V3.</li><li><b>Xeon 6:</b> V4 rack and GPU examples.</li><li><b>6900-series:</b> SC750 V4 Neptune nodes.</li><li><b>Four sockets:</b> SR860 V4 scales shared host memory.</li></ul>${modelButtons(['se100','st650','sr630','sr650','sr860','sc750'])}</article></div>
 <div class="takeaway"><span class="symbol">≠</span><div><h3>The CPU logo does not choose the GPU.</h3><p>AMD-host SR675 V3 uses NVIDIA accelerators. Intel-host SR680a V4 uses NVIDIA HGX B300. The withdrawn SR685a V3 documented AMD-host systems with AMD MI300X or NVIDIA HGX builds.</p></div></div>
 <section class="section"><div class="chapter-heading"><h2>The practical platform map</h2><span class="small">Select a model for the specification.</span></div><div class="table-scroll"><table><caption class="visually-hidden">Selected Lenovo platform designs by CPU vendor</caption><thead><tr><th scope="col">Design</th><th scope="col">AMD examples</th><th scope="col">Intel examples</th></tr></thead><tbody>${[['1U · one socket',['sr635'],[]],['2U · one socket',['sr655'],[]],['1U · two sockets',['sr645'],['sr630']],['2U · two sockets',['sr665'],['sr650']],['Four-socket scale-up',[],['sr860']],['Tower',['st45'],['st650']],['Compact edge',['se455'],['se100']],['Dense / supercomputing nodes',['sd535','sd665'],['sc750']],['PCIe GPU-focused servers',['sr675'],['sr650a']],['Eight-GPU systems',['sr685a'],['sr680a']]].map(([label,a,b])=>`<tr><th scope="row">${label}</th><td>${a.length?modelButtons(a):'<span class="support-none">No selected example</span>'}</td><td>${b.length?modelButtons(b):'<span class="support-none">No selected example</span>'}</td></tr>`).join('')}</tbody></table></div><p class="matrix-note">Selected examples, not a Lenovo-wide support matrix or performance ranking. SR685a V3 is withdrawn. Dense / HPC and AI rows include different physical designs, cooling and generations.</p></section>
 <section class="section two-col"><article class="lesson"><div class="eyebrow">P-CORES, E-CORES AND MEMORY</div><h3>Xeon 6 is not one universal configuration.</h3><p>SR630 V4 lists P-core and E-core options. SR650 V4 lists 6500P / 6700P. MRDIMM and CXL support also depend on the CPU and exact server configuration.</p><p>Likewise, 32 DIMM slots do not mean 32 memory channels. SR650 V4 has eight channels per CPU with two DIMM slots per channel; these AMD rack examples use twelve channels per CPU with one slot each.</p>${sourceLink('sr630','SR630 CPU and memory rules')}</article><article class="lesson"><div class="eyebrow">MORE CORES ARE ONLY ONE VARIABLE</div><h3>Find the workload’s actual constraint.</h3><p>A VM host can run out of memory first. A database can be constrained by storage latency or per-core licensing. AI can depend most on GPU memory, interconnects and software.</p><p>Compare application measurements, usable capacity, network bandwidth, power, cooling and support. Neither CPU brand nor socket count is a performance score.</p></article></section>
 <section class="section three-col"><article class="lesson"><div class="big-number">01</div><h3>The embedded controller</h3><p>XCC2 or XCC3 monitors one server and provides remote management. The compact ST45 is an exception: it uses a simpler management design.</p>${sourceLink('st45','ST45 management details')}</article><article class="lesson"><div class="big-number">02</div><h3>The fleet manager</h3><p>XClarity One connects a cloud or local portal to on-premises hubs and supported devices. It handles hardware operations across the fleet.</p>${sourceLink('xc1','XClarity One architecture')}</article><article class="lesson"><div class="big-number">03</div><h3>The workload software</h3><p>Windows Server, Linux and hypervisors run applications and VMs. ThinkAgile validates particular hardware and software stacks together.</p>${sourceLink('os','Check Lenovo’s OS guide')}</article></section><div class="next-lesson"><p>Next: decode drives, GPUs and cooling.</p><a class="btn primary" href="#components">Storage & GPUs →</a></div>`;}
// END platforms
// BEGIN driveLessons
const driveLessons={
 sff:{label:'2.5-inch SFF',art:'',title:'The bay size is the first clue.',text:'SFF usually means a 2.5-inch drive format. SAS, SATA and NVMe describe different interfaces or protocols. The backplane, cabling and controller decide which drives work.',notice:'SD535 V3 has six SFF AnyBay SSD positions per node. SE455 V3 has four front and four optional internal SSDs; those internal drives are not hot-swappable.',ids:['sd535','se455'],source:'se455'},
 lff:{label:'3.5-inch LFF',art:'lff',title:'More physical room for capacity.',text:'LFF usually means a 3.5-inch bay, commonly used for capacity-oriented hard drives. Raw capacity is not usable capacity after RAID, spares and software overhead.',notice:'SR665 V3 documents layouts up to twenty LFF bays across front, middle and rear. ST45 uses non-hot-swap bays; sharing a drive-size label does not imply the same service procedure.',ids:['sr665','st45','st650'],source:'sr665'},
 e3:{label:'E3.S / CXL',art:'e3',title:'One shape family can hold different devices.',text:'E3.S is an EDSFF form factor. An E3.S NVMe SSD is storage; a qualified CXL memory module in an E3.S 2T bay is memory expansion. They perform different jobs.',notice:'SR650 V4 lists E3.S NVMe layouts and separate CXL configurations. CXL requires a qualified CPU, bay configuration and OS; an empty E3.S bay is not sufficient.',ids:['sr650','sr860','sc750'],source:'sr650'},
 e1:{label:'E1.S NVMe',art:'e1',title:'Enterprise flash in a different package.',text:'E1.S and E3.S are different EDSFF shapes. NVMe in both names does not make their carriers or connectors interchangeable.',notice:'SR635 / SR645 V3 have E1.S configurations. SR675 V3 also offers E1.S layouts in specific GPU shuttles; other shuttles use SFF or E3.S.',ids:['sr635','sr645','sr675'],source:'sr675'},
 m2:{label:'M.2 boot / data',art:'m2',title:'Small modules, several possible roles.',text:'M.2 describes the module shape. It may carry SATA or NVMe storage, and its adapter determines RAID and serviceability. A mirrored boot pair can keep main drive bays free for applications.',notice:'SR650 V4 offers internal and hot-swap M.2 options. SE100 uses M.2 for both boot and data, with no SFF or LFF bays.',ids:['sr650','se100'],source:'se100'}
};
// END driveLessons
// BEGIN components
function components(){return `${intro('04 / UNDER THE COVER','Decode storage. Understand acceleration.','Separate the drive format, connection, accelerator design and cooling system. Then put them back together as a qualified server.')}
 <section class="panel"><div class="panel-head"><div><div class="eyebrow">STORAGE EXPLORER</div><h2 style="margin-top:8px">What does the drive label tell you?</h2><p>Select a format to connect the terminology to real platforms.</p></div><span class="badge accent">FORM ≠ PROTOCOL</span></div><div class="storage-lab"><div class="lab-controls" aria-label="Drive formats">${Object.entries(driveLessons).map(([id,d])=>`<button data-drive="${id}" aria-pressed="${state.drive===id}">${d.label}</button>`).join('')}</div><div class="lab-content" id="driveLesson"></div></div></section>
 <div class="two-col section"><article class="lesson"><h3>AnyBay is part of a supported design.</h3><p>Lenovo AnyBay lets a qualified bay support more than one drive interface. You still need the right backplane, cables, controller and drive. Other bays may be NVMe-only or SAS/SATA-only.</p><p>RAID adapters, HBAs and onboard NVMe paths have different roles. Drive cages also compete with PCIe adapters for room and connectivity.</p>${sourceLink('sr665','Storage configurations and controllers')}</article><article class="lesson"><h3>Three kinds of “memory” to keep separate.</h3><p><b>Host DDR5:</b> active working space for CPUs.<br><b>GPU HBM / graphics memory:</b> local accelerator working space.<br><b>SSDs / hard disks:</b> persistent software and data.</p><p>Adding an SSD does not increase GPU HBM. Multiple GPUs need compatible software and communication paths to work on a large model together.</p><a href="#sources/glossary">Explore the terminology →</a></article></div>
 <section class="section"><div class="chapter-heading"><h2>Three ways to add GPU compute</h2><span class="small">The physical design makes a difference.</span></div><div class="three-col"><article class="lesson"><div class="big-number">01</div><h3>Add a qualified PCIe card.</h3><p>Mainstream racks and towers can host selected GPUs for inference, visualization or other parallel work. Card width, power, airflow and riser support all matter.</p>${modelButtons(['sr665','sr650','st650'])}<p class="small muted">A graphics connector or spare slot is not a compatibility guarantee.</p>${sourceLink('gpu','Lenovo GPU qualification tables')}</article><article class="lesson"><div class="big-number">02</div><h3>Choose a GPU-focused chassis.</h3><p>SR650a V4 moves GPUs to the front of a 2U server. AMD-based SR675 V3 uses 3U PCIe GPU shuttles; its former SXM builds remain useful historical examples.</p>${modelButtons(['sr650a','sr675'])}<p class="small muted">SR650a’s two full-power RTX PRO 6000 Blackwell cards and four power-capped cards are different supported builds.</p>${sourceLink('sr650a','GPU power and quantity rules')}</article><article class="lesson"><div class="big-number">03</div><h3>Use an integrated GPU platform.</h3><p>SR680a V4 pairs Intel hosts with an eight-GPU HGX B300 subsystem. The GPU baseboard, links, networking and cooling are part of the system design.</p>${modelButtons(['sr680a'])}<p class="small muted">SXM and OAM modules are physically different from ordinary PCIe cards.</p>${sourceLink('sr680a','Integrated GPU architecture')}</article></div></section>
 <section class="panel section"><div class="panel-head"><div><div class="eyebrow">THE CPU / GPU CROSSOVER</div><h2 style="margin-top:8px">Documented pairings worth remembering</h2></div></div><div class="table-scroll" style="border:0;border-radius:0"><table><caption class="visually-hidden">Lenovo host CPU and accelerator examples</caption><thead><tr><th scope="col">Host CPU</th><th scope="col">Accelerator example</th><th scope="col">Server</th><th scope="col">What to notice</th></tr></thead><tbody>
 <tr><th scope="row">AMD EPYC 9004 / 9005</th><td>NVIDIA H100 NVL / L40S PCIe</td><td>${modelButtons(['sr665'])}</td><td>A general server can pair AMD CPUs with NVIDIA GPUs.</td></tr>
 <tr><th scope="row">AMD EPYC 9004 / 9005</th><td>NVIDIA PCIe; historical 4-GPU HGX</td><td>${modelButtons(['sr675'])}</td><td>H200 NVL and RTX PRO 6000 require EPYC 9005 plus C5WW fans. HGX H200 was withdrawn July 2026.</td></tr>
 <tr><th scope="row">Intel Xeon 6</th><td>NVIDIA H100 NVL / H200 NVL / RTX PRO</td><td>${modelButtons(['sr650a'])}</td><td>GPU quantity and supported wattage are linked.</td></tr>
 <tr><th scope="row">Intel Xeon 6</th><td>8 × NVIDIA HGX B300</td><td>${modelButtons(['sr680a'])}</td><td>Integrated eight-GPU system in an 8U air-cooled chassis.</td></tr>
 <tr><th scope="row">AMD EPYC 8004</th><td>Qualified NVIDIA PCIe GPUs</td><td>${modelButtons(['se455'])}</td><td>Edge environment and I/O-sharing rules constrain the build.</td></tr>
 <tr><th scope="row">Intel Core Ultra</th><td>NVIDIA RTX 2000E Ada</td><td>${modelButtons(['se100'])}</td><td>A compact edge platform with a different host CPU family.</td></tr>
 <tr><th scope="row">AMD EPYC · historical option</th><td>AMD Instinct MI210 PCIe</td><td>${modelButtons(['sr655','sr665','sr675'])}<span class="badge warn">GPU OPTION WITHDRAWN</span></td><td>Up to 3 / 3 / 8 cards respectively; kits and shuttle rules apply. MI210 withdrawal does not retire these host servers.</td></tr>
 <tr><th scope="row">AMD EPYC · historical</th><td>8 × AMD MI300X or NVIDIA H100 / H200</td><td>${modelButtons(['sr685a'])}<span class="badge warn">WITHDRAWN</span></td><td>Existing-system reference; not a current availability claim.</td></tr>
 </tbody></table></div></section>
 <div class="warning"><strong>GPU support belongs to the exact server build.</strong> AMD EPYC does not imply AMD Instinct support. SXM, OAM and PCIe are not interchangeable. Software, power, airflow and GPU population rules matter alongside the model number. ${sourceLink('gpu','Open the GPU summary')}</div>
 <section class="section"><div class="chapter-heading"><h2>Neptune: understand where the heat goes</h2><span class="small">A family of cooling approaches.</span></div><div class="three-col"><article class="lesson"><div class="cooling-glyph" aria-hidden="true">↻</div><h3>Hybrid liquid-to-air</h3><p>A closed liquid circuit carries heat to a radiator; fans move that heat into room air. SR675 V3’s historical SXM model used this approach.</p><p class="small muted">Liquid inside a server does not automatically mean facility-water connections.</p>${sourceLink('sr675','SR675 cooling architecture')}</article><article class="lesson"><div class="cooling-glyph" aria-hidden="true">≈</div><h3>Neptune Core</h3><p>Open-loop options remove heat through a facility-connected cooling system. SR650 V4 has processor-only and compute-complex variants.</p><p class="small muted">Compute Complex Neptune Core also cools memory and voltage regulators; supported configurations differ.</p>${sourceLink('sr650','Processor / compute-complex cooling')}</article><article class="lesson"><div class="cooling-glyph" aria-hidden="true">⇄</div><h3>Purpose-built Neptune</h3><p>AMD SD665 V3 uses 1U two-node trays in a 6U DW612S enclosure. Intel SC750 V4 uses vertical two-node trays in 13U N1380. Both require facility-connected cooling.</p><p class="small muted">DW612S holds up to 12 SD665 nodes; N1380 holds up to 16 SC750 nodes. Each node has independent CPUs and memory.</p>${modelButtons(['sd665','sc750'])}${sourceLink('sd665','SD665 and DW612S design')}</article></div></section>
 <section class="section"><h2>From an option to a supported system</h2><div class="compat-steps"><article class="compat-step"><h3>Exact platform</h3><p>Full model, version, machine type and CPU / GPU build.</p></article><article class="compat-step"><h3>Population rules</h3><p>DIMMs, drives, controllers, risers and adapter combinations.</p></article><article class="compat-step"><h3>Facility needs</h3><p>Power, airflow, coolant, environment and service access.</p></article><article class="compat-step"><h3>Software stack</h3><p>OS, hypervisor, GPU runtime, firmware and driver versions.</p></article></div><p class="small">${sourceLink('os','OS interoperability')} · ${sourceLink('proven','ServerProven compatibility')}</p></section><div class="next-lesson"><p>Ready to connect the dots?</p><a class="btn primary" href="#quiz">Test your knowledge →</a></div>`;}
// END components
// BEGIN sourcesView
function sourcesView(){return `${intro('06 / KEEP LEARNING','Go straight to the evidence.','A source-linked learning snapshot reviewed on October 7, 2026. Original hardware illustrations follow Lenovo’s product figures and simplify the physical details.')}
 <div class="two-col"><article class="lesson"><h3>What this guide covers</h3><p>${models.length} selected rack, tower, scale-up, edge, dense, Neptune and AI platforms. The aim is to understand the design and its CPU, memory, storage, accelerator and management choices.</p><p>The broader portfolio includes additional models and ThinkAgile solutions. This guide is an educational map; the current model guide and compatibility tools determine a deployable configuration.</p></article><article class="lesson"><h3>How changing sources were handled</h3><p>Detailed model guides take priority over broad portfolio tables. SR685a V3 is marked withdrawn following the September 26, 2026 update. Its past GPU configurations remain educational references. MI210 is separately marked as a withdrawn accelerator option on still-current SR655, SR665 and SR675 models.</p><p>Future or planned options are not treated as available. Memory and GPU ceilings are conditional; historical datasheets can lag current qualification. The publication version V3 / V4 alone does not establish lifecycle.</p></article></div>
 <section class="section" id="glossary"><div class="eyebrow">PLAIN-ENGLISH REFERENCE</div><h2 style="margin-top:10px">Keep the acronyms under control.</h2><label class="visually-hidden" for="glossarySearch">Search glossary</label><input class="glossary-search" id="glossarySearch" type="search" placeholder="Find a term: AnyBay, XClarity, Neptune…"><div class="glossary" id="glossaryList">${Object.entries(glossary).map(([term,def])=>`<details data-term="${esc((term+' '+def).toLowerCase())}"><summary>${esc(term)}</summary><p>${def}</p></details>`).join('')}</div><p id="glossaryEmpty" class="muted" hidden>No matching terms. Try a shorter search.</p></section>
 <section class="section"><div class="eyebrow">OFFICIAL SOURCE LIBRARY</div><h2 style="margin-top:10px">Follow the document behind the detail.</h2><p class="muted small">“Reviewed” is the access date for this guide. Verified publication or update dates are labeled separately. Figures are simplified illustrations or logical schematics, not service drawings. Linked documents can change; no source documents were supplied by the user.</p><div class="source-list">${Object.entries(sources).map(([id,s])=>`<article class="source-item" id="source-${id}">${sourceLink(id)}<p>${s.scope}</p><small>${s.date} · ${s.loc}</small></article>`).join('')}</div></section>`;}
// END sourcesView
