// Shared, source-backed processor and memory presentation for every OEM surface.
function memoryScope(m){const p=m.computeMemory;return 'Per '+p.scope+(p.nodesPerChassis?' · '+p.nodesPerChassis+' nodes / chassis':'');}
function memoryDpc(m){const p=m.computeMemory;return p.dpc.length?p.dpc.map(n=>n+'DPC').join(' / '):'Not confirmed';}
function memorySlots(m){const p=m.computeMemory;return p.dimmLabel||(p.dimmSlots===null?'Not confirmed':String(p.dimmSlots));}
function memoryInstalledProcessors(m){const p=m.computeMemory,counts=p.installedCPUCounts;return (counts?.length?counts.join(' or '):'Not confirmed; maximum '+p.maxProcessors)+(p.installedCPUCountsNote?' · '+p.installedCPUCountsNote:'');}
function memoryTypes(m){return m.computeMemory.memoryTypes?.length?m.computeMemory.memoryTypes.join(' / '):'See OEM population guide';}
function memoryMetrics(m){
 const p=m.computeMemory;
 return `<section class="memory-highlights" aria-label="Processor and memory essentials for ${esc(m.name)}"><dl class="platform-facts"><div><dt>Max processors</dt><dd>${p.maxProcessors}</dd></div><div><dt>DIMM slots</dt><dd class="${p.dimmSlots===null&&!p.dimmLabel?'fact-unknown':''}">${p.dimmSlots===null&&!p.dimmLabel?'<span class="unknown-value" aria-label="Not confirmed">—</span>':esc(memorySlots(m))}</dd></div><div><dt>DPC support</dt><dd class="dpc-value ${p.dpc.length?'':'fact-unknown'}">${p.dpc.length?p.dpc.map(n=>`<span>${n}DPC</span>`).join(''):'<span class="unknown-value" aria-label="Not confirmed">—</span>'}</dd></div></dl><p class="memory-scope">${esc(memoryScope(m))} · slots with all processors${p.channelsPerCpu!==null?`<span>${p.channelsPerCpu} memory channels / processor</span>`:''}${p.dimmSlots===null&&!p.dimmLabel||!p.dpc.length?`<span class="memory-condition">${[p.dimmSlots===null&&!p.dimmLabel?'DIMM slots':'',!p.dpc.length?'DPC':''].filter(Boolean).join(' and ')} not confirmed</span>`:''}${p.dpcNote?`<span class="memory-condition">${esc(p.dpcNote)}</span>`:''}</p></section>`;
}
function memoryEvidence(m){
 const p=m.computeMemory;
 return `<details class="memory-evidence"><summary>CPU & memory population details</summary><dl class="memory-detail-facts"><div><dt>Supported installed processors</dt><dd>${esc(memoryInstalledProcessors(m))}</dd></div><div><dt>Memory types</dt><dd>${esc(memoryTypes(m))}</dd></div></dl><p>${esc(p.note)}</p><p><b>1DPC</b> means one DIMM per memory channel; <b>2DPC</b> means two. A slot count is a platform ceiling, not the number of DIMMs installed. Memory type, speed and allowed population depend on the OEM configuration.</p><div class="memory-source-links">${p.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗${s.loc?`<small>${esc(s.loc)}</small>`:''}</a>`).join('')}</div></details>`;
}
function memoryCompareRows(list){return [['Max processors',m=>String(m.computeMemory.maxProcessors)],['Supported installed processors',memoryInstalledProcessors],['DIMM slots',memorySlots],['Channels / processor',m=>m.computeMemory.channelsPerCpu??'Not confirmed'],['DPC support',memoryDpc],['Memory types',memoryTypes],['Count scope',memoryScope],['Population conditions',m=>m.computeMemory.note]].map(([label,value])=>`<tr><th scope="row">${label}</th>${list.map(m=>`<td>${esc(value(m))}</td>`).join('')}</tr>`).join('');}
function memoryLegend(){return `<p class="memory-legend"><b>Read the memory layout:</b> 1DPC = 1 DIMM per channel · 2DPC = 2 DIMMs per channel. Counts are per server or compute node, with all processors installed. Published slot maxima can vary with cooling and memory type.</p>`;}
