// BEGIN hardware
function hardware(shape='rack2',hero=false){
 // Front arrangements follow the product-gallery photographs recorded in physical-supermicro.json.
 // Hidden internals and alternative backplanes are deliberately not inferred from the front.
 const uid='sm-art-'+(++artSerial),metal=`url(#${uid}-metal)`,mesh=`url(#${uid}-mesh)`,darkmesh=`url(#${uid}-darkmesh)`;
 const aliases={rack1:'amd1',rack2:'amd2',lff:'amdcloud',twin:'amdtwin',twinfront:'inteltwin',twin2:'h15twin',blade:'blade',amdblade:'amdblade',tower:'tower',edge:'edge',flash:'petascale',storage:'capacity',gpu4:'pciegpu',gpu5:'amdpcie',gpu8:'instinctair',gpu4liquid:'instinctliquid'};
 const id=shape.startsWith('sm-')?shape.slice(3):(aliases[shape]||shape);
 const rect=(x,y,w,h,fill='#1b2024',stroke='#859198',rad=1)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rad}" fill="${fill}" stroke="${stroke}" stroke-width=".65"/>`;
 const vent=(x,y,w,h,dark=false)=>rect(x,y,w,h,dark?darkmesh:mesh,dark?'#303940':'#9ca9b0');
 const port=(x,y,w=9,h=6,color='#111a22')=>rect(x,y,w,h,color,'#c1ccd1',.4);
 const led=(x,y,color='#71cf97')=>`<circle cx="${x}" cy="${y}" r=".9" fill="${color}"/>`;
 const handle=(x,y,w,h)=>`<path d="M${x} ${y+h}v-${h-2}q0 -2 2 -2h${w-4}q2 0 2 2v${h-2}" fill="none" stroke="#c5cdd1" stroke-width="2.7"/>`;
 const drive=(x,y,w,h,vertical=false,latch='#e4ad30')=>{
  const inset=Math.min(1.5,w*.18);
  let s=rect(x,y,w,h,'#151b20','#606d75',.8)+rect(x+inset,y+1.5,w-inset*2,h-3,'#283138','#10171b',.5);
  if(vertical){const pad=Math.min(2,w*.16),count=w>=8?2:1,gap=count===2?.8:0,cell=(w-pad*2-gap)/count;for(let i=0;i<count;i++)s+=rect(x+pad+i*(cell+gap),y+h*.3,cell,h*.48,'#0c1115','#0c1115');s+=rect(x+pad,y+h-5,w-pad*2,3,latch,latch,.3);}
  else {s+=`<path d="M${x+3} ${y+h*.35}h${w-10}M${x+3} ${y+h*.7}h${w-10}" stroke="#080d11" stroke-width="1.6"/>`;s+=rect(x+w-6,y+2,3.7,Math.max(1,h-4),latch,latch,.3);}
  return s;
 };
 // All three planes share the same depth vector; no disconnected lower side panel.
 const shell=(x,y,w,h,depth=13)=>`<path d="M${x} ${y}l12 -${depth}h${w}l-12 ${depth}z" fill="${metal}" stroke="#a9b5bc" stroke-width=".65"/><path d="M${x+w} ${y}l12 -${depth}v${h}l-12 ${depth}z" fill="#77858f" stroke="#b5c1c8" stroke-width=".6"/>`+rect(x,y,w,h,metal,'#bdc9d0',1.4)+rect(x+2,y+2,11,h-4,'#b7c1c7','#85959f')+rect(x+w-13,y+2,11,h-4,'#bac5cc','#85959f')+led(x+7,y+8,'#d7575c')+led(x+7,y+12)+`<path d="M${x+5} ${y+h-6}h5M${x+w-10} ${y+h-6}h5" stroke="#4f626f" stroke-width="2"/>`;
 const fan=(cx,cy,r)=>`<circle cx="${cx}" cy="${cy}" r="${r}" fill="#46565f" stroke="#889ca6" stroke-width="1.3"/><path d="M${cx-r*.64} ${cy}h${r*1.28}M${cx} ${cy-r*.64}v${r*1.28}" stroke="#72858e" stroke-width="${r*.24}"/><circle cx="${cx}" cy="${cy}" r="${r*.24}" fill="#26363f"/>`;
 const rack=(model,x=16,y=80,w=326)=>{
  const one=model==='amd1'||model==='intelcloud',h=one?33:66; let b=shell(x,y,w,h),fx=x+16,fw=w-32;
  if(one){const dw=fw/6;for(let col=0;col<4;col++)for(let row=0;row<2;row++)b+=drive(fx+col*dw,y+3+row*13.5,dw-1.6,12.5);for(let col=4;col<6;col++)b+=vent(fx+col*dw,y+3,dw-1.6,26,true);b+=port(model==='intelcloud'?x+w-10:x+4,y+18,5,3,'#2583b2');}
  else if(model==='amdcloud'){for(let row=0;row<3;row++)for(let col=0;col<4;col++)b+=drive(fx+col*fw/4,y+3+row*20,fw/4-2,18,false,'#44474a');b+=handle(x+3,y+17,7,28)+handle(x+w-10,y+17,7,28);}
  else {b+=vent(fx,y+3,fw/3-2,60,true)+vent(fx+fw*2/3+1,y+3,fw/3-2,60,true);for(let col=0;col<8;col++)b+=drive(fx+fw/3+col*(fw/3)/8,y+3,(fw/3)/8-1,60,true);}
  return b;
 };
 const moduleFace=(x,y,w,h,amd=false)=>{
  let b=rect(x,y,w,h,metal,'#d4dde1',.4)+vent(x+1.5,y+10,w-3,h*(amd?.35:.54));
  b+=led(x+4,y+4,'#ba5358')+led(x+w-4,y+4)+rect(x+2,y+6,w-4,2,'#9aa7ae','#86949c');
  if(amd){for(let j=0;j<6;j++)b+=drive(x+2,y+h*.47+j*h*.044,w-4,h*.038,false,'#d49b2d');b+=vent(x+2,y+h*.76,w-4,h*.19);b+=rect(x+w-4,y+h*.8,2,h*.12,'#974551','#974551');}
  else{for(let j=0;j<4;j++)b+=drive(x+2+j*(w-4)/4,y+h*.69,(w-4)/4-.5,h*.27,true);b+=rect(x+1,y+h*.61,2,h*.06,'#9d3f50','#9d3f50');}
  return b;
 };
 const enclosure=(amd=false,highlight=false)=>{const x=44,y=amd?24:38,w=262,h=amd?163:137;let b=shell(x,y,w,h,13);for(let i=0;i<10;i++){const bx=x+17+i*22.9;b+=`<g opacity="${highlight&&i!==4?.47:1}">${moduleFace(bx,y+3,21.7,h-6,amd)}</g>`;if(highlight&&i===4)b+=rect(bx-1,y+1,23.7,h-2,'none','#ebba53',1);}return b;};
 const miniTower=()=>{const x=105,y=31,w=91,h=157;let b=`<path d="M${x} ${y}l47 -15h${w}l-47 15z" fill="#424b50" stroke="#6a7880" stroke-width=".7"/><path d="M${x+w} ${y}l47 -15v${h}l-47 15z" fill="#2f383e" stroke="#62717b" stroke-width=".7"/>`+rect(x,y,w,h,'#252b2f','#72828b',2);for(let i=0;i<5;i++)b+=rect(x+5,y+10+i*6,81,3.5,'#10171b','#344049');for(let i=0;i<15;i++)b+=rect(x+5,y+61+i*5.7,81,3.2,'#11181d','#344049');b+=rect(x+5,y+42,81,14,'#343d43','#11171c')+port(x+9,y+46,9,5,'#1b72a4')+port(x+23,y+46,9,5,'#1b72a4')+`<circle cx="${x+76}" cy="${y+49}" r="4" fill="#141a1e" stroke="#6f7e86"/>`+led(x+64,y+49);return b;};
 let b='',label='Supermicro physical schematic';
 if(id==='portfolio'){b=`<g transform="translate(28 -28) scale(.88)">${rack('amd1',16,88)}</g><g transform="translate(11 0) scale(.94)">${rack('amd2',16,88)}</g>`;label='Supermicro Hyper portfolio: 1U eight-bay front above 2U central eight-bay front; representative configurations';}
 else if(['intelhyper','amd1','amd2','amdcloud','intelcloud'].includes(id)){b=rack(id,16,id==='amd1'||id==='intelcloud'?92:76);label=`${id==='amdcloud'?'AS-2015CS-TNR 2U CloudDC with twelve LFF carriers in four columns and three rows':id==='amd1'||id==='intelcloud'?'Supermicro 1U with eight horizontal SFF carriers and right-hand mesh blanks':'Supermicro 2U Hyper with central eight vertical SFF carriers and mesh blanks on both sides'}; documented front configuration, cover closed`;}
 else if(['amdtwin','inteltwin','h15twin'].includes(id)){
  b=shell(15,77,326,66);const h15=id==='h15twin';for(let n=0;n<(h15?2:4);n++){const x=31+(n%2)*148,y=80+(h15?0:Math.floor(n/2)*31),h=h15?60:29;b+=rect(x,y,146,h,metal,'#747f87',.4);
   if(id==='amdtwin'){for(let r=0;r<2;r++)for(let c=0;c<3;c++)b+=drive(x+5+c*45,y+2+r*12.7,43,11.5);}
   else if(id==='inteltwin'){for(let c=0;c<8;c++)b+=drive(x+5+c*11.2,y+2,9.7,24,true,'#c99532');b+=port(x+103,y+4,10,7)+port(x+116,y+4,9,7)+port(x+130,y+4,9,7)+port(x+102,y+16,9,4,'#287ead')+port(x+116,y+16,9,4,'#287ead');}
   else{b+=vent(x+4,y+3,71,24)+vent(x+78,y+3,63,24);b+=port(x+82,y+5,22,7)+port(x+109,y+5,22,7)+port(x+82,y+16,20,7)+port(x+109,y+16,20,7);for(let r=0;r<4;r++)for(let c=0;c<2;c++)b+=drive(x+5+c*54,y+32+r*6.2,52,5.2);b+=port(x+117,y+36,17,7)+port(x+117,y+47,8,4,'#328abc');}
   b+=handle(x+1,y+5,4,h-9);
  }label=id==='h15twin'?'AS-2117GT7-DNF two-node GrandTwin, front I/O and optional eight horizontal SFF carriers per node':id==='inteltwin'?'SYS-212GT-HNF four-node GrandTwin, two by two node layout with eight E1.S carriers and front I/O per node':'AS-2115GT-HNTR four-node GrandTwin; six SFF carriers per node, each arranged three across and two high';
 }
 else if(id==='bladechassis'){b=enclosure();label='6U SuperBlade enclosure with ten tall single-width blades; four vertical E3.S carriers at the foot of each blade';}
 else if(id==='amdblade'){b=enclosure(true,true);label='SBA-817V7-1N family context: official gallery shows an 8U SuperBlade enclosure; one blade position highlighted. Front population is representative, not a confirmed isolated sled configuration';}
 else if(id==='blade'){
  // Blade remains upright as installed; long side casing distinguishes a sled from a tower.
  b=`<path d="M103 37L257 17V160L103 180Z" fill="${metal}" stroke="#8c9ca5"/><path d="M80 37L234 17h23L103 37Z" fill="#c4cdd1" stroke="#8c9ca5"/>`;
  b+=`<path d="M126 50L246 34M126 166L246 150" stroke="#8f9ba3" stroke-width="1"/>`+moduleFace(80,37,23,143)+rect(250,54,8,75,'#37433e','#70816e');
  label='SBI-622B-1NE34 single-width compute blade, upright installed orientation, with long sled casing and four vertical E3.S front carriers; requires a compatible 6U enclosure';
 }
 else if(id==='tower'||id==='amdentry'){b=miniTower();label=(id==='tower'?'SYS-531R-I':'AS-3015A-I')+' mini-tower: horizontal black front louvers above and below central USB and power strip; closed side panel';}
 else if(id==='edge'){
  b=shell(17,88,322,33,29);for(let i=0;i<2;i++){let x=34+i*48;b+=vent(x,91,45,26)+port(x+14,95,16,16)+handle(x+8,94,25,24);}b+=vent(134,91,115,26)+port(161,92,15,7)+port(159,103,12,4,'#267dac')+port(176,103,12,4,'#267dac')+port(191,103,12,4,'#267dac')+port(210,106,16,7,'#536caa')+vent(252,91,68,11)+vent(252,105,68,12);
  label='AS-1115S-FWTRT compact 1U front-I/O WIO system: two power supplies on the left, central motherboard I/O and right expansion blanks; no external drive bank';
 }
 else if(id==='petascale'){
  b=shell(16,92,326,33);b+=vent(32,95,18,26)+vent(306,95,19,26);for(let c=0;c<4;c++)for(let r=0;r<4;r++)b+=drive(54+c*62,95+r*6.6,59,5.6);label='SSG-122B-NE316R 1U Petascale: sixteen horizontal E3.S carriers, arranged in four stacks of four';
 }
 else if(id==='capacity'){
  // One connected chassis volume. The drive field is recessed into its top,
  // while a flat rear cover stays in the same plane instead of resembling a raised lid.
  const top=(u,v,w,d,fill,stroke='#72848e')=>`<path d="M${28+u+v*.575} ${103-v}l${w} 0l${d*.575} -${d}h-${w}z" fill="${fill}" stroke="${stroke}" stroke-width=".65"/>`;
  b=`<path d="M302 103L348 23V101L302 181Z" fill="#677d8c" stroke="#9aadb9" stroke-width=".75"/>`+top(0,0,274,80,metal,'#a6b7c2');
  b+=top(10,5,254,37,'#111b22','#7f929d')+top(5,45,264,31,'#b0bfc8','#91a4b0');
  for(let row=0;row<3;row++)for(let col=0;col<15;col++){const u=14+col*16.6,v=7+row*11;b+=top(u,v,14.8,9,'#2c3841','#72818b')+top(u+1.8,v+1.2,11.2,1.4,col===7?'#5389b4':'#a08a8e','#667780');}
  b+=rect(28,103,274,78,metal,'#b5c3cd',1)+vent(42,108,246,68,true)+handle(33,116,7,52)+handle(290,116,7,52);
  for(let i=0;i<15;i++)b+=rect(48+i*16,115,2.5,53,'#6b7e88','#60727d',.5);
  b+=`<ellipse cx="164" cy="142" rx="13" ry="4.8" fill="#c9d9d2" stroke="#498c6c" stroke-width="1.3"/><path d="M157 142h14" stroke="#5f8175" stroke-width="1.5"/>`+led(35,109,'#d35a67')+led(35,112);
  label='SSG-542B-E1CR90 deep 4U top-loading storage chassis: recessed forward drive field, flat rear cover and connected full-depth side; only part of the ninety-drive field shown';
 }
 else if(id==='pciegpu'||id==='amdpcie'){
  const five=id==='amdpcie',x=five?35:24,y=five?37:55,w=five?281:301,h=five?142:122; b=shell(x,y,w,h);const fx=x+16,fw=w-32;
  if(five){for(let i=0;i<5;i++){const fanx=fx+i*fw/5;b+=vent(fanx,y+4,fw/5-1.5,52)+fan(fanx+fw/10,y+30,18);}b+=vent(fx,y+60,fw,22);}
  else for(let i=0;i<3;i++)b+=vent(fx+i*fw/3,y+4,fw/3-2,51,true);
  const dy=five?y+88:y+60,dh=five?49:57;for(let i=0;i<24;i++)b+=drive(fx+i*fw/24,dy,fw/24-.8,dh,true,i<(five?4:8)?'#e7ae32':'#8b596b');b+=handle(x+3,y+12,7,39)+handle(x+w-10,y+12,7,39);label=five?'AS-5126GS-TNRT 5U PCIe GPU chassis: five upper fan grilles, a horizontal ventilation strip and 24-position lower SFF front; source-photo drive population':'SYS-421GE-TNRT 4U PCIe GPU chassis: three upper mesh sections over a 24-position vertical SFF front; source-photo drive population';
 }
 else if(id==='instinctair'){
  b=shell(65,20,217,175);b+=vent(80,25,187,84)+rect(80,113,187,22,metal,'#82949e');b+=handle(91,117,40,14)+handle(214,117,40,14);for(let c=0;c<5;c++)for(let r=0;r<2;r++)b+=drive(80+c*37.5,139+r*9,35.7,8,false,c===4?'#865164':'#dfac34');for(let i=0;i<5;i++){const x=80+i*37.5;b+=vent(x,160,35.8,30)+fan(x+17,175,10.5)+rect(x+29,167,3,12,'#d4dad8','#a3b1b5');}label='AS-8126GS-TNMR 8U Instinct air-cooled system: large upper mesh, host service tray, eight SFF plus two SATA positions, and five lower fan modules';
 }
 else if(id==='instinctliquid'){
  b=shell(34,49,290,117,31);b+=vent(50,53,258,49)+vent(50,106,258,25);for(let c=0;c<4;c++)for(let r=0;r<2;r++)b+=drive(50+c*54,137+r*10.5,52,9);b+=vent(268,137,40,20)+port(277,141,12,5,'#486a9b');
  // Soft parallel bends retain the source's front coolant leads without
  // crossing one another or leaving detached, bright connector fragments.
  for(const [x,y,ex,ey] of [[78,77,66,172],[111,77,100,177],[248,77,243,177],[282,77,277,172],[156,115,148,189],[187,115,179,189]]){
   const hose=`M${x} ${y+3}C${x} ${y+24} ${ex} ${y+28} ${ex} ${ey}`;
   b+=`<circle cx="${x}" cy="${y}" r="5" fill="#17242c" stroke="#8da2af" stroke-width="1.3"/><path d="${hose}" fill="none" stroke="#657782" stroke-width="6" stroke-linecap="round"/><path d="${hose}" fill="none" stroke="#202d36" stroke-width="3.6" stroke-linecap="round"/>`+rect(ex-2.6,ey-1,5.2,7,'#768b98','#344650',.7);
  }label='AS-4126GS-NMR-LCC 4U liquid-cooled Instinct system: six attached, curved front coolant leads, upper mesh and lower eight-SFF bank; hoses shortened for the schematic';
 }
 else if(id==='hgx'||id==='amdhgx'){
  b=shell(65,20,217,175);b+=vent(80,24,187,37);for(let i=0;i<8;i++)b+=port(85+i*23,39,14,6);b+=vent(80,66,187,84)+rect(80,154,187,36,metal,'#899da7');b+=vent(139,156,62,32)+vent(82,156,54,11)+vent(204,156,60,11);for(let c=0;c<4;c++){b+=drive(89+c*10.8,170,9.5,19,true,'#927749');b+=drive(207+c*10.8,170,9.5,19,true,'#927749');}b+=port(251,173,11,5)+port(251,182,11,4,'#2d83ba');label=(id==='hgx'?'SYS-822GS-NB3RT':'AS-8126GS-NB3RT')+' 8U HGX B300: eight upper network apertures, large central GPU-tray mesh, and split lower E1.S banks around the host service panel';
 }
 else if(id==='gaudi'){
  b=shell(65,20,217,175);b+=vent(80,25,187,91)+rect(80,117,187,14,metal,'#8396a0');for(let i=0;i<6;i++)b+=port(86+i*29,120,16,7);b+=vent(80,135,187,17)+port(223,140,10,5)+port(237,140,10,5,'#377eaa')+port(250,140,12,5);b+=vent(80,155,55,35)+vent(214,155,53,35);for(let i=0;i<8;i++)b+=drive(138+i*9.2,155,8.2,35,true);label='SYS-822GA-NGR3 8U Gaudi 3: large upper accelerator-tray grille with six OSFP apertures, host service strip, and central eight vertical SFF carriers below';
 }
 else {b=rack('amd2');label='Representative Supermicro Hyper eight-SFF front schematic';}
 return `<svg viewBox="0 0 360 210" role="img" aria-label="${label}"><defs><linearGradient id="${uid}-metal" x2=".3" y2="1"><stop stop-color="#dbe2e5"/><stop offset=".45" stop-color="#b2bfc7"/><stop offset="1" stop-color="#778b99"/></linearGradient><pattern id="${uid}-mesh" width="5.2" height="5.6" patternUnits="userSpaceOnUse"><rect width="5.2" height="5.6" fill="#adbdc7"/><circle cx="2.6" cy="2.8" r="1.35" fill="#586c78"/></pattern><pattern id="${uid}-darkmesh" width="5.2" height="5.6" patternUnits="userSpaceOnUse"><rect width="5.2" height="5.6" fill="#33454f"/><circle cx="2.6" cy="2.8" r="1.35" fill="#15232c"/></pattern></defs>${b}</svg>`;
}
// END hardware
// BEGIN architecture
function architecture(){
 let svg='<defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".6" fill="#526b7e" opacity=".45"/></pattern></defs><rect width="1000" height="540" fill="#0b1622"/><rect width="1000" height="540" fill="url(#grid)"/>';
 const box=(x,y,w,h,label)=>`<rect class="enclosure" x="${x}" y="${y}" width="${w}" height="${h}" rx="12"/><text class="tiny" x="${x+18}" y="${y+25}">${label}</text>`;
 if(state.mode==='rack'){
  svg+=box(60,153,880,345,'AS-2126HS-TN · HYPER 2U · LOGICAL COMPONENT GROUPS');
  svg+='<path class="trace management" d="M210 103v98"/><path class="trace" d="M800 103v98M785 253v35H612v34M243 348h30M439 348h92M697 348h33M350 374v28H288v27M612 374v28h142v27"/>';
  svg+=node('fleet',60,42,300,61,'Supermicro Server Manager','Fleet hardware operations');svg+=node('network',670,42,270,61,'External network','Workload traffic');
  svg+=node('bmc',93,201,234,52,'Embedded BMC','Hardware management');svg+=node('nic',670,201,234,52,'AIOM network adapter','Qualified OCP NIC');
  svg+=node('ram',93,322,150,52,'DDR5 DIMMs','CPU 1 memory');svg+=node('cpu',273,322,166,52,'EPYC CPU 1','9004 / 9005');svg+=node('cpu',531,322,166,52,'EPYC CPU 2','9004 / 9005');svg+=node('ram',730,322,174,52,'DDR5 DIMMs','CPU 2 memory');
  svg+=node('drives',93,429,390,47,'Drive bays + backplane','SFF NVMe / SATA layouts');svg+=node('pcie',558,429,346,47,'PCIe expansion','Qualified GPUs and I/O');
 }else if(state.mode==='blade'){
  svg+=node('bladechassis',60,29,345,58,'6U SuperBlade enclosure','SBE-610J / J2');svg+=node('network',611,29,329,58,'External workload network','Uplinks from enclosure modules');
  svg+=box(60,130,880,369,'TEN SINGLE-WIDTH POSITIONS · EACH BLADE IS AN INDEPENDENT SERVER');
  svg+='<path class="trace management" d="M247 203H39V350h51"/><path class="trace" d="M777 87v88M672 231v33H127M127 264h738"/>';
  svg+=node('cmm',91,175,280,56,'Chassis management','CMM + blade-local BMCs');svg+=node('bladefabric',460,175,445,56,'25GbE switch / pass-through modules','Shared enclosure networking');
  for(let i=0;i<10;i++){const x=91+i*82;svg+=`<path class="trace" d="M${x+36} 264v42"/>`;svg+=node('blade',x,306,73,94,'','',{aria:'Compute blade '+(i+1),content:`<text x="${x+36.5}" y="331" text-anchor="middle" class="label">${String(i+1).padStart(2,'0')}</text><text x="${x+36.5}" y="354" text-anchor="middle" class="sublabel">2 CPUs</text><text x="${x+36.5}" y="375" text-anchor="middle" class="sublabel">Own OS</text>`});}
  svg+=node('bladepower',91,437,814,38,'','',{content:'<text x="498" y="461" text-anchor="middle" class="sublabel">SHARED POWER + COOLING · LOCAL CPU, MEMORY AND STORAGE IN EACH BLADE</text>'});
 }else{
  svg+=box(60,112,880,386,'AS-8126GS-TNMR · 8U AIR-COOLED · MI350X EXAMPLE');
  svg+=node('network',603,26,337,56,'External AI cluster network','Connect other systems and storage');
  svg+='<path class="trace" d="M770 82v76M520 190h69M350 221v29M706 221v29M93 190H78v269h15"/>';
  svg+=node('host',93,158,427,63,'2 × EPYC + host DDR5','CPU control and data preparation');svg+=node('aiio',589,158,317,63,'PCIe + network adapters','Host links and scale-out I/O');
  svg+='<rect x="94" y="250" width="811" height="177" rx="10" fill="#102a2b" stroke="#426f67" stroke-dasharray="4 4"/>';
  for(let i=0;i<8;i++){const x=111+i*97;svg+=node('gpu',x,270,86,61,'GPU '+(i+1),'MI350X');svg+=`<path class="trace gpu-trace" d="M${x+43} 331v27"/>`;}
  svg+=node('infinity',112,358,776,47,'Infinity Fabric · GPU-to-GPU connections','Eight OAM accelerators, each with local HBM');
  svg+=node('aistorage',93,443,386,33,'','',{content:'<text x="286" y="465" text-anchor="middle" class="sublabel">LOCAL NVMe / SATA + M.2 STORAGE</text>'});
  svg+=node('cooling',525,443,381,33,'','',{content:'<text x="715.5" y="465" text-anchor="middle" class="sublabel">CHASSIS POWER + AIR COOLING</text>'});
 }
 svg+='<text class="tiny" x="60" y="525">LOGICAL SCHEMATIC · PLACEMENT AND CONNECTIONS SIMPLIFIED · NOT A WIRING PLAN</text>';
 $('#diagramMount').innerHTML=`<svg class="diagram" viewBox="0 0 1000 540" role="group" aria-label="Interactive Supermicro ${state.mode} system diagram">${svg}</svg>`;
 $('#diagramBlurb').innerHTML={rack:`A complete rack server has local compute, storage, networking and management. This tour uses the AMD 2U Hyper as its example. ${sourceLink('amd2','Hyper specifications')}`,blade:`Blades share more infrastructure than a standalone rack. Switches and pass-through modules are configuration choices; the drawing groups them by role. ${sourceLink('bladechassis','6U enclosure architecture')}`,ai:`Host CPUs coordinate work; OAM GPUs execute accelerator workloads; network adapters connect servers. The GPU links are grouped, not drawn lane by lane. ${sourceLink('instinctair','Eight-GPU system')}`}[state.mode];
 $$('#modeSwitch button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode)));
 const ids=$$('[data-concept]',$('#diagramMount')).map(n=>n.dataset.concept);if(!ids.includes(state.concept))state.concept={rack:'cpu',blade:'bladechassis',ai:'gpu'}[state.mode];setConcept(state.concept);
}
// END architecture
// BEGIN overview
function overview(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">AN INTERACTIVE GUIDE TO SUPERMICRO</div><h1>A world of servers.<br><em>Know the building blocks.</em></h1><p>Hyper. Twin. SuperBlade. And a lot of AI. Find your way through the families, decode the model names, and see how CPUs, drives and accelerators fit together.</p><div class="button-row"><a class="btn primary" href="#lineup">Explore the servers <span>↗</span></a><button class="btn ghost" data-scroll="systemMap">Take the system tour <span>↓</span></button></div><div class="source-note">Based on ${sourceLink('portfolio','Supermicro documentation')} and individual model specifications.<br>${models.length} selected platforms · reviewed 09 Oct 2026.</div></div><div class="hero-art"><div class="hero-stack">${hardware('portfolio',true)}</div><div class="art-label">SUPERMICRO HYPER · ILLUSTRATIVE FRONT VIEWS</div></div></section>
 <div class="chapter-heading"><h2>Start with the shape of the system</h2><span class="small">Six paths through a broad portfolio.</span></div><section class="family-grid supermicro-families" aria-label="Supermicro hardware families">
 ${[['Rack','01 / FLEXIBLE INFRASTRUCTURE','rack2','Hyper & CloudDC','Self-contained racks for VMs, databases and everyday compute.','1U / 2U · AMD or Intel'],['Twin','02 / MANY NODES, ONE CHASSIS','twin','Twin architecture','Independent servers share an enclosure for dense scale-out compute.','GrandTwin · 2 or 4 nodes'],['Blade','03 / SHARED INFRASTRUCTURE','bladechassis','SuperBlade','Compute modules share enclosure power, cooling and networking.','6U / 8U enclosures'],['Storage','04 / FLASH OR CAPACITY','storage','Storage systems','From dense E3.S flash to deep top-loading drive arrays.','Petascale · 90-bay storage'],['Compact','05 / CLOSER TO THE WORK','tower','Edge & tower','Short-depth racks and office-friendly systems for smaller sites.','EPYC 4005 / 8005 · entry Xeon'],['AI','06 / ACCELERATED COMPUTING','gpu8','GPU & AI systems','PCIe cards, integrated OAM / SXM systems and liquid-cooled designs.','NVIDIA · AMD · Intel']].map(([family,num,shape,title,desc,chip])=>`<button class="family-card" data-family="${family}"><span class="over">${num}</span><span class="arrow">↗</span><div class="hardware">${hardware(shape)}</div><h3>${title}</h3><p>${desc}</p><div class="chip-row"><span class="badge">${chip}</span></div></button>`).join('')}</section>
 <section class="two-col section"><article class="lesson"><div class="eyebrow">READ THE NAME</div><h3 style="margin-top:12px">AS-2126HS-TN</h3><div class="name-decoder"><div class="name-piece">AS<small>AMD A+ system</small></div><div class="name-piece">2126<small>Chassis + platform</small></div><div class="name-piece">HS-TN<small>Design + options</small></div></div><p>In this naming scheme: <b>2</b> is 2U; <b>1</b> identifies the 2.5-inch / EDSFF chassis class; <b>2</b> denotes dual processors; <b>6</b> is a Supermicro platform-generation field. <b>H</b> identifies Hyper.</p><p>Keep the full suffix when checking parts. That “6” does <b>not</b> mean sixth-generation EPYC; this model supports 9004 / 9005.</p>${sourceLink('naming','Open the naming convention')}</article><article class="lesson"><div class="eyebrow">FAMILY ≠ CPU GENERATION</div><h3 style="margin-top:12px">Three layers to read together.</h3><p><b>Hyper / GrandTwin / SuperBlade:</b> the system design.<br><b>X14 / H14 / H15:</b> Supermicro platform generations.<br><b>Xeon 6 / EPYC 9005 / EPYC 9006:</b> host CPU families.</p><p>New generations coexist with established designs. This guide includes an H15 EPYC 9006 GrandTwin alongside SP5 and earlier Xeon platforms to make those differences visible.</p>${sourceLink('h15','H15 portfolio announcement')} · ${sourceLink('portfolio','Intel platform families')}</article></section>
 <section class="panel section" id="systemMap"><div class="panel-head"><div><div class="eyebrow">THE SYSTEM, CONNECTED</div><h2 style="margin-top:8px">Open up three different designs.</h2><p>Choose a system, then select any component to learn what it does.</p></div><div class="segmented" id="modeSwitch" aria-label="Supermicro system mode"><button data-mode="rack" aria-pressed="true">Hyper rack</button><button data-mode="blade" aria-pressed="false">SuperBlade</button><button data-mode="ai" aria-pressed="false">Instinct AI</button></div></div><div class="diagram-scroll"><div id="diagramMount"></div></div><div class="diagram-legend"><span><i></i>Workload / component connection</span><span><i style="background:var(--purple)"></i>Management connection</span><span>Tap or use Tab + Enter to inspect</span></div><div class="diagram-blurb" id="diagramBlurb"></div><div class="detail-panel" id="partDetail" aria-live="polite"></div></section>
 <section class="three-col section"><article class="lesson"><div class="big-number">01</div><h3>Count servers, then sockets.</h3><p>A four-node Twin is four computers. A dual-socket Hyper is one computer with two CPUs. A SuperBlade chassis contains independent servers.</p></article><article class="lesson"><div class="big-number">02</div><h3>Separate host from accelerator.</h3><p>AMD EPYC and Intel Xeon run the host. NVIDIA, AMD Instinct and Intel Gaudi options depend on the complete server design.</p></article><article class="lesson"><div class="big-number">03</div><h3>Read the exact configuration.</h3><p>Board revision, risers, drive layout, power and cooling can change compatibility. Individual “up to” values are not a combined parts list.</p></article></section><div class="next-lesson"><p>Next: meet the models behind those families.</p><a class="btn primary" href="#lineup">Explore the lineup →</a></div>`;}
// END overview
// BEGIN lineup
function lineup(){return `${intro('02 / THE HARDWARE EXPLORER','Make sense of the model numbers.','Explore '+models.length+' representative platforms. Filter by physical design, host CPU or workload; open a profile or compare up to three side by side.')}
 <div class="filterbar"><div class="filter search"><label for="modelSearch">SEARCH THE LINEUP</label><input id="modelSearch" type="search" placeholder="Try Hyper, MI350X, E3.S, 9006…" value="${esc(state.filters.q)}"></div><div class="filter"><label for="familyFilter">FAMILY</label><select id="familyFilter">${selectOptions(['All','Rack','Twin','Blade','Storage','Compact','AI'],state.filters.family)}</select></div><div class="filter"><label for="vendorFilter">HOST CPU</label><select id="vendorFilter">${selectOptions(['All','AMD','Intel'],state.filters.vendor)}</select></div><div class="filter"><label for="useFilter">WORKLOAD</label><select id="useFilter">${selectOptions(['All','General compute','Virtualization','Data & storage','AI & GPUs','Edge & branch','HPC & density'],state.filters.use)}</select></div></div><div class="results-info"><p id="modelCount" aria-live="polite"></p><button class="text-btn" data-reset-filters>Reset filters ↻</button></div><div class="model-grid" id="modelGrid"></div><div class="compare-tray" id="compareTray" hidden><p id="compareStatus" aria-live="polite"></p><div class="button-row"><button class="btn compact ghost" data-clear-compare>Clear</button><button class="btn compact primary" id="compareButton" data-compare>Compare selected →</button></div></div>
 <div class="warning"><strong>“Up to” means a configuration ceiling.</strong> CPU, memory, GPU and drive maxima can require different builds. Twin specifications are explicitly per node. Rack filtering also includes the selected AI racks; Compact groups edge and tower systems.</div>
 <section class="section"><h2>Where the rest of Supermicro fits</h2><div class="history-list"><article><span class="badge accent">MORE TWIN DESIGNS</span><h3 style="margin-top:16px">GrandTwin, BigTwin and FlexTwin</h3><p>GrandTwin emphasizes single-socket nodes. BigTwin covers dual-socket multi-node designs. FlexTwin targets dense HPC and liquid-cooled configurations. Node count and shared resources depend on the exact model.</p>${sourceLink('portfolio','Explore the broader families')}</article><article><span class="badge accent">BEYOND A SINGLE SERVER</span><h3 style="margin-top:16px">Rack-scale AI and validated solutions</h3><p>Complete AI deployments also need fabrics, storage, power, cooling and software. Supermicro’s wider portfolio extends into rack-scale accelerator solutions and newer H15 platforms.</p>${sourceLink('h15','See H15 portfolio context')}</article></div><div class="lesson" style="margin-top:16px"><span class="badge accent">SERVERS VS. EXPANSION</span><h3 style="margin-top:14px">A storage enclosure is not always a server.</h3><p>The selected SSG systems include host CPUs and run software. JBOD / JBOF expansion enclosures add drives or flash to another system; they do not imply an independent general-purpose host.</p><p>MicroCloud and MicroBlade add entry-class multi-node choices, including EPYC 4005. MicroBlade and SuperBlade have different enclosure and module rules; the AMD SuperBlade selected here needs a compatible 8U enclosure. ${sourceLink('genSm4005','Entry multi-node family context')} · ${sourceLink('amdbladeFamily','Blade enclosure matrix')}</p><p>This guide selects examples across generations. Inclusion is not a claim of local stock, universal availability or a complete catalog.</p>${sourceLink('storagefamily','Explore storage servers and enclosures')}</div></section><div class="next-lesson"><p>Next: understand the processor platforms.</p><a class="btn primary" href="#platforms">AMD & Intel →</a></div>`;}
// END lineup
// BEGIN platforms
function platforms(){return `${intro('03 / THE CPU PLATFORM MAP','Start with the host. Keep the system in view.','Supermicro offers AMD and Intel across several physical designs. CPU family, socket count, memory topology and expansion all matter.')}
 <div class="two-col"><article class="vendor-panel amd"><span class="badge amd">AMD CPU PLATFORMS</span><h2>EPYC</h2><p>Four EPYC branches illustrate different sizes of server.</p><ul><li><b>4004 / 4005:</b> AM5 entry tower; four UDIMM slots across two memory channels.</li><li><b>8004 / 8005:</b> SP6 edge; six RDIMM slots, with a later 8005 refresh.</li><li><b>9004 / 9005:</b> SP5 Hyper, CloudDC, GrandTwin, PCIe GPU and integrated AI hosts.</li><li><b>9006:</b> H15 / SP7 GrandTwin and the announced 8U-enclosure SuperBlade.</li><li><b>One or two sockets:</b> independent of whether the chassis holds one node or several.</li></ul>${modelButtons(['amdentry','edge','amdcloud','amd2','h15twin','amdblade'])}</article><article class="vendor-panel intel"><span class="badge intel">INTEL CPU PLATFORMS</span><h2>Xeon</h2><p>Entry servers and large AI hosts use different Xeon platforms.</p><ul><li><b>6300 / E-2400:</b> entry tower.</li><li><b>4th / 5th Gen Xeon Scalable:</b> selected PCIe GPU chassis.</li><li><b>Xeon 6 6500P / 6700P / 6700E:</b> selected racks, Twin and blades.</li><li><b>6900P:</b> the Gaudi 3 host example.</li></ul>${modelButtons(['tower','pciegpu','intelcloud','intelhyper','blade','gaudi'])}</article></div>
 <div class="takeaway"><span class="symbol">≠</span><div><h3>The CPU brand does not choose the accelerator.</h3><p>AMD hosts appear with both NVIDIA HGX and AMD Instinct. The AMD entry tower also lists Radeon Pro workstation graphics, which are different products from Instinct. Intel hosts appear with NVIDIA HGX and Intel Gaudi. OAM, SXM and PCIe card designs have different qualification rules.</p></div></div>
 <section class="section"><div class="chapter-heading"><h2>The practical platform map</h2><span class="small">Select a model to inspect the details.</span></div><div class="table-scroll"><table><caption class="visually-hidden">Selected Supermicro systems by host processor vendor</caption><thead><tr><th scope="col">Design</th><th scope="col">AMD examples</th><th scope="col">Intel examples</th></tr></thead><tbody>${[['1U · one socket',['edge'],['intelcloud']],['2U · one socket',['amdcloud'],[]],['1U · two sockets',['amd1'],['petascale']],['2U · two sockets',['amd2'],['intelhyper']],['Multi-node chassis',['amdtwin','h15twin'],['inteltwin']],['Blade in shared enclosure',['amdblade'],['blade']],['Edge / entry tower',['edge','amdentry'],['tower']],['High-capacity storage',[],['capacity']],['PCIe GPU-focused chassis',['amdpcie'],['pciegpu']],['Integrated eight-accelerator AI',['instinctair','instinctliquid','amdhgx'],['hgx','gaudi']]].map(([label,a,b])=>`<tr><th scope="row">${label}</th><td>${a.length?modelButtons(a):'<span class="support-none">No selected example</span>'}</td><td>${b.length?modelButtons(b):'<span class="support-none">No selected example</span>'}</td></tr>`).join('')}</tbody></table></div><p class="matrix-note">Selected learning examples, not a vendor-wide compatibility matrix or performance ranking. Empty cells do not mean a design is unavailable elsewhere in the portfolio.</p></section>
 <section class="section two-col"><article class="lesson"><div class="eyebrow">CORES, CHANNELS AND MODULES</div><h3>Xeon 6 is not one interchangeable part.</h3><p>P-core and E-core processors have different supported configurations. MRDIMM appears in qualified P-core builds. A platform listing Xeon 6 does not imply support for every Xeon 6 or Xeon 6+ part.</p><p>SYS-112C-TN has sixteen DIMM slots across eight memory channels. Slots, channels, capacity and speed describe different things.</p>${sourceLink('intelcloud','CPU and memory configuration')}</article><article class="lesson"><div class="eyebrow">THE REVISION CAN MATTER</div><h3>Same model family, different qualification.</h3><p>AS-2015CS-TNR and AS-2115GT-HNTR require motherboard revision 2.x for EPYC 9005. The H15 GrandTwin uses a different SP7 platform for EPYC 9006.</p><p>Keep the complete system name, board revision and firmware release when checking a CPU upgrade. AS-2126HS-TN has 24 RDIMM slots, one per memory channel; its qualified 9005 / 9004 builds list 6400 / 4800 MT/s. Capacity alone does not describe bandwidth.</p>${sourceLink('amdcloud','Revision requirement')} · ${sourceLink('h15twin','SP7 model specifications')}</article></section>
 <section class="section three-col"><article class="lesson"><div class="big-number">01</div><h3>One server’s controller</h3><p>A BMC handles hardware status, remote console and power operations. SYS-112C-TN demonstrates a DC-SCM / OpenBMC implementation; management is not identical across every model.</p>${sourceLink('bmc','BMC resources')}</article><article class="lesson"><div class="big-number">02</div><h3>Fleet and resource tools</h3><p>SSM provides fleet hardware monitoring and operations. SuperCloud Composer addresses resource management and orchestration. Check supported hardware and licensing.</p>${sourceLink('ssm','Server Manager')} · ${sourceLink('composer','SuperCloud Composer')}</article><article class="lesson"><div class="big-number">03</div><h3>The workload software</h3><p>Linux, Windows Server and hypervisors run applications and VMs. Hardware management software does not replace them. OS, driver and accelerator runtime qualification are separate checks.</p>${sourceLink('os','OS compatibility lookup')}</article></section><div class="next-lesson"><p>Next: decode storage, accelerators and cooling.</p><a class="btn primary" href="#components">Storage & GPUs →</a></div>`;}
// END platforms
// BEGIN driveLessons
const driveLessons={
 sff:{label:'2.5-inch SFF',art:'',title:'A bay size, not a protocol.',text:'SFF usually refers to a 2.5-inch drive position. NVMe, SAS and SATA need different supported electrical paths, even when the carrier looks similar.',notice:'AS-2126HS-TN offers eight SFF bays by default and layouts up to twenty-four. Its detailed storage table lists NVMe / SATA; use the exact backplane and cabling rules.',ids:['amd2','intelhyper'],source:'amd2'},
 lff:{label:'3.5-inch LFF',art:'lff',title:'Physical room for capacity.',text:'LFF usually means a 3.5-inch bay, often populated with capacity-oriented hard drives. Raw drive capacity is reduced by RAID, spares and software overhead.',notice:'SSG-542B-E1CR90 puts ninety large drives in a top-loading 4U chassis. It is about 1.1 meters deep, so rack fit and service clearance matter as much as rack-unit height.',ids:['capacity','amdcloud','tower'],source:'capacity'},
 e3:{label:'E3.S NVMe',art:'e3',title:'Dense enterprise flash.',text:'E3.S belongs to the EDSFF shape family. Its physical profile and cooling design differ from SFF drives. A matching NVMe protocol does not make the carriers interchangeable.',notice:'SSG-122B-NE316R has sixteen E3.S 1T bays in 1U. SBI-622B-1NE34 has four E3.S bays on a compute blade.',ids:['petascale','blade'],source:'petascale'},
 e1:{label:'E1.S NVMe',art:'e1',title:'Another shape for enterprise SSDs.',text:'E1.S and E3.S are separate physical formats. Thickness, carriers, airflow and the backplane must match the qualified drive.',notice:'SYS-212GT-HNF supports up to eight E1.S drives per node. Alternative four-drive configurations free room for other expansion. SYS-822GS-NB3RT uses eight E1.S bays in an HGX system.',ids:['inteltwin','hgx'],source:'inteltwin'},
 m2:{label:'M.2 boot / data',art:'m2',title:'Small modules with a separate job.',text:'M.2 describes a compact module, not a storage protocol. Modules may use SATA or NVMe; mirroring and serviceability depend on the host adapter and configuration.',notice:'Many selected systems have separate M.2 positions for boot or local storage. Their presence does not guarantee hot-swap access or a hardware RAID mirror.',ids:['amdcloud','blade','instinctair'],source:'amdcloud'}
};
// END driveLessons
// BEGIN components
function components(){return `${intro('04 / UNDER THE COVER','Decode storage. Understand acceleration.','Drive shape, storage protocol, accelerator form and cooling describe different parts of the design. Learn them separately, then combine them into a qualified system.')}
 <section class="panel"><div class="panel-head"><div><div class="eyebrow">STORAGE EXPLORER</div><h2 style="margin-top:8px">What does the drive label tell you?</h2><p>Select a format to connect the terminology to real platforms.</p></div><span class="badge accent">FORM ≠ PROTOCOL</span></div><div class="storage-lab"><div class="lab-controls" aria-label="Drive formats">${Object.entries(driveLessons).map(([id,d])=>`<button data-drive="${id}" aria-pressed="${state.drive===id}">${d.label}</button>`).join('')}</div><div class="lab-content" id="driveLesson"></div></div></section>
 <div class="two-col section"><article class="lesson"><h3>The backplane completes the connection.</h3><p>The drive carrier is what you touch. The backplane, cables and controller decide how the device connects. A RAID controller and an HBA also serve different storage designs.</p><p>AS-2015CS-TNR starts with SATA bays and needs additional parts for its optional SAS / NVMe paths. Similar-looking fronts can hide different configurations.</p>${sourceLink('amdcloud','Drive and controller options')}</article><article class="lesson"><h3>Three kinds of capacity to keep separate.</h3><p><b>Host DDR5:</b> CPU working memory.<br><b>GPU HBM / graphics memory:</b> accelerator working memory.<br><b>SSDs and disks:</b> persistent software and data.</p><p>More SSD space does not increase HBM. Software and interconnects determine how several accelerators cooperate on a large workload.</p><a href="#sources/glossary">Explore the terminology →</a></article></div>
 <section class="section"><div class="chapter-heading"><h2>Three ways to build accelerator compute</h2><span class="small">The physical platform changes the options.</span></div><div class="three-col"><article class="lesson"><div class="big-number">01</div><h3>Add a qualified PCIe card.</h3><p>General-purpose Hyper and CloudDC models can host selected cards. The 2U AMD Hyper lists NVIDIA accelerators and AMD Instinct MI210.</p>${modelButtons(['amd2','intelhyper'])}<p class="small muted">Check height, width, power, risers, airflow and the qualified GPU list.</p>${sourceLink('gpu','GPU qualification resources')}</article><article class="lesson"><div class="big-number">02</div><h3>Choose a GPU-focused chassis.</h3><p>The Intel 4U SYS-421GE-TNRT uses PCIe switches. The AMD 5U AS-5126GS-TNRT directly attaches qualified PCIe GPUs, including Instinct MI350P, to the hosts. Its eight-GPU limit is different from its nine/ten expansion-slot layouts.</p>${modelButtons(['pciegpu','amdpcie'])}<p class="small muted">A PCIe switch is not the same thing as an HGX NVLink fabric.</p>${sourceLink('pciegpu','PCIe GPU platform')}</article><article class="lesson"><div class="big-number">03</div><h3>Use an integrated accelerator platform.</h3><p>AMD Instinct and Intel Gaudi examples use OAM modules. NVIDIA HGX B300 uses SXM. The baseboard, links and cooling are part of the qualified design.</p>${modelButtons(['instinctair','hgx','amdhgx','gaudi'])}<p class="small muted">These module names do not imply interchangeable hardware or software.</p>${sourceLink('gaudidesign','Gaudi platform architecture')}</article></div></section>
 <section class="panel section"><div class="panel-head"><div><div class="eyebrow">THE CPU / ACCELERATOR CROSSOVER</div><h2 style="margin-top:8px">Documented pairings worth remembering</h2></div></div><div class="table-scroll" style="border:0;border-radius:0"><table><caption class="visually-hidden">Supermicro host CPU and accelerator examples</caption><thead><tr><th scope="col">Host CPU</th><th scope="col">Accelerator example</th><th scope="col">Server</th><th scope="col">What to notice</th></tr></thead><tbody>
 <tr><th scope="row">AMD EPYC 9004 / 9005</th><td>NVIDIA H100 NVL / L40S or AMD MI210 PCIe</td><td>${modelButtons(['amd2'])}</td><td>Two accelerator vendors appear on one qualified Hyper platform.</td></tr>
 <tr><th scope="row">AMD EPYC 9004 / 9005</th><td>8 × AMD MI325X or MI350X OAM</td><td>${modelButtons(['instinctair'])}</td><td>8U air-cooled integrated GPU system.</td></tr>
 <tr><th scope="row">AMD EPYC 9004 / 9005</th><td>8 × AMD MI325X or MI355X OAM</td><td>${modelButtons(['instinctliquid'])}</td><td>4U liquid-cooled model with its own GPU qualification.</td></tr>
 <tr><th scope="row">AMD EPYC 9005</th><td>8 × NVIDIA B300 SXM</td><td>${modelButtons(['amdhgx'])}</td><td>The same accelerator family is documented in an AMD-host design.</td></tr>
 <tr><th scope="row">AMD EPYC 9004 / 9005</th><td>Up to 8 × AMD Instinct MI350P PCIe</td><td>${modelButtons(['amdpcie'])}</td><td>A PCIe accelerator system has different links and population rules from OAM.</td></tr>
 <tr><th scope="row">AMD EPYC 4004 / 4005 or Ryzen</th><td>AMD Radeon Pro W7500 / W7800</td><td>${modelButtons(['amdentry'])}</td><td>Qualified workstation graphics are distinct from Instinct AI accelerators.</td></tr>
 <tr><th scope="row">Intel Xeon 6700P</th><td>8 × NVIDIA B300 SXM</td><td>${modelButtons(['hgx'])}</td><td>HGX with internal NVLink / NVSwitch and separate cluster networking.</td></tr>
 <tr><th scope="row">Intel Xeon 6900P</th><td>8 × Intel Gaudi 3 OAM</td><td>${modelButtons(['gaudi'])}</td><td>AI accelerator platform with Ethernet / RoCE scale-out.</td></tr>
 <tr><th scope="row">AMD EPYC 8004</th><td>NVIDIA L4 PCIe; recheck qualification for an 8005 build</td><td>${modelButtons(['edge'])}</td><td>The system now lists 8005 CPUs; the named L4 source documents an 8004 build.</td></tr>
 </tbody></table></div></section>
 <div class="warning"><strong>Qualified alternatives are separate builds.</strong> A page listing MI325X and MI350X does not authorize mixing them in one baseboard. AMD CPUs do not imply every Instinct GPU is supported; the same applies to Intel and NVIDIA. ${sourceLink('gpu','Check model-level GPU support')}</div>
 <section class="section"><div class="chapter-heading"><h2>Cooling is part of the platform</h2><span class="small">Follow the heat beyond the server.</span></div><div class="three-col"><article class="lesson"><div class="cooling-glyph" aria-hidden="true">↻</div><h3>Air-cooled systems</h3><p>Fans carry heat into the data-center air. The selected eight-module Instinct OAM, HGX B300 and Gaudi 3 air systems are 8U designs. The PCIe MI350P example is 5U; all need qualified power and airflow.</p>${modelButtons(['instinctair','hgx','amdhgx','gaudi'])}</article><article class="lesson"><div class="cooling-glyph" aria-hidden="true">≈</div><h3>Direct-to-chip liquid</h3><p>Cold plates remove heat from selected components through a liquid loop. The 4U Instinct liquid model still has fans and needs compatible facility and service arrangements.</p>${modelButtons(['instinctliquid'])}${sourceLink('instinctliquid','Liquid system requirements')}</article><article class="lesson"><div class="cooling-glyph" aria-hidden="true">⇄</div><h3>Rack and facility design</h3><p>Rack power, airflow, coolant distribution, heat rejection and maintenance access determine whether the full deployment works. A smaller U count does not mean a simpler installation.</p>${sourceLink('instinctdesign','Compare the air and liquid platforms')}</article></div></section>
 <section class="section"><h2>From an option to a supported system</h2><div class="compat-steps"><article class="compat-step"><h3>Exact platform</h3><p>Full SKU, motherboard revision, CPU and accelerator build.</p></article><article class="compat-step"><h3>Population rules</h3><p>DIMMs, backplanes, controllers, risers and GPU combinations.</p></article><article class="compat-step"><h3>Facility needs</h3><p>Rack fit, electrical power, airflow, coolant and service access.</p></article><article class="compat-step"><h3>Software stack</h3><p>OS, hypervisor, firmware, drivers and accelerator runtime.</p></article></div><p class="small">${sourceLink('os','OS certification')} · ${sourceLink('resources','Qualified product resources')}</p></section><div class="next-lesson"><p>Ready to connect the dots?</p><a class="btn primary" href="#quiz">Test your knowledge →</a></div>`;}
// END components
// BEGIN sourcesView
function sourcesView(){return `${intro('06 / KEEP LEARNING','Go straight to the evidence.','A source-linked learning snapshot reviewed on October 9, 2026. Original illustrations simplify official product figures; component tours are logical schematics.')}
 <div class="two-col"><article class="lesson"><h3>What this guide covers</h3><p>${models.length} selected Hyper, CloudDC, GrandTwin, SuperBlade, storage, edge, tower and accelerator platforms. These examples teach physical designs and their CPU, memory, drive, GPU and management choices.</p><p>Models span several generations, including H15 / EPYC 9006. The guide is not an exhaustive catalog or live ordering / availability system.</p></article><article class="lesson"><h3>How source differences were handled</h3><p>Detailed model specifications take priority over portfolio headlines. Hyper storage summaries can disagree about SAS; the selected AMD Hyper profile follows its detailed NVMe / SATA table.</p><p>Conflicting CPU core / memory-channel counts on storage pages and inconsistent B300 memory-speed figures are omitted. Current model qualification takes priority over older datasheet availability labels. The edge page now lists 8005 and 768 GB; older store builds remain 8004 / 576 GB. These are configuration-specific references, not an automatic upgrade promise.</p></article></div>
 <section class="section" id="glossary"><div class="eyebrow">PLAIN-ENGLISH REFERENCE</div><h2 style="margin-top:10px">Keep the acronyms under control.</h2><label class="visually-hidden" for="glossarySearch">Search glossary</label><input class="glossary-search" id="glossarySearch" type="search" placeholder="Find a term: GrandTwin, OAM, AIOM…"><div class="glossary" id="glossaryList">${Object.entries(glossary).map(([term,def])=>`<details data-term="${esc((term+' '+def).toLowerCase())}"><summary>${esc(term)}</summary><p>${def}</p></details>`).join('')}</div><p id="glossaryEmpty" class="muted" hidden>No matching terms. Try a shorter search.</p></section>
 <section class="section"><div class="eyebrow">OFFICIAL SOURCE LIBRARY</div><h2 style="margin-top:10px">Follow the document behind the detail.</h2><p class="muted small">“Reviewed” is this guide’s access date. Verified publication dates are labeled separately. Illustrations are not service drawings, and grouped diagram lines are not physical wiring plans. Linked documents can change; no source files were supplied by the user.</p><div class="source-list">${Object.entries(sources).map(([id,s])=>`<article class="source-item" id="source-${id}">${sourceLink(id)}<p>${s.scope}</p><small>${s.date} · ${s.loc}</small></article>`).join('')}</div></section>`;}
// END sourcesView
