# Generate a source-linked gallery of the actual SVGs used by the dashboard.
import html
import json
import re
from urllib.parse import quote

def render_illustration_review(out, catalog, manifest, review, source):
    esc = lambda v: html.escape(str(v))
    changed=set(review['changes'])
    regressions={'hpe:sy480','hpe:ml350','dell:t560','lenovo:st650','lenovo:se100','supermicro:capacity'}
    ordered=sorted(catalog['models'],key=lambda m:(m['id'] not in changed,m['id'] not in regressions,m['oem'],m['name']))
    cards=[]
    for m in ordered:
        p=m['illustration']; mem=m['computeMemory']; new=m['id'] in changed
        status='Redrawn from OEM reference' if new else ('Exterior not established' if p['reviewStatus']=='schematic' else 'Existing model illustration')
        dims=mem.get('dimmLabel') or (str(mem['dimmSlots']) if mem['dimmSlots'] is not None else 'Not confirmed')
        dpc=' / '.join(str(n)+'DPC' for n in mem['dpc']) or 'Not confirmed'
        dims_class='unconfirmed' if mem['dimmSlots'] is None else ''
        dpc_class='unconfirmed' if not mem['dpc'] else ''
        prefix='review_'+m['id'].replace(':','_')+'_'
        art=re.sub(r'id="([^"]+)"',lambda x:'id="'+prefix+x[1]+'"',m['art'])
        art=re.sub(r'url\(#([^)]+)\)',lambda x:'url(#'+prefix+x[1]+')',art)
        art=re.sub(r'href="#([^"]+)"',lambda x:'href="#'+prefix+x[1]+'"',art)
        features=''.join('<li>'+esc(f)+'</li>' for f in p['features'])
        cards.append(f'<article data-changed="{str(new).lower()}" data-regression="{str(m["id"] in regressions).lower()}" data-model="{esc(m["id"])}"><div class="eyebrow">{esc(m["oemName"])}<span class="state">{esc(status)}</span></div><div class="art">{art}</div><h2>{esc(m["name"])}</h2><p class="view">{esc(p["view"])}</p><div class="facts"><span><small>MAX PROCESSORS</small><b>{mem["maxProcessors"]}</b></span><span><small>DIMM SLOTS</small><b class="{dims_class}">{esc(dims)}</b></span><span><small>DPC SUPPORT</small><b class="{dpc_class}">{esc(dpc)}</b></span></div><p class="scope">Per {esc(mem["scope"])} · slots with all processors</p><details><summary>Reference and configuration</summary><ul>{features}</ul><p>{esc(p["caveat"])}</p><a href="{esc(p["sourceUrl"])}" target="_blank" rel="noopener">Official OEM reference ↗</a><p class="scope">{esc(p["locator"])}</p></details><a class="open" href="index.html#finder?model={quote(m["id"],safe="")}">Open platform →</a></article>')
    schematic=[m['name'] for m in catalog['models'] if m['illustration']['reviewStatus']=='schematic']
    page="""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Server illustration review · ChipIndex</title><style>
:root{color-scheme:dark;font-family:Arial,sans-serif;background:#090c11;color:#e8edf4}*{box-sizing:border-box}body{max-width:1450px;margin:auto;padding:28px 24px}a{color:#ffca65;text-decoration:none}nav{display:flex;gap:24px;flex-wrap:wrap;font-size:13px}h1,h2,.eyebrow,.filters,.facts{font-family:ui-monospace,Consolas,monospace}h1{font-size:clamp(28px,4vw,40px);margin-bottom:12px}header>p{max-width:960px;color:#aebdd0;line-height:1.6}.filters{display:flex;gap:10px;flex-wrap:wrap;margin:22px 0}button{min-height:44px;border:1px solid #374657;border-radius:6px;padding:10px 16px;background:#17202a;color:#dce8f2;cursor:pointer}button[aria-pressed=true]{border-color:#ef3345;background:#352028}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}article{min-width:0;border:1px solid #34404d;border-radius:10px;background:#171d24;padding:20px;display:flex;flex-direction:column}.eyebrow{font-size:11px;color:#99b9d7;display:flex;gap:12px;justify-content:space-between}.state{text-align:right;color:#93c4b1;font-size:10px}.art{height:192px;display:grid;place-items:center}.art svg{width:100%;height:100%;max-height:192px}h2{font-size:18px;margin:8px 0}.view{min-height:36px;font-size:12px;color:#a9bdd2;line-height:1.5}.facts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-top:1px solid #bd994a;border-bottom:1px solid #35404e;background:#101820}.facts>span{padding:12px 7px;border-right:1px solid #35404e}.facts>span:last-child{border:0}.facts small{font-size:9px;display:block;color:#aebed0;margin-bottom:7px}.facts b{display:block;font-size:20px;color:#f3d289;overflow-wrap:anywhere}.facts b.unconfirmed{font-size:13px;line-height:1.5}.scope{font-size:11px;color:#9cafc5;line-height:1.5}details{font-size:12px;color:#b2c4d7;line-height:1.6;margin:10px 0 18px}summary{cursor:pointer;min-height:28px}ul{padding-left:16px}.open{font-size:12px;margin-top:auto;padding-top:8px}article[hidden]{display:none}footer{border-top:1px solid #34404d;margin-top:28px;padding-top:20px;font-size:12px;color:#9dafc3;line-height:1.6}code{overflow-wrap:anywhere}@media(max-width:1000px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){body{padding:22px 14px}.grid{grid-template-columns:1fr}.art{height:175px}.facts b{font-size:18px}.eyebrow{font-size:10px}}
</style></head><body><nav><a href="../">Products</a><a href="../benchmarks/">Benchmarks</a><a href="index.html#finder">Platforms</a><a href="spec-verification.html">Specification review</a></nav><header><p class="eyebrow">CHIPINDEX · SERVER ILLUSTRATIONS</p><h1>Recognizable servers. Traceable references.</h1><p>Model-specific drawings based on official OEM photos and front-view diagrams. The illustrated configuration is one example; a drawing does not combine every storage, CPU or GPU option. Processor counts, DIMM slots and DPC remain separate source-backed facts.</p></header>"""
    page+=f'<div class="filters"><button data-mode="changed" aria-pressed="true">Redrawn ({len(changed)})</button><button data-mode="regression" aria-pressed="false">Earlier formatting fixes ({len(regressions)})</button><button data-mode="all" aria-pressed="false">All platforms ({len(ordered)})</button></div><p id="count" class="scope" aria-live="polite"></p><div class="grid">'+''.join(cards)+'</div>'
    page+=f'<footer><b>Still schematic:</b> {esc(", ".join(schematic))}. These remain explicitly labeled because an exact exterior was not established by the reviewed references.<br><a href="illustration-review.json">Review record</a> · <a href="implementation-review.html">Implementation evaluation</a><br>UI <code>{esc(manifest["buildHash"])}</code></footer>'
    page+="""<script>function show(mode){let count=0;document.querySelectorAll('article').forEach(card=>{const visible=mode==='all'||card.dataset[mode==='changed'?'changed':'regression']==='true';card.hidden=!visible;if(visible)count++;});document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));document.getElementById('count').textContent=count+' illustrations in this view';}document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.mode)));show('changed');</script></body></html>"""
    data={**review,'catalogHash':manifest['contentHash'],'buildHash':manifest['buildHash'],'remainingSchematics':schematic,'scope':'Source-inspected exterior review; no hardware/support facts changed. An illustrative configuration is not a bill of materials.'}
    for file,value in [('illustration-review.html',page),('illustration-review.json',json.dumps(data,indent=2,ensure_ascii=False)+'\n')]:
        path=out/file; b=value.encode('utf-8');path.write_bytes(b);assert path.read_bytes()==b
    for path in source.glob('art-review-*.json'):
        target=out/path.name;b=path.read_bytes();target.write_bytes(b);assert target.read_bytes()==b
